### ISSUE TITLE
Research why buildifier is rebuilt from source

### ISSUE THREAD

**Issue by furtnerl** [dynatrace-oss/barista#1019]
When trying to execute the //:buildifier target from a pre-commit hook, we saw that it had to rebuild the buildifier bin for every commit. This is unacceptable for pre-commit hooks as it would be slowing down the developer workflow.

Goal of this issue is to check why buildifier had to be rebuilt, or find a way to execute buildifier for every commit without slowing down developers

**Comment by lukasholzer** [comment]
For now we removed buildifier from the bazel workspace. I think we might use the npm version of the buildifier that should be already built.
