### ISSUE TITLE
running lint-styles target fails locally, succeeds in ci: No files matching the pattern

### ISSUE THREAD

**Issue by christian-fischer** [dynatrace-oss/barista#1024]
# Bug Report

## Expected Behavior

I expect lint-styles to also succeed locally, when it succeeds on the remote branch in the ci

## Current Behavior

lint-styles fails with multiple errors, all starting with "No files matching the pattern ..." 
(full log in attachment)

## Steps to Reproduce

1. checkout `barista/extend-filter-field-for-partial-data`
2. run `npm run affected:stylelint -- --parallel`

## Context (Environment)

Running on Windows 10 locally.
The ci run on the remote branch succeeds: https://app.circleci.com/pipelines/github/dynatrace-oss/barista/5622/workflows/cb5b28a6-f7e1-4374-9020-762b5d061fee/jobs/32415/steps

### Used Versions:

- **node**: v12.16.1
- **npm**: 6.13.4
- **@dynatrace/barista-components**: branched from master today

## Attachments

[lint-styles.log](https://github.com/dynatrace-oss/barista/files/4634186/lint-styles.log)

**Comment by lukasholzer** [comment]
Hey, Thank you very much for submitting this issue! We will take further investigations on this topic. Maybe @bardosmisi can you try it out on your machine as you use Windows 10?

**Comment by christian-fischer** [comment]
I noticed this popup in vscode as well, not sure if this is related or not: 
![image](https://user-images.githubusercontent.com/5974170/82295059-71745f80-99af-11ea-8489-a77e95b38642.png)

**Comment by christian-fischer** [comment]
I rebased my branch to the upstream master today, the commit `522e34d4 build(workspace): Fix affected linting on windows.` is now part of the branch; but running `npm run lint` is still failing on my machine - same error

**Comment by christian-fischer** [comment]
update: tried it a second time: now `npm run lint` finally succeeds
