### ISSUE TITLE
quick-filter: expose inputChange and currentFilterChanges from filter-field

### ISSUE THREAD

**Issue by christian-fischer** [dynatrace-oss/barista#1025]
# Feature Request

## Summary

In order to use async/partial options in the filter-field part of quick-filter, I'd like to use the `inputChange` and `currentFilterChanges` outputs. 

## Feature Description

**Problem**: currently the quick-filter does not expose the `inputChange` and `currentFilterChanges` outputs from the filter-field. Therefore no async/partial options are possible. But we would need that in order to do server-side filtering for our async tag loading (there are way too many tags to implement this otherwise in a well scaling manner)

**Solution**: expose those two events from the filter-field in the quick-filter. We are fine with that those async/partial filters will only show up in the filter-field part of the quick-filter and not in the sidebar.

**Comment by lukasholzer** [comment]
Hey, thank you very much for filing this feature request!
It is pretty awesome that you are playing around with our experimental quick filter!

Are you willing to contribute this feature to the quick filter? This would be very helpful if you need this issue in the near future.

**Comment by christian-fischer** [comment]
Yes, at least it seems like a small change - so I could take care of that.

**Comment by tomheller** [comment]
> Yes, at least it seems like a small change - so I could take care of that.

@christian-fischer yes, if you like, please take care of this one.  I agree that this should be a fairly small change.

**Comment by lukasholzer** [comment]
I think it should be more a proxy of the events to the quick-filter.
