### ISSUE TITLE
Barista: Evaluate `most ordered`list.

### ISSUE THREAD

**Issue by rowa-audil** [dynatrace-oss/barista#1042]
# Feature Request

Our most ordered tile is currently a hardcoded list. 
**We should evaluate which are most ordered** and display them on the index page

Possible Solution: Calc the avg of visits on each page and the top 7 are displayed(/also saved in a list somewhere?).

**Comment by tomheller** [comment]
I'm guessing we first would need some sort of analytics. We can probably set something up within dynatrace to monitor the application. Since the infrastructure move of the deployment I don't think that this has been set up correctly again.

**Comment by rowa-audil** [comment]
Will do as soon as I am tackling this
