### ISSUE TITLE
[Table]: simple column comparator @Input causes error on navigation

### ISSUE THREAD

**Issue by cprohinig** [dynatrace-oss/barista#1046]
# Bug Report
When setting a custom comparator function to a simple column via the template, and having this column sorting active, on page leave the following exception appears in the console:

`Error: "Cannot move a destroyed View in a ViewContainer!" `

## Expected Behavior

Custom comparator functions, when set in template should behave just like default sorting of columns or setting the comparator function via the dataSource.

## Current Behavior

Custom comparator functions, when set in template, cause an error when leaving the page.
Setting the comparator function via:
`dataSource.addComparatorFunction('colName', comparatorFn)`
is a possible workaround and does not cause the issue mentioned.

## Steps to Reproduce
1. Go to https://stackblitz.com/edit/github-bf3vmb
2. Sort "Memory combined" ASC (important, happens only in ascending in that example)
3. Click "Hide/Show" button

## Versions

**@dynatrace/barista-components**: 6.5.2

**Comment by tomheller** [comment]
Hi @cprohinig! Can you please attach a stackblitz example that reproduces the issue. 
It should not matter if you navigate away or destroy the component via an ngIf, either way I assume the problem exists when destroying the component.

**Comment by cprohinig** [comment]
I added a stackblitz as well as exact steps to reproduce.

**Comment by tomheller** [comment]
Nice, thank you. I will have a look as soon as my time allows it.

**Comment by lukasholzer** [comment]
This error is occurring again: https://stackblitz.com/edit/github-jazho6?file=package.json

**Comment by rowa-audil** [comment]
@tomheller What is the status on this?

**Comment by tomheller** [comment]
@rowa-audil We were not able to track down the issue as it occurs quite randomly during the tables lifecycle.

Please keep the issue open as we want to investigate this, but were not able to do so effectively at this point.

**Comment by rowa-audil** [comment]
The material table doesn't run into the same issue:

https://stackblitz.com/edit/material-table-example-bug

**Comment by tomheller** [comment]
> The material table doesn't run into the same bug:

Your example is also not quite complete. The barista table also does not run into problems, when not using simple-columns. 
Simple columns, especially ones that go beyond _simply formatting the input value a bit differently_, like ones changing their behavior based on a specific input on the component, are the real problem. 
Material does not have something like this, for this very reason. 
Their "advanced example" for a text column, is also only formatting the value passed into it by the table.
https://github.com/angular/components/blob/59d39840440d1dd35767de5290fec10960f583f5/src/components-examples/material/table/table-text-column-advanced/table-text-column-advanced-example.ts

**Comment by rowa-audil** [comment]
Thanks for pointing that out. I guess we'll have to rebuild the simple-column anyway

**Comment by tomheller** [comment]
Currently the plan is to split the simple columns into a header and a cell component, that can be used within the `*columnDef` directive (As we did for the order column https://github.com/dynatrace-oss/barista/tree/master/libs/barista-components/table/src/order).

The problem with this approach is that we need another solution to provide comparators to keep sorting simple.

**Comment by lukasholzer** [comment]
Moved to APM-266086
