### ISSUE TITLE
Radial chart with selection and relative values

### ISSUE THREAD

**Issue by subarroca** [dynatrace-oss/barista#1053]
# Feature Request

## Summary

Radial chart is missing some features, like displaying percent values and being selectable

## Feature Description

* Selection should be possible. either by input or by click
* Selection is not always needed so it should be disabled by default
* Values in legend should also be toggled from absolute to percent

**Comment by subarroca** [comment]
Adding inputs for `DtRadialChart`:

- `selectable`: `boolean`. Whether it accepts selections or not. Default: false
- `valueDisplayMode`: `absolute` | `percent`. Format of the values in legend. Default: absolute

Adding input and output for `DtRadialChartSeries`:
- `selected`: boolean
- `selectedChange`: Emitter

**Comment by tomheller** [comment]
@subarroca This looks good, thank you for adding this to the library.
