### ISSUE TITLE
barista: Fix code highlighting in barista

### ISSUE THREAD

**Issue by rowa-audil** [dynatrace-oss/barista#1055]
Code examples in barista aren't highlighted

**Expected Behavior**: Code should have highlighting

**Current Behavior**: Code isn't being highlighted

**Possible Solution**: Find out what causes it.

**Steps to Reproduce**: visit a page with code examples.

**Comment by lukasholzer** [comment]
Add E2E tests for barista that should check this, that this does not happen anymore in the future.
