### ISSUE TITLE
API Guardian

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1061]
# Feature Request

## Summary

Introduce a typescript api guardian to ensure semantic versioning

## Feature Description

Currently the repository and components keep growing and it gets harder and harder to ensure that no breaking changes go through during reviews.

By adding an automation that checks the new d.ts files against a static set on each PR we can ensure that no breaking changes go through. 
There is a package by the angular team that does exactly that. 
https://www.npmjs.com/package/ts-api-guardian

By adding this check we need to think about the impact on our workflow - what if my changes should include a breaking change - how can I accept these breaking changes? Is this only a maintainers responsibility? How is this done?

- [ ] Propose / Research a workflow for maintainers + contributors.
- [ ] Run check against current library and save them
- [ ] Add check to CI pipeline

**Comment by ffriedl89** [comment]
@thomaspink might know how the material team is doing it :)

**Comment by thomaspink** [comment]
material generates `d.ts` files for each package/component and stores it [here](https://github.com/angular/components/tree/master/tools/public_api_guard). It will then compare the new `d.ts` file with the stored one and if there is a change it will report an error. If the api change is intended by the developer, a [script](https://github.com/angular/components/blob/master/scripts/approve-api-golden.js) has to be run to update the stored `d.ts` file with a new one.

References:
https://github.com/angular/components/tree/master/tools/public_api_guard
https://github.com/angular/components/blob/master/scripts/approve-api-golden.js
https://github.com/angular/components/blob/master/tools/public_api_guard/generate-guard-tests.bzl
