### ISSUE TITLE
[Filter field] First entry always seems to be selected.

### ISSUE THREAD

**Issue by schobocop** [dynatrace-oss/barista#1070]
# Bug Report

## Expected Behavior

Only the entry where the mouse hovers over should be colored.

## Current Behavior

The entry where the mouse hovers and the first entry are colored

## Possible Solution

Should be fixed, since the user may be confused what he will select when clicking.

## Steps to Reproduce

Just try the first filter field here:
https://barista.dynatrace.com/components/filter-field
* also check autocomplete, select, and combobox

1. Go to https://barista.dynatrace.com/components/filter-field
2. Click on the first filter field
3. Hover over the third entry. You will see that the first entry is also colored as if "selected"

## Context (Environment)
Found on:
Firefox Version: 76.0.1
Chrome Version: 83.0.4103.61

### Used Versions:

- **node**: >=10.13.0
- **yarn**: >=1.13.0 <2
- **typescript**: 3.8.3
- **angular**: 9.1.0
- **@angular/cdk**: 9.2.0
- **@dynatrace/barista-components**: 6.5.2

## Attachments
![filter-field-bug](https://user-images.githubusercontent.com/12202020/82452748-f777cf80-9aaf-11ea-94b6-3524f77e2fd6.png)

**Comment by tomheller** [comment]
Hi @schobocop ! This is an issue that we are facing for a long time already. It's the autocomplete / select dropdown hover & active states look the exact same. 
We already had lengthy discussions with @dynatrace-oss/ux-core in the past, but I'm sure we can revisit this. 
Any thoughts on this one @dynatrace-oss/ux-core?

**Comment by ffriedl89** [comment]
I think it's time we do something about this :)

**Comment by ursula-wieshofer** [comment]
I agree, this has been postponed way too long already. A very popular way of showing the selected entry is just using bold font. This would then not interfere any more with our hover state (colored background). What do you think, should we change the active state to bold font?

**Comment by tomheller** [comment]
>What do you think, should we change the active state to bold font?
@ursula-wieshofer sorry for the late response. Do you want to remove the background of the selected and add the bold font or leave the background and add the bold font?

**Comment by ursula-wieshofer** [comment]
@tomheller I'd suggest to leave the background for the hover state and for the selected entry remove the background and use bold font ;)

**Comment by tomheller** [comment]
@ursula-wieshofer Alright, that leaves us with the following setup:

_selected_: No background, font bold
_hover_: background, font regular
_keyboardFocused_: background ?, font ?

Do we need to differentiate between hover and keyboard focus or should they look the same?

**Comment by ursula-wieshofer** [comment]
Up until now we never differentiated between hover and keyboard focus. I'd suggest to apply the same look, as I never saw a big problem here.

**Comment by rowa-audil** [comment]
>The entry where the mouse hovers and the first entry are colored

@schobocop We also need highlighting for keyboard support. That's why the first entry is already highlighted.
We are going to add a distinction between selected and focused/hovered as stated in the discussion with @ursula-wieshofer

**Comment by rowa-audil** [comment]
> Up until now we never differentiated between hover and keyboard focus. I'd suggest to apply the same look, as I never saw a big problem here.

@ursula-wieshofer Well we do need a distinction between keyboard selected and hovered styles. Currently both of them are highlighted the same.

**Comment by rowa-audil** [comment]
Maybe underlining the keyboard selected option might be the trick.

<img width="143" alt="image" src="https://user-images.githubusercontent.com/57528898/88643631-38005480-d0c2-11ea-9553-9dc7e513b50d.png">

@ffriedl89 @tomheller @ursula-wieshofer What do you think?
