### ISSUE TITLE
Scroll Spy active element bug

### ISSUE THREAD

**Issue by rowa-audil** [dynatrace-oss/barista#1072]
A problem with the generated TOC is that it sometimes highlights the wrong element. The easiest way of reproducing this is to go to https://barista.lab.dynatrace.org/components/alert, click on 'Alerts in use' int the TOC, watch 'Do's and don'ts' gets highlighted.

Also there is a weird behavior of scroll jumps in case of a narrow mode barista. We were able to repro this behavior on the charts barista page in a narrow window mode. Try to go to the pie chart example, hover it a couple of times, and notice unintentional scrolling.

**Comment by tomheller** [comment]
@rowaWill this be fixed by the refactoring done in #1110?

**Comment by rowa-audil** [comment]
Yes. :)
