### ISSUE TITLE
Barista - Next section

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1075]
# Feature Request

## Summary

We want to have a next section in Barista. 

## Feature Description

The code for the next section can live here in this repo, but the content should only be coming from our CMS.
For the next section we need to move a couple of elements that we have in the app.html.

Goal of this issue is to have a route /next only showing a dark page. No breadcrumbs, footer or navigation present. 

This route should only be available with configuration internal.

**Comment by lukasholzer** [comment]
### Steps for creating a new app.

1. Create a new app with the Angular Cli `ng generate @nrwl/angular:application --name=next --style=scss --prefix=x --routing --viewEncapsulation=Emulated`
2. Create a shared library for the data access of strapi `ng generate @nrwl/angular:library --name=data-access-strapi --directory=shared --simpleModuleName --no-interactive`.
3. Add to the Jenkinsfile located under `.deployment/barista/Jenkinsfile` into the stage **Build Barista** the build next section:
    ```sh
                if $PUBLIC_BUILD ; then
                  configuration='production'
                else
                  configuration='production-internal';

                  # Build next section of the design system
                 node \
                  --max_old_space_size=8192 \
                  ./node_modules/.bin/ng run next:build:production-internal
                fi
    ```
4. Go to the `angular.json` and rename the configuration production to `production-internal`
5. Go to the `.deployment/barista/barista-internal.Dockerfile` and add after the copy of the barista stuff the line
     `COPY dist/apps/next /var/www/next`
6. Adapt the Nginx configuration in `.deployment/barista/nginx/sites-available/barista-internal.conf` and move the root  statement into the `/` location add another location for the next section that is consuming the files from the next folder.
   ```
    location /next {
        root /var/www/next;
        try_files $uri $uri/ /index.html;
    }

    location / {
        root /var/www/barista;
        try_files $uri $uri/ /index.html;
    }

   ```
7. Try to run the Jenkins :)

**Comment by lukasholzer** [comment]
To leverage Strapi for content delivery extract the files

```
apps/barista-design-system/src/shared/services/page-guard.ts
apps/barista-design-system/src/shared/services/page.service.ts
apps/barista-design-system/src/shared/services/universal.interceptor.ts
```

into the new generated library and export them. After that adapt all paths from the relative URL to the new typescript path alias.

In the new app create a index-page component like in barista and add the BaPageGuard to the `canActivate` section. 

now you need a `json` file called index in the location that is provided via the environment under `dataHost`.

**Comment by rowa-audil** [comment]
Notes from the discussion (8.06) concern **How are the pages structured**:

The top navigation contains groupings of pages called _detail pages_(in the mock) which have the content.
Clicking on one group element opens an _overview_ or _intro_.
The sidenav then consists of sections for a grouping

**Comment by ffriedl89** [comment]
I think we can close this issue and have smaller followup issues that tackle the individual issues like sidenav, responsive top navigation and publishing
