### ISSUE TITLE
(font-styles.scss) default font definition for h3 is missing

### ISSUE THREAD

**Issue by DorotkaMakotka** [dynatrace-oss/barista#1081]
# Bug Report

## Expected Behavior

font-styless.scss (which is imported i.a. into cluster global styles) is expected to provide and ensure all font styling in accordance with barista design system, including the entry below:
```
h3 {
  @include dt-h3-font();
}
```
## Current Behavior

Style definition for h3 is missing (since https://github.com/dynatrace-oss/barista/pull/550/files?file-filters%5B%5D=.scss)

## Steps to Reproduce

1. 

### Used Versions:

- **node**: 
- **npm**: 
- **typescript**: 
- **angular**: 
- **@angular/cdk**: 
- **@dynatrace/barista-components**:

**Comment by tomheller** [comment]
Thanks @DorotkaMakotka for noticing and fixing this 👍

**Comment by DorotkaMakotka** [comment]
(I'll push the fix in a moment)
