### ISSUE TITLE
[Filter-field] Disabled state is not working (docs/stackblitz)

### ISSUE THREAD

**Issue by areknow** [dynatrace-oss/barista#1097]
# Bug Report

The disabled filter-field example does not behave as intended. The filters are modifiable even though the filter field is set to disabled state.

## Expected Behavior

No filters should be modifiable.

## Current Behavior

Filters are removable and the clear all button removes all filters.

## Steps to Reproduce

https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleFilterFieldDisabled/

Thanks!

**Comment by tomheller** [comment]
Hi @areknow!
Thanks for reporting this one. This seems to be a general issue that if filters are set programmatically after the disable state is set, that filters are not marked as disabled. I will have a look to and see if we can fix that one quickly.
