### ISSUE TITLE
Confirmation dialog prevents mouse events from elements even when it is hidden

### ISSUE THREAD

**Issue by mohamediab** [dynatrace-oss/barista#1103]
# Bug Report
## Expected Behavior

Confirmation dialog should not interfere with the screen when it is hidden.

## Current Behavior

Confirmation dialog blocks all mouse events on table row although it is hidden.

## Steps to Reproduce

1. Have a screen that includes both a table and confirmation dialog
2. have multiple rows for table, the row overlapping with the confirmation dialog is not clickable and doesn't get any mouse events.

## Context (Environment)

- Wants to have the confirmation dialog show only when i click on a button in the expandable table row.

### Used Versions:

- **@dynatrace/barista-components**: 7.0.0

## Attachments

![confirmation_dialog](https://user-images.githubusercontent.com/60917703/83605552-6527ff00-a578-11ea-8e68-e489d38a4c6e.PNG)

**Comment by ffriedl89** [comment]
It's also reproducible on barista - https://barista.lab.dynatrace.org/components/confirmation-dialog if you scroll so the button of one of the examples is at the bottom of the screen the hidden confirmation dialog blocks interaction.
