### ISSUE TITLE
Enhance DtFormattedValue with full display unit

### ISSUE THREAD

**Issue by obarcelonap** [dynatrace-oss/barista#1126]
# Feature Request

## Summary

Expose the full display unit in DtFormattedValue.

## Feature Description

After using a formatter returning a DtFormattedValue instance there are use cases where the unit needs to be styled differently (eg. different font size or color).
Currently the full display unit is a composition of displayUnit, displayRateUnit and displayWhiteSpace and is implemented within toString method of DtFormattedValue.

### Propostions
1. Add a new optional property in FormattedData interface computed on the getter of formattedData.
2. Add new getter in DtFormattedValue class which computes the fullDisplayUnit.

Both proposals require:
1. Extract composition of fullDisplayUnit from toString to a helper method.
2. Change toString method to use method created at 1.

For the sake of simplicity I would go for proposition 2.

I am happy to help on this one :)

**Comment by obarcelonap** [comment]
Just submitted a PR :)

**Comment by ffriedl89** [comment]
@obarcelonap Thanks for creating the issue. I agree that the second option is the preferred one. And cool that you already submitted the PR for it.
