### ISSUE TITLE
dt-tile inputs color & disabled cannot be set via `(input-name)="method()`

### ISSUE THREAD

**Issue by petrabrunner** [dynatrace-oss/barista#1159]
# Bug Report
 I am using the dt-tile component. 
And I tried setting the color-/disabled-option via a method call like so: 

.html:
`<dt-tile  (color)="getColor()" (disabled)="data()"> [...] </dt-tile>`

.ts: 
  ```
getColor(): string {
    return 'recovered';
  }

  data(): boolean {
   // return true;  // I used this line to test if the disabled-state would work like this.
    return false;
  }
```

regarding Expected vs Current behavior: 

currently the two options do not react when set like this. I am not sure if that is expected behavior or a "bug" (or if my code is hiding a mistake I cant find) - but I expected them to work like this. 

thx for your help! ~

### Used Versions:

- **node**: v12.14.0
- **npm**: 6.13.4
- **typescript**: 3.8.3
- **angular**: 9.1.6
- **@angular/cdk**: 9.2.1
- **@dynatrace/barista-components**: "^6.2.0"

screenshot:

![image](https://user-images.githubusercontent.com/45869415/84663605-b394b080-af1d-11ea-8796-af091398490a.png)

**Comment by tomheller** [comment]
Hi @petrabrunner !
As you are trying to set the input of the dtTile, you will need to use the downstream binding in the template with the bracket syntax `[]`.
Bindings with braces `()` are to bind to output event data. 

So this should work for you: 
```html
<dt-tile (color)="getColor()" (disabled)="data()"> [...] </dt-tile>
```

```ts
getColor(): string {
  return 'recovered';
}

data(): boolean {
 // return true;  // I used this line to test if the disabled-state would work like this.
  return false;
}
```

See the stackblitz example here: https://stackblitz.com/edit/github-egasbs?file=src%2Ftile%2Ftile-default-example%2Ftile-default-example.html

There is also a good overview about the binding syntax in angular templates here:
https://angular.io/guide/template-syntax#binding-syntax-an-overview

**Comment by petrabrunner** [comment]
@tomheller  yes that works! 😅 thx for the hint!
