### ISSUE TITLE
Table: Expression changed after checked error when reordering rows.

### ISSUE THREAD

**Issue by peter-affenzeller** [dynatrace-oss/barista#1166]
# Bug Report

## Expected Behavior

Reordering should not throw an error.

## Current Behavior

When reordering rows, an ExpressionChangedAfterItHasBeenCheckedError is thrown, which has not been reported before. So far, I've not been able to find the issue, already talked to @ffriedl89, who will help me figure this one out.

## Possible Solution

Must have something to do with where/when the new index of the rows is being set.

## Steps to Reproduce

Reorder table rows in dev-app/demos with angular v9.1.9 (error is not reported with v9.1.6)

1. 

### Used Versions:

- **node**: 
- **npm**: 
- **typescript**: ^3.8.3
- **angular**: ^9.1.9
- **@angular/cdk**: ^9.2.4
- **@dynatrace/barista-components**:

**Comment by lukasholzer** [comment]
Hi @peter-affenzeller Is this a regression or has it never worked?

**Comment by peter-affenzeller** [comment]
regression, did work with angular 9.1.6, but the error probably just hasn't been reported since the code didn't change, but after the update to angular 9.1.9 it is throwing the error.
