### ISSUE TITLE
[quick-filter] collapsable quick-filters OR a way to deal with filters with a huge set of values

### ISSUE THREAD

**Issue by petrabrunner** [dynatrace-oss/barista#1169]
# Feature Request

## Summary

We are using the quickfilter component and are quite happy with it for our general usecase. 
But we have a filter that has a lot of value-entries and makes it not very usable as a quickfilter.
(why we want this as a quickfilter see below) 
Now it would be awesome if there was a way to show a fixed size of filter values and "show more" if the user needs to see more. I dont really know if that is an ideal solution - I certainly wouldn't mind good suggestions in a different direction - but that is the one that I was thinking of. 

## Feature Description

- Problem 
We are using the quickfilter component for certain filters that are 
**1. used very often** -> that way the user needs just one click per filter  to filter the data instead of 3 clicks like they need in the filterfield 
(click into the filterfield; select the filterkey; select the filtervalue)
**2. very important for certain usecases** -> very important in the sense that the user sees on one glance all the values that are selectable.  
Now we have filters that have a huge set of filter-values (see screengrab for example; size of that value-list is ~500 entries)  This particular filter would be awesome to have as a quickfilter, because the filter itself is used very often. But the size of values prevents it from being useful as a quickfilter. 

- Solution
It would be awesome if there was some way to deal with this situation.

- one way could be using a "show more" -> where the user is given x (would need to be definable by the project using the component) entry values as a start and can click on "show more" which then presents with either the rest of the data or a given number of "more" entries. Similar to listing the contents of a huge directory on linux. (press Enter to show more - gives you more - pressing Enter again shows the next set of "more" - and so on) 
- another way could be to make the list collapsable 
- ... 

 I understand that my example is a rather extreme one (regarding the number of data entries) and maybe the quickfilter component is not the best solution for this entirely, but I thought I would put this in here so you know that there is demand for something like this. 

thx
 
## Attachments
![image](https://user-images.githubusercontent.com/45869415/84985542-3c3d6780-b13d-11ea-9ccd-880ed899db65.png)

**Comment by lukasholzer** [comment]
Hey @petrabrunner!
Thanks for creating a feature request for this! As you can see on the screenshots this is already designed and thought of. As the quick filter is an experimental component we decided to skip this for the very first version.

But we are happy to get a contribution for this! So if you want this feature and contribute it we could support you with it!


![image](https://user-images.githubusercontent.com/11156362/85004235-9fd48e80-b157-11ea-83da-1ba08eb7c657.png)

![image](https://user-images.githubusercontent.com/11156362/85004201-95b29000-b157-11ea-874e-03770aab952b.png)

**Comment by petrabrunner** [comment]
@lukasholzer perfect! looks good! 

if you are willing to support me in the process (as I am still quite a novice with angular I know I would need a bit of support/hints on how to write cleaner/better code) I'd certainly be willing to contribute. :) Probably not right at the moment, I'd have to schedule this, but Ill ping you when I know more.

**Comment by lukasholzer** [comment]
For sure I will explain it to you in detail and will guide you through we can do something like a pair programming session as well on that.

**Comment by hubert-grininger** [comment]
hi,
as I'm currently redoing the service list page in Angular I now have the same requirement than Petra (limit the list and show 'show more' which opens the filter in the filter-bar). Maybe we can talk about it in the next days. thanks, Hubert
