### ISSUE TITLE
Sunburst-chart: various improvements

### ISSUE THREAD

**Issue by subarroca** [dynatrace-oss/barista#1173]
# Feature Request

## Summary

Currently we have v1 of sunburst but after taking it to a real project there are some improvements to be done

## Feature Description

- Responsiveness. Currently the text scales and it's inconsistent with the rest of charts
- Better managing of overlay. Currently we have flickers in some cases
- Central label. Currently it can fall behind the slices and become unreadable

No API changes should take place

**Comment by tomheller** [comment]
Hey @subarroca! Thank you for sticking with the component and keep improving it. Very much appreciated 🙌 🥳
