### ISSUE TITLE
Event chart x-axis showing too many decimals

### ISSUE THREAD

**Issue by subarroca** [dynatrace-oss/barista#1190]
# Bug Report

## Expected Behavior

Format should be time friendly, like `1 min 20 s`, but if not possible, as a short term solution `1.33 min` should suffice

## Current Behavior

When decimals are long we get a huge amount, like `1.3333333333333333333` and it's really ugly and sometimes illegible

## Possible Solution

This is bound to Duration Formatter. Probably it would be good to limit the amount of decimals returned by the formatted

## Attachments

![image](https://user-images.githubusercontent.com/1245057/85302851-f91b2580-b4a9-11ea-8ead-85164d861b34.png)

**Comment by subarroca** [comment]
I can take this ticket but I need to know if the proposed solution of limiting the amount of decimals is the one to go

**Comment by tomheller** [comment]
I think with the duration formatter now being available, we should think about using this one to format the x-Axis. 

https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/formatters/src/duration/duration-formatter.ts

**Comment by subarroca** [comment]
We're already using this formatter, but the given result has too many decimals. My suggestion is adding a parameter to the formatter to specify the amount of decimals: if undefined then all, if defined the amount asked.
Does this work for you?

**Comment by tomheller** [comment]
> My suggestion is adding a parameter to the formatter to specify the amount of decimals: if undefined then all, if defined the amount asked.

If we add this, then it should only take affect if the `PRECISE` is passed. And we would need to make sure that we do not add unnecessary decimals, for example `1.00`. 

As a solution to the event-chart specific problem I also found that we are passing `PRECISE` as a parameter here, I'd argue that switching this one to default, would get rid of the decimal problem entirely. 
https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/event-chart/src/event-chart.ts#L842

**Comment by subarroca** [comment]
Switching it to default breaks  the purpose of axis values because you could get multiple `<1` values.

I'm gonna open a PR with my suggestion only applied to precise, which totally makes sense
