### ISSUE TITLE
Card: Info or help hover dialog

### ISSUE THREAD

**Issue by SaraDavilaMendez** [dynatrace-oss/barista#1198]
# Feature Request

## Summary

Add optional info or help icon link to the top right corner of the cards component. If the user clicks it a hover dialog will appear and the other components will be cover by a dark shadow. See images below.

## Feature Description

Currently, the cards component is used every where and it can contain almost every thing in it. Therefore providing a way to explain in detail how, where and what fore the card shows that information, would be helpful.  

Like the action buttons, it should be configurable if the help icon link is shown or not.
The content shown in the dialog should also be specified externally, but it should have a dialog header, body and action button(s).  See images below.

## Attachments
![image](https://user-images.githubusercontent.com/16416038/85411713-fa5f5780-b568-11ea-906a-ced376401e84.png)

![image](https://user-images.githubusercontent.com/16416038/85413975-cdf90a80-b56b-11ea-9443-96e9e7c2855a.png)

**Comment by tomheller** [comment]
Hi @SaraDavilaMendez!
Thank you for bringing this to our attention. This seems like a valid addition to the library. Would you be willing to also contribute this feature? We would obviously support and guide you through the contribution process and help with any questions you might have. 

@dynatrace-oss/ux-core Is this concept of the info bubble something that is limited to cards or is it more universally used?
This information would be very helpful to design an API for the feature and decide if it is it's own separate component or an addition to the card component.

**Comment by ffriedl89** [comment]
As stated on the internal communication, this pattern is not recommended anymore. Instead more description should be added to the card in addition to more documentation content. 

I couldn't find this pattern described on Barista anymore - so i guess we already removed that one in the past ;)

**Comment by tomheller** [comment]
>  this pattern is not recommended anymore
Oh sorry, I was not aware of this fact.

**Comment by tomheller** [comment]
@dynatrace-oss/ux-core Any update on this one?

**Comment by kathrin-aigner** [comment]
> @dynatrace-oss/ux-core Any update on this one?

This behaviour is not recommended anymore, since we had problems with that in the past. Instead of that please use a proper description within the card.
