### ISSUE TITLE
Switch as webcomponent

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1222]
# Feature Request

## Summary

We want to have a switch component for next as a webcomponent. 

## Feature Description

The switch should look like 
![image](https://user-images.githubusercontent.com/2905693/86444586-3afd6480-bd11-11ea-8b68-cbb44b8c8447.png)

Design details are available in the Figma file from UX. If you need a link - please reach out. 

Additional important information and tips could be found here - https://inclusive-components.design/toggle-button/
and here https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-1/checkbox-1.html

Scope of this issue is to create a first basic version that uses our design tokens including a first set of tests. Check out the checkbox for guidance.
If a11y is a big topic - please create followup issues to include these into the component. 

Animations can be omitted and added in a separate PR/issue. 

Check out https://www.fast.design/docs/components/switch as a reference as well.

**Comment by tomheller** [comment]
Api should be rather close to the one of the checkbox, omitting the indeterminate state.

## Properties
`checked`: Whether or not the switch is set to 'on'
`disabled`: Whether or not the switch is in it's disabled state

## Methods
`toggle`: Toggles the checked state on / off

## Events
`change`: Change event fired when the switch changes state (only when triggered by user interaction).
