### ISSUE TITLE
Empty Table should hide sort indicators out of the box

### ISSUE THREAD

**Issue by christian-fischer** [dynatrace-oss/barista#1227]
# Feature Request

## Summary

We should hide the sort indicators if the table is empty.

## Feature Description

If a table is empty - i.e. when the empty state is shown - the table headers and their sort indicators are still visible.
Sorting an empty table feels kind of unnecessary. 

Thus it would be really great if the table component could hide the sort indicators out of the box for empty state.
So far, every user of the table has to add something similar to `[dtSortDisabled]="_dataSource?.data?.length == 0"`

**Comment by tomheller** [comment]
This is a good addition to the table and sorting behavior. It could be a bit tricky to get this into the rather extravagant change-detection of the table. 
But it is definitely worth a shot. Would you be willing to contribute this feature to barista as well?

**Comment by christian-fischer** [comment]
Willing yes, but I fear time availability is another matter, at least in the short term I most likely won't get around to it. 
As you mention the rather extravagant change-detection and since I haven't contributed to the table before, I might have some need of a bit of guidance then.

**Comment by tomheller** [comment]
Of course we would offer guidance to anyone willing to contribute to the project. 

> Willing yes, but I fear time availability is another matter

Thank you for being honest about this, we will keep this issue open for contributors and you can reach out if you want to tackle it in the future.
