### ISSUE TITLE
Sunburst chart opening additional children

### ISSUE THREAD

**Issue by bradking1329** [dynatrace-oss/barista#1245]
# Bug Report
## Expected Behavior
When clicking on a certain child, only the children of that child should expand.
## Current Behavior
Clicking the 11th or 12th child in NORAM causes multiple children to expand, even if they do not correspond to the parent clicked.
## Possible Solution
Haven't looked at the source code, but seems like it may due to the raw number of entries in our chart, since it consistently happens to the 11th or 12th child of our example
## Steps to Reproduce

Reproducible at: https://stackblitz.com/edit/github-okclvb
1. Click on NORAM child (purple).
2. Click the 11th or 12th smallest child.
## Context (Environment)
We've been working on creating reporting for an internal app — we want to use the Sunburst Chart to show the busiest hour within a 24 hour period (almost like a clock), along with the user-breakdown underneath the hour.
### Used Versions:
- **node**: 12.15.0
- **npm**: 6.14.1
- **typescript**: 3.8.3
- **angular**: 9.1.11
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: 7.1.0
## Attachments

![image](https://user-images.githubusercontent.com/34667107/86815089-4245aa80-c050-11ea-8cd6-d9c767231069.png)

**Comment by tomheller** [comment]
@bradking1329 Thank you for reporting this. 
@subarroca Would you mind looking into this one?

**Comment by subarroca** [comment]
No problem. Assign it to me and I'll deal with it as soon as possible

**Comment by subarroca** [comment]
@tomheller this will be finally taken care by @PedroMosquera . Thanks!
