### ISSUE TITLE
[Filter field] Range filter breaks after data refresh

### ISSUE THREAD

**Issue by ap-dyna** [dynatrace-oss/barista#1256]
# Bug Report

## Expected Behavior

After async data update, the range filter widget does not break. It e.g disappears like the autocomplete filter.

## Current Behavior

[Background: Some of the Dynatrace views are required to asynchronously update their data in tables. This requires filters to update as the autocomplete filters hold the values.]

Currently, when updating filter values, the widget goes as in the screencast https://www.screencast.com/t/hDZLBeLG. 
(The screencast is the Barista stackblitz range filter example with a change to async).

## Steps to Reproduce
https://stackblitz.com/edit/github-nfqa9b-w2adfv

1. Make the filter loading data in an interval.
2. Choose a range filter and wait for the change
3. The widget breaks

**Comment by tomheller** [comment]
Hey @ap-dyna!

It seems to me that it does not make a lot of sense to update the data, while the user is mid filtering. You are potentially loading data, that would be filtered away after the user is finished with the filter. 
Setting the datasource of the filterfield, while the user is in flight of creating a filter is really hard to for us to handle. 
The filterfield gives you an event, when the filters have changed. It should be possible to fetch your data when the filters have changed. 
The only thing that I think is feasible to achieve is that the filter-field will emit an `filteringInFlight` event or something similar, that a consumer can check for and hence not update the filter-datasource. 

--- 

Additionally, what would you expect to happen in the following scenarios:
1. The new dataset that gets loaded does not contain the filter definition the user is currently editing? In your case the range one? Does the filter field reset completely?
2. The new dataset does not contain any of the filters previously set by the user.
Should they vanish or do they stay? 
3. What would happen if the filter-definition changes and the filter the user is currently on can be recreated, but now it is no longer a range but a free text field.

**Comment by ap-dyna** [comment]
Hey @tomheller, thanks for the resp.:)

Having an _filteringInFlight_ event(s) that would notify when a user started and stopped focus on the widget is a good option. I think it will give a solution to omit the range widget getting broken.

As for the questions:
1. & 2. & 3. Having the _filteringInFlight_ event, a conscious filter client app would set appropriate [filters] and [dataSource] values after the async request and choose their own policy.
(Some issues I think may already happen when a non-conscious client app sets non consistent [filters] and [dataSource] data. So what to do in all those cases? Maybe the UXs would know?)

**Comment by tomheller** [comment]
Hey @ap-dyna!
Okay, I guess we can look into an event or property to indicate if the user is interacting with the filter field at the moment. 

Could you please specify what you mean by conscious vs. non-conscious client app. I'm afraid I'm not quite familiar with this terminology.

**Comment by ap-dyna** [comment]
Nice.


> Could you please specify what you mean by conscious vs. non-conscious client app. I'm afraid I'm not quite familiar with this terminology.

Sure. "a non-conscious client app sets non consistent [filters] and [dataSource] data" means eg.:

Let's say a user made a typo and his [filters] is not a subset of [dataSource]. In the barista exmple example:
https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleFilterFieldProgrammaticFilters/
 it could be:
// TYPO Filter AUT -> Los Angeles
[this.DATA.autocomplete[0], **this.DATA.autocomplete[1]** .autocomplete![1]],

As far as I see, currently the filter field just shows 'Los Angeles', despite that AUT does not contain that option.
Which is similar to one of the cases you asked about:
> what would you expect to happen in the following scenarios: The new dataset that gets loaded does not contain the filter definition the user is currently editing?

**Comment by tomheller** [comment]
> it could be:
// TYPO Filter AUT -> Los Angeles
[this.DATA.autocomplete[0], this.DATA.autocomplete[1] .autocomplete![1]],

Yes, this is correct. If the consumer (developer) provides the filter-field with inconsistent data, the filter field accepts these values. Especially because we need to deal with filters being settable, without the datasource being fully loaded. 

Pardon if I'm not quite following, but what do typos / inconsistent filter settings have to do with the range breaking the filter?

**Comment by ap-dyna** [comment]
This is my understanding of the flow: 

@tomheller: 'Additionally, what would you expect to happen in the following scenarios: The new dataset that gets loaded does not contain the filter definition the user is currently editing? In your case the range one? Does the filter field reset completely?'
@ap-dyna: 'Having the filteringInFlight event, a conscious filter client app would set appropriate [filters] and [dataSource] values after the async request and choose their own policy. (Some issues I think may already happen when a non-conscious client app sets non consistent [filters] and [dataSource] data.)'

In the _// TYPO Filter AUT -> Los Angeles_ case the filter field doesn't reset completely, so for me the range could behave the same.

**Comment by tomheller** [comment]
@ap-dyna Now I think I understand. If a range is currently open, and a new data is set to the filter field data source that does no longer contain the currently open range, the range should close and the current filter reset?

**Comment by tomheller** [comment]
Is considered fixed by #1317 and the follow up of #1321
