### ISSUE TITLE
[Quick Filter] Distinct radio groups affect eachother

### ISSUE THREAD

**Issue by areknow** [dynatrace-oss/barista#1270]
# Bug Report

When using a basic QuickFilter with two config options using the "distinct" option, a bug is noticed between the two radio groups. Clicking a radio in one group will affect the selection of radios in the other.

https://github-mpgcfd.stackblitz.io/
https://stackblitz.com/edit/github-mpgcfd?file=src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts

**Comment by tomheller** [comment]
Hi @areknow! 
Thank you for catching this! 
I can confirm that this is an issue when setting the filters via the quickfilter. The connection from the filter-field to the quickfilter seem to work (when setting the filters in the filter-field, they are reflected correctly in the quickfilter).

**Comment by areknow** [comment]
Just tested out the fix in 7.4.0 and I can confirm that it is fixed and working correctly. Thank you very much for the super fast resolution!
