### ISSUE TITLE
[Filter field]: Refactor unit tests into multiple files

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#1296]
The filter field spec file is getting very large and at this point, it is very hard to grasp which setup is used for which testcase within the file. 

It would be great if we could split the tests into multiple files to make them more readable, as discussed in https://github.com/dynatrace-oss/barista/pull/1276/files#r453449163

**Comment by ffriedl89** [comment]
Hold off until #1276 is merged to not introduce merge conflicts

**Comment by ffriedl89** [comment]
Currently blocked by #1276

**Comment by lukasholzer** [comment]
Moved to APM-266062
