### ISSUE TITLE
Filter field: required validation not being for the first time

### ISSUE THREAD

**Issue by sebapawlak** [dynatrace-oss/barista#1299]
# Bug Report
For the filter field component `Validators.required` validation is not being triggered when a filter is selected and no value for the filter is provided. Likely caused by fix for https://github.com/dynatrace-oss/barista/issues/1180

When some value is typed and then deleted then it gets properly validated and a validation error is shown.

## Expected Behavior
When there is a validation that requires value and after the selection of the filter it gets submitted there should be a validation error.

## Current Behavior
There is no validation error shown if the page is submitted right after a filter with `Validators.required` validation is selected.

## Steps to Reproduce
Data source to reproduce the issue:
```
{
    autocomplete: [
      {
        name: 'nonEmptyFreeText',
        suggestions: [],
        validators: [
            {validatorFn: (control: FormControl) => Validators.required(control), error: 'Content cannot be empty.'},
          ],
      },
    ],
}
```

1. Select `nonEmptyFreeText` filter.
2. Hit return key.
3. Validation error should be shown at this point.

### Used Versions:
Issue does not exist in Barista 7.2.0.
Issue identified in Bartista 7.4.0 but 7.3.0 was not checked.

**Comment by tomheller** [comment]
@sebapawlak Thank you for reporting this. I can confirm that this is an issue caused by the fix contained in #1180.
