### ISSUE TITLE
Display web component READMEs in next app

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1315]
# Feature Request

## Summary

Similar to what we are doing with the readmes from the angular-components we want to display the readme files from the fluid-elements subcomponents inside the next app. 

## Feature Description

Each README file for a web component should have a page inside the next app. 

For the fluid-button - I'd like to have a page e.g. /components/button containing the content of the readme.

**Comment by lukasholzer** [comment]
We will close this issue as web components are not the way we want to create components in the future this is related to a shift of priorities in the team.
