### ISSUE TITLE
Bazel: Investigate remote cache hits.

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1318]
I think we might have some problems with the remote cache hits on the CI. The test runs should be cached from the ci. https://github.com/dynatrace-oss/barista/pull/1308#issuecomment-660806288

![image](https://user-images.githubusercontent.com/11156362/87916299-8afb5b80-ca73-11ea-88a4-3b648b1aec9f.png)

button, core and icon should be cached as they were not touched and should be already built by the ci.

**Comment by furtnerl** [comment]
After quite some research it drills down to being a rather simple problem. 
The service user we use to push cache objects had rights to read and write object to our caching backend but not to alter objects. 
After equipping the user with sufficient rights I was able to achieve 100% cache hits locally and on my little private CI that is based on Kubernetes Pods as executors. Will check the latest Circle CI builds now

**Comment by tomheller** [comment]
@furtnerl After the sync today, this issue seems to be fixed, right?
