### ISSUE TITLE
[Filter field]: Add information about interaction level on the filter field.

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#1321]
# Feature Request

## Summary

Add an `@Output` and a property to the filter field that indicates whether the user is currently using the filter field. This will help consumers to determine when it is safe to update filter-definitions (datasource) without crashing the user flow of the user. 

The output can be useful to react to changes in the interaction-behaviour, whereas the property can be used for onDemand checks if it is now safe to update the datasource.

This state will probably need to determine the following things:
- Is the filter field focused
- is an autocomplete / range currently open

## Proposal

Add the following to the filter field. 
I'm happy to accept feedback, especially on the naming as I'm not sure how well this naming fits. 

`@Output() inFlightChange: EventEmitter<FilterFieldInFlightChange<boolean>>`
Fires when the user starts interacting with the filter field or stops interacting with it.

`inFlight: boolean`
Determines if the user is currently interacting with the filter field or not. 

Please add your considerations, especially pinging @ffriedl89 @thomaspink @ap-dyna

**Comment by ap-dyna** [comment]
Hi @tomheller,
This description looks good and I see the @Output+property combination as useful.
(As for the naming, I will stick to your Barista conventions).

**Comment by ffriedl89** [comment]
I can see both the ouput and the boolean property being useful. I am also not quite convinced about the naming tbh. 
Maybe 
`@Output() userInteractionChange` for the output
`userInteracting` or `isUserInteracting` for the boolean flag

**Comment by tomheller** [comment]
I think it's a good point to go with
`@Output() userInteractionChange` for the output.
`isUserInteracting` for the boolean flag.

**Comment by ffriedl89** [comment]
Moved to internal issue tracking.
