### ISSUE TITLE
Bazel: Make result output visible on CI.

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#1340]
# Bug Report

When a bazel run on the CI fails (right now primarily stylelint tasks), there is no way to see the output on Circle CI.
I have to rerun the whole thing locally again (given one knows how to) and know where the output logs are, to figure out why the stylelint fails. 

## Expected Behavior

CircleCI gives me a way to view the linting errors, so one does not have to duplicate the effort of running the checks again. 

## Current Behavior

Circle CI output shows a process exit error, which is not very helpful.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/6338434/88023159-d889ce00-cb30-11ea-99fc-1fa72c010847.png">

**Comment by lukasholzer** [comment]
@tomheller thank you very much for opening the issue :)
