### ISSUE TITLE
Container-breakpoint-observer: Exception in MS Edge 45

### ISSUE THREAD

**Issue by dominikmessner** [dynatrace-oss/barista#1346]
# Bug Report

## Expected Behavior

Edge should react to queries.

## Current Behavior

Exception:
`The provided query "(min-width: 460px)" is not valid. Make sure to your query is wrapped in brackets. Only min and max queries are supported`

## Possible Solution

It works in Edge Chromium, which was officially rolled out to all users in June AFAIK, so I think it would be sufficient to ignore these queries in Edge, so it doesn't throw an exception anymore.

## Steps to Reproduce

https://barista.dynatrace.com/components/container-breakpoint-observer

**Comment by thomaspink** [comment]
Issue: 
Edge (Non Chromium) returns a different value for the following code as the other browser:
```ts
window.matchMedia('(min-width: 460px)').media
```

Needs to be fixed here:
https://github.com/dynatrace-oss/barista/blob/3a23c27f9c8b016f0fb55ccd7eaea4aa51b9fd37/libs/barista-components/container-breakpoint-observer/src/query.ts#L59

**Comment by lukasholzer** [comment]
@dominikmessner do you want to contribute the fix?

**Comment by samuelfahrngruber** [comment]
The fix from the above pull request will fix the error in the query parsing logic.

However, after verifying the change on MS Edge locally, the `container-breakdown-observer` does still not work. There is no error in the console anymore, but the breakpoint won't trigger either. Firefox and Chrome work fine.

I suspect there is another problem occurring in MS Edge when actually detecting the breakpoint.
