### ISSUE TITLE
Design system outlet with SSG and storybook examples

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#1349]
## Idea

Investigate if it would be feasible to replace the design-system outlet with a static site generator (i.e. 11ty) and examples built with storybook and included as iframes. 

## Things we need to discuss

* Is this a good idea at all, do we have any blockers that would prevent us from doing this?
  - The mockup for some changes to the design system outlet is in a very early stage, so it is hard to say if there is anything we would miss?
  - Things like the decisiongraph could be a standalone app, that eleventy publishes with the rest of the code. If we need them at all.
* ~How would a CSS pipeline look like for this one?~ Solved by applying a bazel scss pipeline
* ~How would a client side JS pipeline look like?~ A simple one is in place with bazel, but we will need some bundling in addition to the tsc compile.
* ~Do we need (want) typescript for the client side javascript?~ We want typescript, simple bazel pipeline is set up.
* ~Do we need typescript for the eleventy config?~ No
* ~Do we need bazel for this?~ Yes, we do for the styles and scripts pipeline
* How can we integrate storybook and stories?
  - How can we provide the theme switch for stories within iframes?
  - Static output of storybook in iframes can be used to display interactive demos.
  - How can we extract demo code to show with the example?
  - Do we want to write stories in mdx or js/ts.
* How can we configure / build internal and external versions?
  - multiple .eleventy.js config files that configure either internal or external?

Further questions and tasks are listed for now are maintained in the initial pull request #1374 

## Things it would make easier

Right now data fetching from our cms and aggregation of data (barista-tools) is getting more and more convoluted. A SSG like 11ty seems to be the perfect fit to get data from a headless cms, enrich it with snippets, stories, or api documentation. 
This way we could prevent building and running the barista-tools library, building the design system application, and running SSR generation. 

Any input is appreciated, especially pinging @ffriedl89 @lukasholzer @rowa-audil @bardosmisi @thomaspink

**Comment by lukasholzer** [comment]
> - Do we need bazel for this?
Definetly "Yes" as it is our build tool and will replace the angular cli completely in the future. From the perspective of fast incremental build we would only gain advantages from bazel as it could handle the typescript, scss and javascript compilation.  11y should only be orchestrated in the bazel pipeline to generate the pages.

**Comment by tomheller** [comment]
@lukasholzer We will definitely need your help on the bazel things then, I have no idea where to start with this.

**Comment by lukasholzer** [comment]
@tomheller for sure let's sync up today then I can elaborate you my point of view a little bit better. :)
