### ISSUE TITLE
[Table] Using dtExpandableRowContent and dtSort together creates rows with spacing

### ISSUE THREAD

**Issue by areknow** [dynatrace-oss/barista#1353]
# Bug Report

Hi team, I noticed today that since upgrading to v7.4.0, a new issue is present with the DtTable that uses DtSort along with DtExpandableRowContent.

<img width="1516" alt="Screen Shot 2020-07-22 at 5 02 35 PM" src="https://user-images.githubusercontent.com/6361609/88228639-75399200-cc3d-11ea-8fe0-73fe108c579e.png">

For some reason I am NOT able to reproduce the bug in stackblitz. Only by creating a fresh Angular project was I able to make a reproduction.

## Expected Behavior

The beautiful table should remain beautiful, no extra spacing between each row after clicking on a sort header.

## Current Behavior

When using the sort functionality on a DtTable that also has expandable rows, some extra spacing is introduced below each row AFTER clicking on the sort header.

## Steps to Reproduce

1. clone: https://github.com/areknow/barista-table-expander-sort-bug.git
2. `npm i`
3. `npm run start`
4. click on a table column header to activate sorting
5. observe that each row now has additional spacing below it that was not there before

### Used Versions:

- **angular**: 9
- **@angular/cdk**: ^9.1.0
- **@dynatrace/barista-components**: 7.4.0

**Comment by lukasholzer** [comment]
Thank you for reporting this issue! Do you want to contribute the fix to the library @areknow?

**Comment by tomheller** [comment]
@areknow I found the root cause for that problem, which seems to be tied to the internal rendering scheme of the table and the angular animation used to set the expand / collapse states. 
I'm currently trying to figure out how we can circumvent this issue.
