### ISSUE TITLE
[Quick Filter] Radio buttons invisible after upgrade to 7.5.0

### ISSUE THREAD

**Issue by areknow** [dynatrace-oss/barista#1383]
# Bug Report

Hi team, 
I noticed that after the 7.5.0 upgrade, the radio buttons in the quick filter are no longer visible. They are however still selectable. I think this is due to the recent change to custom properties styling, but I may be incorrect.

<img width="492" alt="Screen Shot 2020-07-27 at 8 35 07 PM" src="https://user-images.githubusercontent.com/6361609/88605687-ab658000-d048-11ea-9925-5ce541a8c512.png">

Thank you!

## Expected Behavior

The radio buttons should still be visible.

## Current Behavior

The radio buttons are not visible.

## Steps to Reproduce

https://stackblitz.com/edit/github-dyfbut

### Used Versions:

- **@dynatrace/barista-components**: 7.5.0

**Comment by tomheller** [comment]
Thanks @areknow! I'll check immediately. We were planning on releasing 7.6 soon anyways, as we missed a feature in the release yesterday. I'll see if we can get this done.

**Comment by areknow** [comment]
> Thanks @areknow! I'll check immediately. We were planning on releasing 7.6 soon anyways, as we missed a feature in the release yesterday. I'll see if we can get this done. 

Thanks @tomheller!

**Comment by tomheller** [comment]
@areknow As a workaround you can make sure that there is a theme set in your app, which will mitigate the issue.

**Comment by areknow** [comment]
@tomheller can confirm that setting a theme at the app.component.html level does work 😄 
Thanks
