### ISSUE TITLE
dtDuration formatter cannot handle values < 1 ms in the 'DEFAULT'-mode correctly

### ISSUE THREAD

**Issue by Laubi** [dynatrace-oss/barista#1395]
# Bug Report

## Expected Behavior

The dtDurationFormatter formats values smaller than 1 ms in the DEFAULT-mode correctly.

## Current Behavior

The dtDuration formatter has wrong behavior with the input- and output-units `DtTimeUnit.NANOSECOND` and `DtTimeUnit.MICROSECOND` in the 'DEFAULT'-Mode.  

See the Stackblitz example.

## Steps to Reproduce

[Stackblitz](https://stackblitz.com/edit/github-dqdbji-73uafj?file=src%2Fstyles.scss)

Gist with additional test cases which currently fail (drop-in replacement for the duration.spec.ts):  https://gist.github.com/Laubi/4f15023b9229460e2ac905327ac875b3

## Context (Environment)

I try to remove my self written component with this generic one. Although there might be further improvements needed. But this bugfix is the first step.

### Used Versions:

- **node**: 14.6.0
- **npm**: 6.14.6
- **typescript**: 3.8.3
- **angular**: 9.1
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: trunk (latest release 7.5)

**Comment by ffriedl89** [comment]
@Laubi Thx for creating the reproduction and the gist! 💯 . We'll have a look.
