### ISSUE TITLE
Button group as a webcomponent

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1399]
# Feature Request

## Summary

Create the button group component as a webcomponent. 

## Feature Description

Keep in mind that the button group + items are basically a radio-group + radios. Use the correct roles for the components to be accessible. 

- [x] Create component boilerplate
- [x] Add properties for button-group-items (value, disabled, name, checked)
- [x] Add properties for button-group (value, disabled, name) 
- [x] Style using css proxy custom properties similar to the other web components
- [x] Tests

Think about sharable code between tabs and button-groups - the selection and focus handling using tab and arrow keys is the same. 

![image](https://user-images.githubusercontent.com/2905693/88786937-6d28a780-d193-11ea-95fa-fbaf064ae7e2.png)

**Comment by rowa-audil** [comment]
# API Proposal for the __Button-group webcomponent__

## Overview

The buttongroup provides wrapper grouping options together similar to the radio group or tab group component. Selecting one option responds with a value provided by the user. 

The button group will handle the keyboard support.

## API
### button-group-item
#### Properties:
`id:` string // Identification property
`value:` string // Value property
`name:` string // Name property
`checked:` Boolean // Whether the item is active or not
`disabled:` Boolean // Whether the item is disabled

#### Events:
`checkedChange:` Event: (value: string, bubbles: true)

### button-group

#### Property
`id:` string // Identification property
`value:` string // Value property
`name:` string // Name property
`disabled:` Boolean // Whether the group is active or not

#### events
`checkedChange:` Event: (value: string, bubbles: true)

### HTML prototype

```html
<fluid-button-group>
  <fluid-button-group-item id="btn1">
    Button 1
  </fluid-button-group-item id="btn2">
  <fluid-button-group-item>
    Button 2
  </fluid-button-group-item id="btn3">
  <fluid-button-group-item>
    Button 3
  </fluid-button-group-item>
</fluid-button-group>
```

**Comment by rowa-audil** [comment]
By investing the native behavior of a radio button and grouping them I came to a conclusion concerning automatically deselecting when setting the same name attribute to all radio buttons.

The actual `input type=radio` will be rendered in the shadow dom resulting in every button-group-items input having to relation or way of know each other.

The solution to this is pretty straight forward to let the button-group web component (wrapper) handle the automatic deselect if the user chooses to.

**Comment by rowa-audil** [comment]
Bold on hover and active - Without content shift
Using `-webkit-text-stroke: 1px black` on hover seems to do the trick.
It would look like this:

![Uploading Screenshot 2020-08-14 at 07.00.31.png…]()

The first button group is the active-, the second the hovered state, and the last is the default.

**Comment by rowa-audil** [comment]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/57528898/90237488-a19f9300-de24-11ea-849d-7f9a0d8a869b.png">
