### ISSUE TITLE
Research: Generate styleguide / styles for figma based on design tokens 

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1402]
# Feature Request

## Summary
We want to have a styleguide library published containing the local styles based on the design tokens. 

## Feature Description

The way that figma handles styleguides is that it is like any other figma file with local styles and once published others can import this as a library and use the styles defined in their work. 

Investigate how to access the figma API to create & update a file. 
Once we have that figure out the structure we need to define local styles for colors. 

Ideas on how to solve this: 
* ~~Everytime we merge something on master - run a github action to generate / update the figma styleguide with the latest values of the tokens.~~

Goal of this issue is to call the figma API and generate the styleguide based on the values. 
Nice to have: Already have the github action trigger that on master builds.

---

UPDATE: This doesn't work since the Figma API only supports reading files.

> The Figma API supports read access and interactions with Figma files. This gives you the ability to view and extract any objects or layers, and their properties, so you can render them as images outside of Figma. You can then present your designs, connect them to other applications, or use them to expand on your vision. Future versions of the API will unlock even greater functionality around Files.

We'll pull the data from GitHub or get the sources from Webpack in a Figma plugin instead (all the data we need is built in JSON files). In the first step, we'll add a context menu item to pull the latest data. An auto sync with a push model doesn't seem possible with Figma's current API.

* We need to save the color palettes of all themes in the document's color styles. A theme switch should change the color references on the individual components instead of affecting the color styles.
* On theme switch, the colors should only be changed from the current selection downwards.
* An automatic migration for the current document containing the library might be interesting.
* We don't know how to handle spacings well, so we'll ignore them for now.
* Assign an ugly gradient to design tokens that were deleted to make it clear that those need to be changed

**Comment by SkaillZ** [comment]
Follow-up issue: https://github.com/dynatrace-oss/barista/issues/1495
