### ISSUE TITLE
[Barista icons]: Include metadata in published package

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#1403]
To prepare for #1404 and #1405, we should discuss if it is feasible to include the .json files that are holding the metadata of the barista-icons with the released version. 

The information stored in there is already public on the barista outlet pages and we could simplify the build process in the long run, to not rely onto a checked out version of the barista-icons repository.

If more information is needed about this, please reach out.

**Comment by ffriedl89** [comment]
I definitely see this as a big improvement - this switch to have a installed version but check out master only to generate the pages containing the metadata is odd.
I don't see a reason why this metadata could not be included in the bundle. 
So I am 💯  for go!

**Comment by tomheller** [comment]
Solved in deployment strategies for the icons.
