### ISSUE TITLE
[Barista tools]: Replace the generation of icon pages source

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#1404]
Currently we rely on the barista-icons sources being checked out to generate the icon pages.
https://github.com/dynatrace-oss/barista/blob/master/libs/tools/barista/src/builder/icons.ts

To simplify this and unify the sourcing of files between barista.dynatrace.com/resources/icons and barista.dynatrace.com/components/icon we should move the generation of the files to source the installed data from @dynatrace/barista-icons npm package.

**Comment by lukasholzer** [comment]
As commented here this is currently not possible: https://github.com/dynatrace-oss/barista/pull/1448#issuecomment-669196682

**Comment by tomheller** [comment]
As commented here, this is possible: https://github.com/dynatrace-oss/barista/pull/1448#issuecomment-669205412
