### ISSUE TITLE
[publishing]: Simplify Barista design outlet publishing

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#1405]
Currently we prepare the build-agent, which builds and publishes the barista design outlet via a couple of steps in docker and jenkins. 

**1. The workspace base is built on circle-ci**
https://github.com/dynatrace-oss/barista/blob/master/.deployment/workspace-base.Dockerfile

**2. The barista jenkins agent is built**
https://github.com/dynatrace-oss/barista/tree/master/.deployment/k8s-barista-builder

**3. Barista publish runs based on the agent in step 2**
https://github.com/dynatrace-oss/barista/tree/master/.deployment/barista
Step 2 installs the internal versions via an npm proxy, but step 3 has a check in there, that will reinstall the public version, if there is any mismatch in the package-lock.json 

https://github.com/dynatrace-oss/barista/blob/d21e16d2421df049396ef1d67d20970260d91e86/.deployment/barista/Jenkinsfile#L87-L93

If that check executes the npm ci, it will install the public version, no matter if the npmrc file points to the npm mirror or not.

**Comment by lukasholzer** [comment]
The workspace-base image with the built-in node_modules is used for the preview builds of barista with the public version (without cms) this is done inside GitHub actions and is therefore pretty fast according to the already built-in node_modules.

The Jenkins image has to base on a specific image that is in the internal registry and this is not open source - to have the necessary packages for being a Jenkins pod that can be provisioned by K8.

As this image can only be built in the internal network we already install the internal version of the icons and the fonts. (This means on the most runs where only content changed we don't have to install node_modules and fonts and icons and we can start right away building the static pages)

On the barista publish we check which one to use the public ones that are already built-in in the bottom layer as it is used by the branch preview as well and if it is an internal build it will take the icons and fonts that are in the internal layer.

(only if the shasum of the package.json has changed we install the needed icons and packages)

So to keep all those requirements and have fast builds on the internal and external network this was necessary to set up. Nevertheless, If you have a better approach feel free to propose!

**Comment by tomheller** [comment]
> As this image can only be built in the internal network we already install the internal version of the icons and the fonts. (This means on the most runs where only content changed we don't have to install node_modules and fonts and icons and we can start right away building the static pages)

The problem with this is this particular check in the barista deployment jenkins file.
https://github.com/dynatrace-oss/barista/blob/a1d28385b74f41762e3b101c0395c5d994e3edae/.deployment/barista/Jenkinsfile#L87-L93

If the package-lock.json has changed, we perform an `npm ci` again, which in the last failing case installed all dependencies from the public version again. the package-lock.json was still sourced from the workspace-base, which included the resolved paths to the public npm registry.

Right now, our plan would be to split the builders into two different jenkins agents. One that holds the public installed packages and one that holds the internal ones. This would prevent us from needing to run `npm ci` again.
We would still have fast builds, but we would not need to fiddle around with all these internal / public deployment checks within one jenkins file, but split them into two pipelines. @lukasholzer would that work on your opinion?

**Comment by lukasholzer** [comment]
@tomheller yea sounds great – good approach! 👏

**Comment by tomheller** [comment]
> Nevertheless the need of npm install
Yes, but we can leave the `npmrc` file in the internal agent, so we do not install the public version by mistake. Right now we delete it after the initial install of the icons and fonts again, which caused the original problem in the first place.

**Comment by lukasholzer** [comment]
Currently blocked by: #1469
