### ISSUE TITLE
DtCombobox: Add solid unit test coverage 

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1406]
# Quality issue

## Summary

We need to have solid unit test coverage for the combobox. This also helps us develop a new API against a set of unit tests. 

## Description

Add unit tests for different areas: 
* Mouse interaction
* Keyboard interaction
* Programmatic interaction
* a11y tests to check for role / labels to be correct

**Comment by heartdisease** [comment]
Dropped in favor of #1388
