### ISSUE TITLE
DtCombobox: Rework API

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1407]
# Feature Request

## Summary

The current API for the combobox is really not that great. A lot of heavy lifting is put on the consumer - we should change that so that the filtering is done internally by using a provided function.

## Feature Description

The biggest problem right now is that the consumer needs to handle filtering of the options. E.g. the value of the combobox is set to `app-` but the consumer provides options that don't consider this value already - we display all options that we get. 
Once the filter changes e.g. by the user typing in the input field we emit an event and expect the consumer to handle the filtering again and provide a new set of options. 
And once the value changes by selecting an option we also expect the consumer to filter the options again and provide it to the combobox. 

I'd propose an API where we get "all" available options and do the filtering internally at the correct times. This still should allow consumers to provide a new set of options after a filter changes. (for async server filtering). 
In that case the internal filtering would return all options that were passed since the filtering was already done on the server beforehand. 

Propose a new API for discussion here.

**Comment by lukasholzer** [comment]
@heartdisease can we close this issue in favour of we are doing it with web components?

**Comment by heartdisease** [comment]
Dropped in favor of #1388
