### ISSUE TITLE
Upgrade to Angular 10 & Nx 10 & Typescript 3.9

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1411]
# Feature Request

## Summary

We want to upgrade to the Angular 10 as well as using the new Typescript version 3.9. 
Nx 10 was released as well.

## Feature Description

Since Nx 10 depends on Angular 10 we need to switch all at once. 

Findings so far during the update process:
* Tslib was updated with the angular upgrade to 2.0.0
* Tslint 5.x has a dependency to tslib ^1.10 so I updated to tslint 6.
* Codelyzer also has a dependency to tslib therefore i upgraded to codelyzer 6.0.0. This caused some typings to fail the build due to the dependency to Angular 9 of codelyzer@6.0.0. 
* Jest mocks from barrel files don't work anymore - Typescript throws an error: 
  ```
  TypeError during Jest's spyOn: Cannot set property **** of #<Object> which has only a getter
  ```
  My solution right now is to mock the exact module and not the barrel file which works out without issues.
* The CDK table adjusted the template and added a noDataRowOutlet that needs to be in our template as well. Otherwise the destruction of the table throws an Exception.

TBC

**Comment by lukasholzer** [comment]
Released version [8.0.0-rc.0](https://github.com/dynatrace-oss/barista/releases/tag/8.0.0-rc.0) and run `ng update @dynatrace/barista-components` on the cluster (feature/sb/APM-245631-angular-10-update)

Fails with following error message.

![image](https://user-images.githubusercontent.com/11156362/89779589-09e23200-db10-11ea-85ce-1d6975a40998.png)
