### ISSUE TITLE
[Filter field] Add optional indicator when filter was added programmatically

### ISSUE THREAD

**Issue by dominikmessner** [dynatrace-oss/barista#1415]
# Feature Request

## Summary

When a filter was added from a different component, e.g. a button, the filter field should be highlighted somehow, so the user realizes what happened. See attachments for an example.

### Problem
We have a tile that can set filters to the filter field. The end user however might have difficulties noticing the change in the filter field, because he might look somewhere else. Therefore, we decided with UX to highlight the filter field for a moment. As other users of the filter field might run into the same issue, and to improve consistency, we would like to get this into the Barista component.

### My current solution
I have a smart filter component, and a filter state service. The filter state service can be injected into other components and provides an API to set a filter to a value. Whenever this method is called, the filter component is getting notified and plays the animation. 
I have rebuilt a simplified version on [Stackblitz](https://stackblitz.com/edit/github-petmev?file=src%2Ffilter-field%2Ffilter-field-distinct-example%2Ffilter-field-distinct-example.ts).

### Transferring this to Barista
The Barista filter field exposes the input field `filter`, I guess we could play the animation whenever this input is set. There will however be use-cases where the animation is unnecessary, so we need some additional parameter to define if the animation should be visible.
Not sure how a good API would look like without breaking the current implementation.

## Attachments

![Peek 2020-08-03 13-27](https://user-images.githubusercontent.com/49026443/89178184-5b794280-d58d-11ea-9e9f-fee7665993b2.gif)

https://stackblitz.com/edit/github-petmev?file=src%2Ffilter-field%2Ffilter-field-distinct-example%2Ffilter-field-distinct-example.ts

**Comment by tomheller** [comment]
Hi @dominikmessner!
This seems like a good idea, to notify users of a change that happened programmatically, but I do want to involve @dynatrace-oss/ux-core in this discussion, as this seems like something they should be part of.

**Comment by lukasholzer** [comment]
Not on our roadmap
