### ISSUE TITLE
[Combobox] Resetting to value in some occasions

### ISSUE THREAD

**Issue by obarcelonap** [dynatrace-oss/barista#1427]
# Bug Report

## Current Behavior

When a value in the combobox has been selected, after deleting the value having pressed the delete key it some occasions it resets the value to other one, hidding the autocompletion.

## Expected Behavior

I'd expect the value is selected (bold font) but still the autocompletion panel is opened and showing more options (if there's more)

## Possible Solution

Might be related to debouncing and performing async operations for retrieving the different options considering the input.

## Steps to Reproduce

Reproducible here: https://stackblitz.com/edit/dtcombobox
Screen recording: [Screen Recording 2020-08-04 at 10.10.45.zip](https://github.com/dynatrace-oss/barista/files/5020989/Screen.Recording.2020-08-04.at.10.10.45.zip)

1. select a value
2. delete the value keeping the delete key pressed
3. sometimes the value gets reset

**Comment by tomheller** [comment]
Thank you for reporting this one. this seems like a really weird behaviour.

**Comment by lukett89** [comment]
Hi guys, the same reset issue can still be reproduced by following these steps: 
1. Start typing an option
2. Select the option
3. Then the reset event is sent when the option has been selected
