### ISSUE TITLE
Deploy design-tokens-ui to vercel

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#1429]
# Feature Request

## Summary

We want to have the design tokens app deployed to vercel. 

## Feature Description

Deploy design tokens UI to vercel.

The domain could be design-tokens-ui.dynatrace-oss.vercel.app would be a default one that is good enough for now. Once the app can solve a usecase e2e we should think about a better domain. 

We can deploy the app to production on master and create a preview on PRs. I guess a github action is perfect for this usecase.

**Comment by lukasholzer** [comment]
@ffriedl89 would safty check how many github actions minutes we have left in the organization, before we start implementing a solution.

**Comment by ffriedl89** [comment]
aren't github actions free for open source?

**Comment by tomheller** [comment]
I have no idea why I added the bug label here, I'm sorry. 

> aren't github actions free for open source? 

I think they are free, but I guess they are on a quota as well.

**Comment by lukasholzer** [comment]
No you should have 2000min free credits as far as I know.
