### ISSUE TITLE
DtFilterFieldDefaultDataSource should always work with the root object

### ISSUE THREAD

**Issue by danielkaneider** [dynatrace-oss/barista#1438]
# Feature Request

## Summary
DtFilterFieldDefaultDataSource should always work with the root object, instead of using partial results.

## Feature Description
In 
https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleFilterFieldAsync/
the partial data is set after the suggestions are loaded
```
{
    name: 'AUT (async)',
    autocomplete: [{ name: 'Linz' }, { name: 'Vienna' }, { name: 'Graz' }],
};
```

It would be easier, if the data source would always work with the root object. I.e. initial state:
```
{
    autocomplete: [
      {
        name: 'AUT (async)',
        async: true,
        autocomplete: [],
      },
      {
        name: 'USA',
        autocomplete: [
          { name: 'San Francisco' },
          { name: 'Los Angeles' },
          { name: 'New York' },
        ],
      },
    ],
  }
```
after the data is loaded, the datasource would get
```
{
    autocomplete: [
      {
        name: 'AUT (async)',
        autocomplete: [{ name: 'Linz' }, { name: 'Vienna' }, { name: 'Graz' }]
      },
      {
        name: 'USA',
        autocomplete: [
          { name: 'San Francisco' },
          { name: 'Los Angeles' },
          { name: 'New York' },
        ],
      },
    ],
  }
```

**Comment by thomaspink** [comment]
@danielkaneider thanks for the feedback. 

You mean that the async loaded partial data would be placed (merged) into the root object?

**Comment by danielkaneider** [comment]
Yes, IMHO that would make it easier. And probably also fix https://github.com/dynatrace-oss/barista/issues/1436

**Comment by tomheller** [comment]
@thomaspink To my understanding there was a reason why we did not merge the async data into the original datasource. Due to the nature of trying to recreate the already set filters, this could reset all filters that already have been set, right?

**Comment by thomaspink** [comment]
There would be 2 issues with these approach:
1. We can not alter the original consumer object. Changing the original data structure is considered bad practice. A clone might work.
2. When doing this, it would break server side filtering, because then it is not possible to load the paritial (maybe with different results) more than once as it is then fix to this dataset.

So sadly, merging it is not an option.

**Comment by thomaspink** [comment]
@tomheller yeah this might be another issue

**Comment by danielkaneider** [comment]
> 
> 
> There would be 2 issues with these approach:
> 
>     1. We can not alter the original consumer object. Changing the original data structure is considered bad practice. A clone might work.
Could be, but isn't the provider of the datasource (not the filter-field) responsible to take care of this? The idea would be to have a single-source of truth, something like an ngrx state. 
> 
>     2. When doing this, it would break server side filtering, because then it is not possible to load the paritial (maybe with different results) more than once as it is then fix to this dataset.
Not necessarily: if the autocomplete options are loaded, and the `partial` flag is still set, this should work.

**Comment by lukasholzer** [comment]
Currently not on our roadmap
