### ISSUE TITLE
[Filter field] The text of the filter overlay exceeds the overlay border

### ISSUE THREAD

**Issue by seilmsteiner** [dynatrace-oss/barista#1439]
# Bug Report
The overlay of the filter component can not handle very long filter values. If the filter value is too long the text exceeds the overlay box.

## Expected Behavior
The text of the filter value should have a line break, before the text exceeds the overlay. Truncating the name is not an option because the user is not able to read the full filter value. 
## Current Behavior

![image](https://user-images.githubusercontent.com/69236477/89384714-c433fc80-d6fe-11ea-9b0e-4f9b04be0389.png)

## Steps to Reproduce

- go to https://barista.lab.dynatrace.org/components/filter-field#unique-free-text-or-range-options
-  insert a very long name in the free-text filter field
-  hover over the applied filter

## Context (Environment)
- Barista documentation

**Comment by tomheller** [comment]
@seilmsteiner thank you for reporting this. I'm going to look into word wrapping layouts in the overlay to mitigate this problem.
