### ISSUE TITLE
Investigate esbuild for bundling instead of rollup

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1447]
# Feature Request

Investigate [esbuild](https://github.com/evanw/esbuild) for creating javascript bundling as it depends on go it is incredible fast through parallelization.

![image](https://user-images.githubusercontent.com/11156362/89413793-b051c000-d729-11ea-8689-feef6881f36a.png)

It would be an option to use with bazel as bazel has first class support for go_rules (We could leverage the API implementation and write a macro for a go rule that uses the Go API or Go CLI - https://godoc.org/github.com/evanw/esbuild/pkg/api

The goal is to create rollup bundles for es2015 and es5 for an angular application or the APF 10 for the components. The typescript compilation should be handled by tsc. 

**The goal would be to have:**

- minification (like terser)
- optimization (treeshaking)
- bundling 

**It is not a goal to:**

- transpile typescript or any other language
- Do anything angular related

**Comment by lukasholzer** [comment]
@ffriedl89 @tomheller  please provide your opinion on that. @ddprrt do you have experience with it as snowpack and vite are using it?

**Comment by tomheller** [comment]
I'm not sure if I can provide a valid opinion on this one. I'm not very familiar with the various feature sets of rollup or esbuild. 
If you think we can get the same value as we would get with rollup with esbuild and get the build time reduced, this is fine for me. 

The only problem I would see is that if we would need to extend rollup with some sort of custom plugin, this could be done in JS/TS, whereas esbuild would require you to write go (if it even allows extending / writing plugins).

**Comment by lukasholzer** [comment]
@tomheller regarding the js/ts they have a js API as well but it calls the go binary and communicates via stdin/out so it is a little bit slower :D

**Comment by lukasholzer** [comment]
We should have a minimal bazel rule `esbuild` that leverages esbuild to bundle javascript. This is needed quite often.
