### ISSUE TITLE
DesignToken generation to CLI tool

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1449]
# Feature Request

Currently, the design token generation is an Angular builder to our Road of bazelifying everything we have to first update it to a CLI tool that can be executed via Bazel.

The CLI tool can be then executed and should generate the design tokens via bazel. This is needed for our designtoken apps.

This is split up into four steps:

- [x] Design token builder #1529
- [ ] Dependency tree
- [ ] packaging
- [ ] Tailwind CSS generation

**Comment by tomheller** [comment]
I think we will need at least 2 cli tools. One for the color generation feeding the design token generation and one for the design token generation...
