### ISSUE TITLE
Rework and simplify stage release script

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1461]
# Bug Report

Currently, the stage-release script should only bump the package version and update the CHANGELOG file.

- [ ] Remove checks. We have a lot of checks like (if there are some running checks on master) which is in this step really irrelevant that only blocks from releasing.
- [ ] Remove Co-Authoring from changelog `Co-authored-by: ffriedl89 <ffriedl89@gmail.com>`
- [ ] Add a formatting of the CHANGELOG before committing, because otherwise the github check always fails. Currently you have to run `npm run format:write` everytime when you create a changelog this is cumbersome.
- [ ] Furthermore, the CHANGELOG generation is not correct and accurate as it has commits in there that are already released in a previous version:

### New generated Changelog for 8.0.0-rc.0
![image](https://user-images.githubusercontent.com/11156362/89769456-743da700-dafd-11ea-95f9-311a6a4d6919.png)

### Already released 7.7.0 fixes

![image](https://user-images.githubusercontent.com/11156362/89769503-83bcf000-dafd-11ea-81c5-2a114f698c21.png)

## Simplified approach

In my opinion, checks aren't needed as they are running on the release script itself.
We only have to perform those steps.

1. Commandr with options for wich release (add rc versions in dropdown as well)
2. Get all commits since the last release
3. Create a new release branch with propper upstream
4. Create a changelog for the last commits and append it.
5. Format the changelog
6. Bump version in package-lock.json and package.json
7. Ask if all is fine:
8. Push the commit to the upstream

**Comment by ffriedl89** [comment]
Won't be changed anymore
