### ISSUE TITLE
Radial chart: Add legend filtering capabilities

### ISSUE THREAD

**Issue by PedroMosquera** [dynatrace-oss/barista#1478]
# Bug Report

We need, the **radial chart** to have the filtering capabilities, as in other barista's charts, by clicking in the legends.

## Expected Behavior

When the user clicks on any of the legend item, in the chart, should toggle the visibility of this one in chart.

**_You can use the following chart as an example:_**
https://barista.dynatrace.com/components/chart#donut-or-pie-chart

| Shown             |  Hidden |
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/20814335/89891624-b33f2b80-dbd5-11ea-8599-91ff16659dfa.png) | ![image](https://user-images.githubusercontent.com/20814335/89891652-be925700-dbd5-11ea-9517-2c74c786855b.png)

## Current Behavior

For the current implementation, if the user clicks, in one in the legend, nothing happens.

https://barista.dynatrace.com/components/radial-chart

## Steps to Reproduce

1. Go to https://barista.dynatrace.com/components/radial-chart
2. Click on any legend

**Comment by lukasholzer** [comment]
@PedroMosquera this is not a bug it is a feature – it was never capable of this behaviour if you need it please contribute it to the library as you are already familiar with the charts :)

If you need any guidance please reach out to us via DM. 

If you want to start this feature please provide a first small API proposal first that outlines the changes :)

**Comment by PedroMosquera** [comment]
Thanks @lukasholzer, for updating the ticket 😁

@subarroca is the one that will handle this one. (We have already discussed it) :)
