### ISSUE TITLE
Combobox simple example throws ExpressionChangedAfterItHasBeenCheckedError 

### ISSUE THREAD

**Issue by NagRock** [dynatrace-oss/barista#1485]
# Bug Report

I'm getting error with simple example of `combobox`.

## Expected Behavior

No error

## Current Behavior

`Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'aria-selected: false'. Current value: 'aria-selected: true'.` is thrown

## Steps to Reproduce

1. Just enter the page:

https://stackblitz.com/edit/github-w8bmzm-pshyfk?file=src%2Fcombobox%2Fcombobox-simple-example%2Fcombobox-simple-example.html

### Used Versions:

- **typescript**: `3.8.3`
- **angular**: `9.1.12`
- **@angular/cdk**: `9.2.4`
- **@dynatrace/barista-components**: `7.5.1`

**Comment by ffriedl89** [comment]
Moved to internal issue tracking
