### ISSUE TITLE
Expandable-section component not working on internal barista

### ISSUE THREAD

**Issue by SaraDavilaMendez** [dynatrace-oss/barista#1489]
# Bug Report

## Expected Behavior

I found this inconsistency in the barista expandable-section component, where the component should be disabled!
![image (3)](https://user-images.githubusercontent.com/16416038/90101744-89a21380-dd3f-11ea-8675-00ea27ab16ef.png)

## Current Behavior

But sadly it is enabled. 😢 
Interestingly enough the stackblitz version of the example works as expected. (found by @bardosmisi )

## Possible Solution

In the example above adding the class "dt-expandable-section-disabled" is doing the trick, but the question is:
why is the attribute disabled not working?

![image](https://user-images.githubusercontent.com/16416038/90102508-0ed9f800-dd41-11ea-999d-1733721cded0.png)

## Steps to Reproduce

1. Go to internal barista

## Context (Environment)

My task is to write jira storys for an intern that is going to write selenium test on barista components.
The first step is to transform the components from html elements to java components. 
In the process of finding the functionalities each of the component has, we (the intern and I) found out that the "disabled" attribute is not working as expected in all the components.

**Comment by lukasholzer** [comment]
I think this is related to #1472

**Comment by thomaspink** [comment]
Fixed by PR #1491
