### ISSUE TITLE
Nested structural directives break DtStepper rendering in Ivy

### ISSUE THREAD

**Issue by toddbaert** [dynatrace-oss/barista#1492]
# Bug Report

## Expected Behavior

The component should render even if structural directives are used in the projected content within a step, when using the Ivy compiler. 

## Current Behavior

All dt-steps and the stepper markup fails to render if Ivy is used.

## Possible Solution

?

## Steps to Reproduce

This is not reproducable in stackblitz, so I have created a repo with the minimal reproduction: https://github.com/toddbaert/stepper-issue. This must be compiled with Ivy.

### Used Versions:

- **node**: v12.18.0
- **npm**: 6.14.4
- **typescript**: 3.7.5
- **angular**:9.0.6
- **@angular/cdk**: 9.1.0
- **@dynatrace/barista-components**: 7.7.0

**Comment by lukasholzer** [comment]
Hey @toddbaert thank you very much for reporting this issue!

Will perform an investigation.

**Comment by ffriedl89** [comment]
Moved to internal issue tracking
