### ISSUE TITLE
Integrate the design tokens Figma plugin

### ISSUE THREAD

**Issue by SkaillZ** [dynatrace-oss/barista#1495]
# Feature Request
The design tokens Figma plugin which currently located in a private repository should be moved here. Currently blocked by #1449 since it's built with Bazel.

**Comment by SkaillZ** [comment]
Blocked by #1515 since we don't build the tailwind CSS in Bazel yet and using the provider is a better idea anyway

**Comment by lukasholzer** [comment]
Moved to APM-266049
