### ISSUE TITLE
Add visual regression testing using percy

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#15]
Percy seems to be good choice for visual testing. https://percy.io/

**Comment by lukasholzer** [comment]
We could leverage percy with our e2e tests with testcafe https://blog.percy.io/new-percy-sdk-end-to-end-visual-testing-with-testcafe-7b778a491746

**Comment by lukasholzer** [comment]
I've investigated percy but I see problems in their free pricing plan.

They do not offer a special open source package so the key point is the **5,000 screenshots / month**.

When doing the maths:

We have currently 271 examples (number will raise), so divided by 5.000 available screenshots we would exceed that after **18 runs**.

> So percy is sadly no option for us.

But storybook has a perfect visual regression testing that supports a variety of vendors and even easy self made solutions.

We should investigate storybook
