### ISSUE TITLE
Tree-table doesn't hide overflow of child nodes

### ISSUE THREAD

**Issue by leonschloemmer** [dynatrace-oss/barista#1502]
# Bug Report

## Expected Behavior

Tree-table component should hide the overflow of child node cells that contain text which is too long

## Current Behavior

The table's width gets bigger than the viewport and / or its parent element

## Steps to Reproduce

https://stackblitz.com/edit/github-wjgnuy?file=src/app/app.component.ts

## Context (Environment)

The tree-table component will be used to build the Angular version of the waterfall component which is part of Dynatrace DEM.

### Used Versions:

- **node**: >=10.13.0
- **npm**: 6.14.4
- **typescript**: 3.8.3
- **angular**: 9.1.12
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: 7.5.1

## Detailed Description

The tree-table component should hide text which is too wide for the table in a similar fashion to the Barista table component (with "...")
![image](https://user-images.githubusercontent.com/31950955/90414650-5ac5cd80-e0b0-11ea-95bc-c791fb1b757d.png)

**Comment by lukasholzer** [comment]
got reverted by #1708
