### ISSUE TITLE
More understandable interactive example for tag component

### ISSUE THREAD

**Issue by SaraDavilaMendez** [dynatrace-oss/barista#1507]
# Feature Request

## Summary

The current interactive example for the tag component in the barista doc for dynatrace could be improved.

## Feature Description

The current example looks like this:
https://stackblitz.com/edit/github-jhgfbi?file=src/app/app.component.ts

I would recommend to change it to something like this:
https://stackblitz.com/edit/github-ws2lcp?file=src%2Findex.html

**Comment by lukasholzer** [comment]
Moved to APM-266052
