### ISSUE TITLE
filter-field docs: Improve documentation vor datasets with more than 2 levels for the filter-field

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#1509]
It is not clear to all users how to make the filter field work with more than 2 levels of data (currently all our examples have 2 levels). 

Add a section and example to the default data source how the data should be structured to achieve more than 2 levels (theoretically infinite). Also make it clear that only leaf nodes can be ranges/free text inputs, ... All other levels currently have to be autocompletes

**Comment by TannerGilbert** [comment]
Would really appreciate that. I'm currently using the code shown in the  [**Changing the default parsing of filter values** section](https://barista.lab.dynatrace.org/components/filter-field#adding-filters-programmatically). Is this the correct way of working with more than 2 levels?

**Comment by ffriedl89** [comment]
Moved to internal issue tracking
