### ISSUE TITLE
web-component overlay/popover positioning in the DOM

### ISSUE THREAD

**Issue by peter-affenzeller** [dynatrace-oss/barista#1513]
# Feature Request

We need something similar to angular cdks overlay for handling the positioning of popovers created with [popper.js](https://popper.js.org/docs/v2/lifecycle/) in the DOM.

## Summary

Currently, popovers are created in place.
Example ComboBox:
The container of the popover is a descendant of the combobox. The popover is positioned correctly (absolute positioning with values calculated by popper.js), but the container stays at the position in the DOM where it was initially created.
In case the user puts the combobox inside a container with `overflow: hidden` and the position set to something other than default, the popover gets cut off if the container is smaller than the popover.

## Feature Description

We need to move the popover container in the DOM, as angular cdk does, to assure that the overlay does not get cut off.

**Comment by thomaspink** [comment]
There are currently 2 points to discuss:
1. Do we want to have sophisticated positioning logic to move the overlay to the best fitting position next to the reference element.
2. Do we want to move the overlay DOM element out to the document body to prevent a cut-off if any parent component has an `overflow: hidden` on it.

**Opinion:**

1. Not sure if we need that complicated positioning for every overlay. Especially simple overlays like select or combobox. (@peter-affenzeller maybe you can add your thought on how complicated/easy it is working with the positioning library you have chosen)
2. Moving the overlay DOM element to the body and creating a container that holds the overlay may be relative easy to achieve. If we do not want go for that I am not sure on how to communicate this to the consumer that `overflow: hidden` in parents is not allowed.

**Comment by lukasholzer** [comment]
I think this is a very common use case used for drawable content etc. where you need an overflow hidden on the parent. The calculation of the position does not take the parent container into account it thinks there is enough space to the window and then the overlay gets cut off.

![image](https://user-images.githubusercontent.com/11156362/91023262-9dc6fa00-e5f6-11ea-97f6-9ed93394ed07.png)

**Comment by peter-affenzeller** [comment]
regarding positioning at the best fitting position:
you can specify a preferred location for the overlay when creating the popover (e.g. `bottom-left`) and pass modifiers for additional calculations, e.g. `offset` and also `flip`, which flips the overlay from the preferred bottom position to top if the space beneath the reference element is not sufficient.

you can also use auto positioning, which calculates the best fitting position, and provide a function e.g. for calculating the offsets based on the current position.
the order of the placements to apply when there is not enough space can be also be customised, e.g. preferred `bottom`, when flipping, first go to `right` (or `left`), then to `top`

**Comment by peter-affenzeller** [comment]
there is also a position strategy "fixed", which changes the popover's absolute positioning to fixed, which would bypass the `overflow: hidden` problem, but it still doesn't work if the container has one of the properties set that create a fixed positioning containing block [see w3](https://www.w3.org/TR/css-position-3/#fixed-positioning-containing-block), if this is the case it's even worse than with absolute positioning, since it totally messes up popperjs' position calculation...

**Comment by ffriedl89** [comment]
I think we can totally ignore this edge case for now. I have not seen any other component library than Angular Material that deals with the overflow issue in a similar fashion. 
Primer by Github does the simplest of simple approaches - position: relative and absolute on the dropdown. 
Same goes for tooltip placements in various systems. Explicit placements - the dev chooses for left, top, right, bottom position. No reflow. 

I'd say keep it simple now, use popper if it makes sense, deal with edge cases in the future. Overflow:hidden can be something that is mentioned in a doc that is not supported.

**Comment by lukasholzer** [comment]
This issue only contains positional logic and we should use popper.js for doing the calculations.

For moving it to the body that should be discussed in a separate issue.
