### ISSUE TITLE
[microchart] tooltips not working

### ISSUE THREAD

**Issue by tkaiser** [dynatrace-oss/barista#1528]
# Bug Report

## Expected Behavior

Tooltips should show up in microchart.

## Current Behavior

Tooltips dont show up.

## Steps to Reproduce

Example in the docs: https://barista.lab.dynatrace.org/components/micro-chart#column-chart
Direct link to stackblitz: https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleMicroChartColumns/

**Comment by lukasholzer** [comment]
Thank you very much for reporting this issue! Do you want to try to contribute the fix for the problem?
