### ISSUE TITLE
Barista: Add preview images for the components instead of shortcuts

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1536]
# Feature Request

Instead of using shortcuts in the tiles provide some images like (duet design system or material)

![image](https://user-images.githubusercontent.com/11156362/91704203-9023ee00-eb7b-11ea-9f23-845ca7831988.png)

![image](https://user-images.githubusercontent.com/11156362/91704220-9ade8300-eb7b-11ea-9fe9-1550d632e0ab.png)

## Goal

To provide better insights in how to choose which components it is necessary to provide a little bit more context via an image and a short description of the component. This should help consumers finding the right component easier.

As a first step, I would suggest screenshotting the examples and uploading them to the image manager.

**Comment by rowa-audil** [comment]
ToDo:
- [ ] Take screenshots of all the components
- [ ] Upload them to the image-manager
- [ ] Load the images when the components overview page is opened
- [ ] Display them instead of the abbreviation
- [ ] Write short and spicy descriptions for the components below the images (if missing) or update them

**Comment by rowa-audil** [comment]
A prototype of image previews on the components overview page on with and the other without border-bottom:

NOTE: The image sizes are not relevant here. They will be adjusted accordingly.

<img width="1315" alt="Screenshot 2020-09-16 at 09 45 13" src="https://user-images.githubusercontent.com/57528898/93307620-7b915800-f801-11ea-8a89-244ddcd3d829.png">
OR:
<img width="950" alt="Screenshot 2020-09-16 at 09 51 40" src="https://user-images.githubusercontent.com/57528898/93308200-42a5b300-f802-11ea-935d-5edb9742e238.png">

**Comment by NinaKammerlander** [comment]
Do you intend to keep the triangles with icons for favorites or experimental components? If yes, where would you place them?

**Comment by lukasholzer** [comment]
@rowa-audil this looks already pretty awesome! I would prefer the border (maybe a little bit lighter) But I think it does the job already pretty well 👍

**Comment by rowa-audil** [comment]
> @rowa-audil do you intend to keep the triangles with icons for favorites or experimental components? If yes, where would you place them?

@NinaKammerlander I think at the original place on the top right corner above the image.

**Comment by rowa-audil** [comment]
<img width="307" alt="Screenshot 2020-09-16 at 14 26 23" src="https://user-images.githubusercontent.com/57528898/93337130-fde14280-f828-11ea-9942-14a329fc3460.png">

I think we should keep thre abbreviations though
