### ISSUE TITLE
Slack Webhook is failing for release

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1537]
# Bug Report

The github action that should post the release notes in the internal slack channel failed with a 400 error.
https://github.com/dynatrace-oss/barista/runs/1050227071?check_suite_focus=true

![image](https://user-images.githubusercontent.com/11156362/91705856-d712e300-eb7d-11ea-8747-98d544da099e.png)

**Comment by SkaillZ** [comment]
Seems like some environment vars are missing. Maybe there's an issue because the last release wasn't created by `dt-ci` so credentials might be missing?

![image](https://user-images.githubusercontent.com/5956280/92099099-64eb0a00-edda-11ea-9f86-8f2caf385689.png)

**Comment by lukasholzer** [comment]
So can we close it then?
