### ISSUE TITLE
[Explorer] Color palette drop down is shifted and cut from the right side on Tablet

### ISSUE THREAD

**Issue by yarynabarninets-car** [dynatrace-oss/barista#1550]
# Bug Report

## Expected Behavior
Drop down menu should not be shifted, it should be aligned vertically with drop down picker, also it should not be cut from the right side.

## Current Behavior
Color palette drop down is shifted and cut from the right side on Tablet

## Context (Environment)
Environment: Samsung tablet 10.5-inch 1,600 x 2,560 resolution. Browsers: Opera, FF, Samsung browser

## Attachments
![image](https://user-images.githubusercontent.com/70687822/92086207-28171700-edca-11ea-93be-931516a7d6bf.png)

**Comment by lukasholzer** [comment]
Hey @yarynabarninets-car just to mention it was on swiping or how do you reproduce it? It is not on the initial load?

**Comment by yarynabarninets-car** [comment]
It is the view by default, it doesn't fit the screen entirely, needed to swipe left to see the whole page

**Comment by lukasholzer** [comment]
@yarynabarninets-car can you create a Stackblitz example to reproduce the behaviour in a standalone environment to be sure it is not an issue from the surrounding layout. 

providing a simple to reproduce example helps to eliminate potential error cases.

You can use this example as starting point :)
https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleSelectDefault/

**Comment by ffriedl89** [comment]
Cannot reproduce
