### ISSUE TITLE
[Chart] Allow to pin the tooltip

### ISSUE THREAD

**Issue by rarenal** [dynatrace-oss/barista#1551]
# Feature Request
Add support for pinnable tooltip in the chart component

## Feature Description

When users hover a chart series, a tooltip is displayed with the hovered point info. However, there is currently no way to fix that tooltip, limiting the possible interactions with the overlay, like adding links or buttons.
![image](https://user-images.githubusercontent.com/11938799/92129782-426de680-ee04-11ea-9435-18ac080eaaba.png)

Feature details:
* Add an option to dt-chart-tooltip to be pinnable
* When clicking on a chart, the displayed tooltip gets fixed in the chart view, disabling hovering over the rest of points a displaying a close button (X) to close the tooltip.
* If the user clicks outside or the close button (X), the pinned tooltip is closed and hovering over the data points is enabled again.

**Comment by SkaillZ** [comment]
Thanks for the suggestion, @rarenal. Would you like to contribute this feature to the library?

**Comment by lukasholzer** [comment]
Not on our roadmap
