### ISSUE TITLE
[drawer] doc does not mention change from side mode to overlay mode

### ISSUE THREAD

**Issue by christian-fischer** [dynatrace-oss/barista#1552]
# Bug Report

## Expected Behavior

The doc page should mention, that the mode changes from side to overlay, when `max-size` is less than 1024px

## Current Behavior

No mention on the doc page of the drawer of this behavior.

### Used Versions:

- **@dynatrace/barista-components**: current master

**Comment by SkaillZ** [comment]
Thanks for noticing and reporting this, @christian-fischer. Would you like to contribute a fix to the documentation?

**Comment by christian-fischer** [comment]
@SkaillZ sadly I don't have the necessary temporal resources at the moment to contribute a fix for this.
