### ISSUE TITLE
[Filter field] Autocomplete resized on scroll

### ISSUE THREAD

**Issue by rarenal** [dynatrace-oss/barista#1553]
# Bug Report
When having autocomplete values with different widths, if those are not shown initially, when the user scrolls to see those elements, then the autocomplete self-resizes to fit the content. It looks really weird that the width changes while resizing.

**Stackblitz with the issue:**
https://stackblitz.com/edit/github-hatoqc?file=src/filter-field/filter-field-distinct-example/filter-field-distinct-example.ts

**Steps to reproduce**
1. Focus the filter field component.
2. Select "AUT" option
3. When the values are displayed, scroll down and check how the autocomplete is resized while scrolling

**Comment by lukasholzer** [comment]
@rarenal Hey thanks for creating an issue for that! Indeed it should have the width of the max item if there is no virtual scrolling. 

Do you want to contribute this issue to the library?

**Comment by rowa-audil** [comment]
@rarenal Can you update the @dynatrace/barista-components 8.0.0 which would fix this issue.

**Comment by rowa-audil** [comment]
Closing this issue as it is solve with `angular 10 & barista-components 8.0.3`
