### ISSUE TITLE
[npm run lint] error on windows: xargs is not recognized as an internal or external command

### ISSUE THREAD

**Issue by christian-fischer** [dynatrace-oss/barista#1554]
# Bug Report

## Expected Behavior

No error when running `npm run lint` on windows.

## Current Behavior

```
'xargs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! @dynatrace-oss/barista@8.0.0 bazel:stylelint: `bazelisk query "attr(generator_function, stylelint, //...)" | xargs bazelisk test`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the @dynatrace-oss/barista@8.0.0 bazel:stylelint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Steps to Reproduce

1. run `npm run lint` on a windows system

## Context (Environment)

Windows

### Used Versions:

- **node**: v12.16.1
- **npm**: 6.14.8
- **@dynatrace/barista-components**: 8.0.0

**Comment by lukasholzer** [comment]
Hey @christian-fischer please install the [msys2](https://www.msys2.org/) package for windows to be able to run this command.

I updated the development section https://github.com/dynatrace-oss/barista/pull/1575/files to provide in-depth instruction for windows users. 

When you enter `wehre bash` in your command prompt it has to return `C:\msys64\usr\bin\bash.exe` it is important to have the msys64 in your `PATH` environment variable:

![image](https://user-images.githubusercontent.com/11156362/92446469-25476800-f1b6-11ea-9361-da47bc58c5e4.png)

**Comment by christian-fischer** [comment]
Thanks @lukasholzer , I followed your updated instructions to install msys2, bazel and vs build c++ tools. 
```
C:\workspaces\barista>where bash
C:\msys64\usr\bin\bash.exe
C:\Program Files\Git\usr\bin\bash.exe
```
Now I'm faced with the following error output when running `npm run lint`:

```(Error: Command failed: C:\workspaces\barista\node_modules\.bin\ngc -p view-engine-tsconfig.json
The system cannot find the path specified.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\workspaces\\barista\\node_modules\\.bin\\ngc -p view-engine-tsconfig.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @dynatrace-oss/barista@8.0.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @dynatrace-oss/barista@8.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by lukasholzer** [comment]
@christian-fischer please update with the latest master as the fix for this is already merged :)

**Comment by christian-fischer** [comment]
@lukasholzer I just pulled the latest upstream master and ran `npm run lint` again:
```
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
npm ERR! code ELIFECYCLE
npm ERR! errno 123
npm ERR! @dynatrace-oss/barista@8.0.0 bazel:stylelint: `bazelisk query "attr(generator_function, stylelint, //...)" | xargs bazelisk test`
npm ERR! Exit status 123
npm ERR!
npm ERR! Failed at the @dynatrace-oss/barista@8.0.0 bazel:stylelint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\christian.fischer\AppData\Roaming\npm-cache\_logs\2020-09-08T10_43_58_082Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 123
npm ERR! @dynatrace-oss/barista@8.0.0 lint: `nx workspace-lint && npm run affected:lint -- --parallel && npm run bazel:stylelint`
npm ERR! Exit status 123
npm ERR!
npm ERR! Failed at the @dynatrace-oss/barista@8.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\christian.fischer\AppData\Roaming\npm-cache\_logs\2020-09-08T10_43_58_133Z-debug.log
```

**Comment by lukasholzer** [comment]
@christian-fischer can confirm this error now on my remote windows setup :) will take a look! Sorry windows support is currently poor as we don't have windows ci resources and we are all Linux, mac devs or windows with WSL. 

But I'm currently working in this sprint to fix all the windows bugs. Sorry for the inconvenience.

**Comment by christian-fischer** [comment]
Hmmm... adding "C:\msys64\usr\bin" to the path sadly has another undesired side effect:
![image](https://user-images.githubusercontent.com/5974170/93576781-897ae080-f99b-11ea-87ef-ad37ad21f55f.png)
All commits in eclipse are aborted in pre-commit hook. 
As soon as I remove msys from the path again, committing works again in eclipse.
So I have to remove the msys path entry again ...

**Comment by ffriedl89** [comment]
Moved to interal issue tracking
