### ISSUE TITLE
[Filter field] Free text option should support async data

### ISSUE THREAD

**Issue by danielkaneider** [dynatrace-oss/barista#1557]
# Feature Request

## Summary

Currently the filter field (among others) supports async options and free text. However, it is not possible to set _async_ on a free text.

## Other functional requirements
* nice to have for the user: a hint, that the user knows that it is possible to enter a custom text

**Comment by SkaillZ** [comment]
Thanks for the suggestion, @danielkaneider. Would you like to contribute this feature to the library? We from the DesignOps team would be happy to guide you through the process.

**Comment by ffriedl89** [comment]
Currently not on our roadmap
