### ISSUE TITLE
[quick-filter] sidebar does not collapse all the way

### ISSUE THREAD

**Issue by christian-fischer** [dynatrace-oss/barista#1559]
# Bug Report

## Expected Behavior

Sidebar should collapse flush with the filter-field

## Current Behavior

With lots of content the sidebar does not close all the way, but there's a visible gap (see screenshot below).
Also when resizing the viewport the size of the gap changes until the content fits.

## Steps to Reproduce

Reproducer: https://stackblitz.com/edit/github-8uplzf

1. collapse the sidebar
2. observe the gap

1. collapse the sidebar
2. resize the window
3. observe the changes in the gap

### Used Versions:

- **@dynatrace/barista-components**: 8.0.0

## Attachments

- when collapsing:
![image](https://user-images.githubusercontent.com/5974170/92234548-8c150a80-eeb2-11ea-9cf8-8f9455434277.png)

- after resizing:
![image](https://user-images.githubusercontent.com/5974170/92234644-b23aaa80-eeb2-11ea-913a-72dbff77df89.png)

**Comment by lukasholzer** [comment]
Thank you for reporting this issue! (This might be an issue of the dt-drawer)

**Comment by lukasholzer** [comment]
This issue is not reproducible for me even on the stack blitz example you provided.

**Comment by christian-fischer** [comment]
@lukasholzer If you like, we can do a short call to show you how it's reproducible

**Comment by ffriedl89** [comment]
Moved to interal issue tracking
