### ISSUE TITLE
Filter field: Clear free text on lost focus

### ISSUE THREAD

**Issue by OFouda** [dynatrace-oss/barista#1572]
# Bug Report<!---

## Expected Behavior

Random text in filter field should be cleared on focus loss

## Current Behavior

Text remains as it is.
In the filter field, users can type in some text that does not match any available option. This text remains in the field even after it looses focus which can wrongly give the impression that some filter is applied when it is not

## Possible Solution

Remove any text in the field on focus loss and keep only the selected filter pills. 

![image](https://user-images.githubusercontent.com/6033268/92433750-4308d300-f19e-11ea-9950-aa4bf4b4ef45.png)

**Comment by lukasholzer** [comment]
Reverted with #1650 as it caused side effects that the filter field is not working

**Comment by lukasholzer** [comment]
@OFouda I did short sync with @tomheller about this issue and in our opinion, it is working as expected. As it behaves like every other input field as well. Think about the use case that someone starts filtering then he copy-pastes an id or something into the field it would be cleared so every input is behaving the same. If you want to clear it to use `command + A ` and then `del`.

So I will close this issue.
