### ISSUE TITLE
Filter Field Stackblitz link is not working for DtExampleFilterFieldCustomParser

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1574]
# Bug Report

The link to the Stackblitz example for the `DtExampleFilterFieldCustomParser` is not working.

https://barista.dynatrace.com/components/filter-field#changing-the-default-parsing-of-filter-values

![image](https://user-images.githubusercontent.com/11156362/92437152-91ba6b00-f1a6-11ea-95e1-9581a65626a1.png)

**Comment by SkaillZ** [comment]
Seems to work again.
