### ISSUE TITLE
fluid-core: Support for UP'n DOWN arrows

### ISSUE THREAD

**Issue by rowa-audil** [dynatrace-oss/barista#1584]
# Feature Request

As per #1512 the core lib is introduced to the fluid-elements which currently consists of a helper function for evaluating what the next index is by a given length and direction (arrow keys).
In order to generalize the function, we add support for the up and down arrows as well.

## Feature Description

Additional arrow support for UP and DOWN arrow keys

## Attachments
none

**Comment by lukasholzer** [comment]
Implemented with #1597
