### ISSUE TITLE
[fluid-input] Add value and name attributes to fluid input.

### ISSUE THREAD

**Issue by bardosmisi** [dynatrace-oss/barista#1587]
# Feature Request

In order to make the input field serializable, we should consider adding value and name attributes.

Also the fluid input should be presented in the fliud-dev app, in order to demonstrate its capabilities.

https://github.com/dynatrace-oss/barista/pull/1565#pullrequestreview-485729864

**Comment by lukasholzer** [comment]
We will close this issue as web components are not the way we want to create components in the future this is related to a shift of priorities in the team.

**Comment by dzintars** [comment]
@lukasholzer Hi. Mind you share a short reasoning to abandon web components idea? From the general perspective. I'm genuinely interested in the web components, but curious about any downsides. I would be grateful for a few words. 😃
