### ISSUE TITLE
[filter-field] Provide possibility for date range operators

### ISSUE THREAD

**Issue by danielkaneider** [dynatrace-oss/barista#1592]
# Feature Request

It would be nice, if there is some way to define range filters for date ranges somehow.

**Comment by thomaspink** [comment]
Hi Daniel. Thanks for your input. It would be great if you could add this feature to the filter field v2 issue: #951 

The current state of the filter field is not very suitable for these kind of new request, so we are panning to release a complete new version which hopefully full-fills all of the requested features.

**Comment by danielkaneider** [comment]
Then I'll close this as a duplicate
