### ISSUE TITLE
[fluid-input] Split up in FormFieldComponent and Input.

### ISSUE THREAD

**Issue by peter-affenzeller** [dynatrace-oss/barista#1596]
# Feature Request

As mentioned by @ffriedl89, we will need error handling, hints and labels for other form-components too.

> I've tried to use the input and I think it does a bit too much right now. I'd argue that the hint & label & potential validation messages are not bound to the input alone but rather to any form control.
> Having a `fluid-input` that maybe just proxies the HTMLInputElement specific properties seems better after i had a chance to try it out. The markup for the hint, errors and label should in my opinion be moved to a form-field component.
> 
> E.g.
> 
> ```
> <fluid-form-field name="filterby">
>     <label>Filter by</label>
>     <fluid-input type="text"></fluid-input>
> </fluid-form-field>
> ```

Add demo page for FluidInput
Add name and value property to FluidInput to make it serialisable.
Tests are also still missing for the FluidInput.

**Comment by lukasholzer** [comment]
We will close this issue as web components are not the way we want to create components in the future this is related to a shift of priorities in the team.
