### ISSUE TITLE
[Filter field] suggestions list disappear after clicking on one of suggested entries

### ISSUE THREAD

**Issue by pawel-bugalski-dynatrace** [dynatrace-oss/barista#1632]
# Bug Report

## Expected Behavior

After clicking on an item in a list it should be field into the filter field

## Current Behavior

Suggestions list disappear (note that pressing enter does work).

## Steps to Reproduce

![Screen Recording 2020-09-17 at 14 49 51](https://user-images.githubusercontent.com/67259865/93474698-005e9d80-f8f8-11ea-932b-2792e7b0e7b9.gif)

This is reproduced in a demo barista app but not in stackblitz (as on the time of writing it has a too old varsion)
http://localhost:4200/filter-field-default-example
### Used Versions:

- **node**: 
- **npm**: 
- **typescript**: 
- **angular**: 
- **@angular/cdk**: 
- **@dynatrace/barista-components**: 

## Detailed Description

This seems to be a regression caused by https://github.com/dynatrace-oss/barista/pull/1625

**Comment by samuelfahrngruber** [comment]
When trying to reproduce this reliably, I found out that this happens more frequently, when there are so few filter items displayed after filtering by text, that the scrolling bar disappears.

#### e.g. This works: 
![grafik](https://user-images.githubusercontent.com/35682879/93578308-7537e300-f99d-11ea-9742-eb2d60b87757.png)
#### This doesn't:
![grafik](https://user-images.githubusercontent.com/35682879/93578442-a0bacd80-f99d-11ea-8492-8a3ccb2cf109.png)

Also it seems that the issue happened after #1585, as commenting out `this._writeInputValue('');` solved the problem in the barista demo app for me.
