### ISSUE TITLE
Png and SVG generation/download does not work for icons in certain browsers

### ISSUE THREAD

**Issue by bardosmisi** [dynatrace-oss/barista#1633]
# Bug Report

Png generation does not work in FF. Also, some Icons are incomplete in certain SVG handling software.

## Expected Behavior

PNG and SG icons come out fine in supported browsers.

## Current Behavior

-If we go to the https://barista.lab.dynatrace.org/resources/icons/actionspersession page and download an icon as PNG in Chrome, it comes out fine, but if do that in FF the PNG is empty. (We generate the PNG from the source of the SVG, but in FF all the `"` characters in the string are escaped. Maybe that could somehow mess up the PNG generation.)

-If we download the icon as an SVG it can come out incomplete in other handling software. I was not able to repro this but @rrcaptain provided a screenshot: 
<img width="528" alt="Screenshot 2020-09-18 at 12 44 31" src="https://user-images.githubusercontent.com/7393576/93739461-a0fad900-fbe8-11ea-8abf-edf1d97f4aae.png">

**Comment by SkaillZ** [comment]
@rrcaptain Could you please provide an example for an icon what appears broken when downloading the SVG? I suppose you've tested it with Illustrator?

**Comment by lukasholzer** [comment]
Fixed with #1633
