### ISSUE TITLE
[Filter field] Should support deletable etc. tags via default data source

### ISSUE THREAD

**Issue by danielkaneider** [dynatrace-oss/barista#1639]
# Feature Request

Use-case: 
* I want to use the _filter-field_ with the _default-data-source_
* When filters are initially set via [filters] I'd expect that properties like [deletable] could be directly set.

However, this doesn't work. Filters need to be set, then retrieved again from the filter-fields, modified, and set again.

Also:
* this seems to require 2 lifecycle hooks (onInit, afterViewInit) to achieve this
* moreover, this requires custom access to the filter-field itself, instead of decoupling the nice functionality via the data-source

**Comment by lukasholzer** [comment]
Hey, @danielkaneider thanks for opening this issue. In my opinion this is a feature request and not a bug as you want to add behaviour that is not supported. 

Currently we are collecting requirements for a new version of the filter field so you can add this item there and we can then discuss how we wan't to proceed with it.

#951 would be the issue for collecting the feedback

**Comment by ffriedl89** [comment]
Currently not on our roadmap
