### ISSUE TITLE
[quick-filter] use internal id path from filter field and not require it in the data source

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#1647]

**Comment by lukasholzer** [comment]
Currently, the quick-filter component requires a `name` property in the data source to build a unique id for the path. The filter-field already has an internal id property that is built up so we should leverage it instead of requireing the user to provide one.

```typescript
export interface DtQuickFilterDefaultDataSourceSimpleOption {
  name: string;
}
```

The `name` is currently used to identify a option by its path. https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/experimental/quick-filter/src/state/reducer.ts#L151

```typescript
      // if the option is distinct we only have to check for the groups name because
      // there can only be one distinct option selected so we know immediately if it is selected
      if (distinct && parts[0] === path[0].name) {
        return true;
      }

      // if it is not distinct we have to build the full path out of the current filters to check
      // wether the path matches them provided node definition
      const dataPath = path.reduce(
        (previousValue, currentValue) =>
          `${previousValue.name}${DELIMITER}${currentValue.name}${DELIMITER}`,
      );

      // if the built path for the filters inside the array is equal to the option
      // in the provided nodeDef then we found our selected option
      if (item.option.uid === dataPath) {
        return true;
      }

```

and where the paths are built for the filters to set the `activeFilters` input on the quick-filter-group: https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/experimental/quick-filter/src/quick-filter-utils.ts

```typescript
import { DELIMITER } from '@dynatrace/barista-components/filter-field';

export function buildIdPathsFromFilters(filters: any[][]): string[] {
  return filters.map((path) =>
    path.reduce(
      (previousValue, currentValue) =>
        `${previousValue.name}${DELIMITER}${currentValue.name}${DELIMITER}`,
    ),
  );
}
```

Maybe @thomaspink can provide some insights on how to handle it for the filter-field.

**Comment by thomaspink** [comment]
The filter field [creates](https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/filter-field/src/filter-field-default-data-source.ts#L271) a `DtOptionDef` via the `dtGroupDef` [function](https://github.com/dynatrace-oss/barista/blob/f80a0ef32e090e5715f47f4e79f68384abb25a9a/libs/barista-components/filter-field/src/types.ts#L202). This function is called in the Datasource and can also take an `uid`. [Only if no `uid` is provided the function creates it's own id based on the name and path.](https://github.com/dynatrace-oss/barista/blob/f80a0ef32e090e5715f47f4e79f68384abb25a9a/libs/barista-components/filter-field/src/filter-field-util.ts#L426)
