### ISSUE TITLE
Edit async autocomplete option in filter field - stuck in loading-state

### ISSUE THREAD

**Issue by sandroschmid** [dynatrace-oss/barista#1666]
# Bug Report

## Expected Behavior

Normally, autocomplete filters in the filter field can be edited by clicking the tag (containing the filter name and previously selected option), which would show all filter options again and enable the user to select another option. We would expect to be able to edit the async autocompletes just like the normal ones.

## Current Behavior

When the autocomplete is async, the loading indicator is shown and never goes away anymore. The options are also not shown. To get back to an editable filter field the page has to be completely reloaded.

## Steps to Reproduce

1. Example at stackblitz: https://stackblitz.com/edit/barista-filter-field-async?file=src/filter-field/filter-field-async-example/filter-field-async-example.ts or even the Barista-example for async filter options: https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleFilterFieldAsync/ 
2. Click the filter field
3. Two async autocompletes are shown, select either one
4. Once the options are loaded, again pick one, e.g.:
![image](https://user-images.githubusercontent.com/18055485/94408124-a91cc080-0174-11eb-89a4-6fa7309d0cbc.png)
5. Click the added tag (not the remove-button on the right, but the label/value)
6. The loading indicator is shown and the filter field gets stuck in this state 
![image](https://user-images.githubusercontent.com/18055485/94408317-ea14d500-0174-11eb-975d-1a3dc4ac6e82.png)

You can also do the same for the non-async autocomplete in the example, this one will not get stuck but instead show the options.

## Context (Environment)

We load the filter options for each async autocomplete (of which we have several) from a REST-API endpoint using the `currentFilterChanges`-output. There we check whether the filter option is a async autocomplete, if yes the API is called and the response is processed just like in the example  for async options (https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleFilterFieldAsync/). Said example has the same issue, async options cannot be edited directly, instead they have to be removed and added anew. 

### Used Versions:

- **typescript**: ~3.8.3
- **angular**: 10
- **@angular/cdk**: 10.2.0
- **@dynatrace/barista-components**: 8.0.1

**Comment by ffriedl89** [comment]
Moved to internal issue tracking
