### ISSUE TITLE
[Filter field] How to display suggestion hints (no-data for suggestions, etc.)

### ISSUE THREAD

**Issue by danielkaneider** [dynatrace-oss/barista#1672]
# Feature Request

## Problem

There might be different situations, when the suggestions are not just a list of text entries.

1) When the async suggestions result in "No data", currently the UX is quite broken. There should be a hint displayed somehow.
![image](https://user-images.githubusercontent.com/1572080/94522200-8c918e80-022f-11eb-96bb-0be0747f04d2.png)

2) There should be hints to indicate, that the user is able to enter a free-text input, not just some empty text field

3) In the case async data can be combined with free-text, there should also be some sort of hint

4) In some cases the result of the suggestions will be one entry with "<no value>". How should this be displayed? And styled?

## Possible solution
A possibility is to outsource the behavior part to the consumer, by allowing suggestions to be styled as hints. Also the complete suggestion result, could indicate something like a "no-data" state. In other words, provide the styling in barista, leave the implementation up to the consumer.
Another possibility would be ofc, to also provide the/some behaviour part in the filter-field

**Comment by ffriedl89** [comment]
Currently not on our roadmap
