### ISSUE TITLE
Tree-table: Hovering on cells with "long" content change the width of the cell

### ISSUE THREAD

**Issue by Sherif-Elhefnawy** [dynatrace-oss/barista#1681]
# Bug Report

## Expected Behavior

The cell width shouldn't imo change width on hovering and then shrink back.

## Current Behavior

On hovering on a cell with "long" text, the width of the cell increases suddenly. And then on hovering on other cells with "short" text, the cell that was previously "expanded", shrinks back causing a jarring experience.

## Steps to Reproduce

https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleTreeTableDefault/

1. Expand first row in the example (hz.hzInstance_1_cluster.thread)
2. Hover over one of its children which have a long name
3. The cell with the longer name expands on hover and then shrinks after mouseout

### Used Versions:

- **node**: 
- **npm**: 
- **typescript**: 
- **angular**: 
- **@angular/cdk**: 
- **@dynatrace/barista-components**: 

## Attachments

![expandOnHover](https://user-images.githubusercontent.com/59170440/94834014-1f891f00-0410-11eb-9df1-36d54fa4482d.gif)

**Comment by lukasholzer** [comment]
Maybe introduced this bug with #1564 and #1626

**Comment by rowa-audil** [comment]
Yes, this needs a revert. 😅

**Comment by Sherif-Elhefnawy** [comment]
@lukasholzer or @rowa-audil , is this being worked on? :)

**Comment by lukasholzer** [comment]
It is the pipe with a high prio but not in progress. Due to our bug first policy we hopefully can tackle it soon. But if you want to contribute the fix, it would probably faster – so you are welcome :)

![image](https://user-images.githubusercontent.com/11156362/95167315-bc044600-07af-11eb-87e8-237c3b0bdee2.png)

**Comment by Sherif-Elhefnawy** [comment]
Ah cool, thanks for the update :)
