### ISSUE TITLE
[chart] loading indicator does not disappear after setting empty series data array

### ISSUE THREAD

**Issue by tkaiser** [dynatrace-oss/barista#1709]
# Bug Report

## Expected Behavior
When loading chart data, sometimes the result will be empty. In that case, I expect the loading indicator to disappear as well (as when setting non-empty data).

## Current Behavior
Loading indicator only disappear when setting some series data, not when passing an empty array.

## Steps to Reproduce

[Stackblitz here](https://stackblitz.com/github/nbwiyvgon?file=src/chart/chart-loading-example/chart-loading-example.ts) , adapted from the [chart loading example](https://barista.dynatrace.com/components/chart#loading-state). 
1. Click the "toggle data" button. The loading indicator will disappear correctly.
2. Click "set loading" to get the loading indicator back.
3. Click "toggle empty data". The loading indicator will stay!

## Context (Environment)

Even though the empty state should be handled by removing the chart from view and showing an empty state thingy, the chart should handle this case properly in my opinion.

### Used Versions:

- **@dynatrace/barista-components**: ^7.6.0

**Comment by tomheller** [comment]
Hi @tkaiser!

I'm having a hard time to fine the _set loading_ button in your example. Barista components are now on version 8.1.1. Can you confirm that this issue still exists in the new version (if you are able to upgrade).

**Comment by ffriedl89** [comment]
Closed - cannot reproduce
