### ISSUE TITLE
[combobox] change detection error

### ISSUE THREAD

**Issue by tkaiser** [dynatrace-oss/barista#1715]
# Bug Report

a change detection error is shown in the browser console when loading (any?) page containing a dt-combobox.

```
core.js:6241 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'attr.aria-selected': 'false'. Current value: 'true'.
    at throwErrorIfNoChangesMode (core.js:8160)
    at bindingUpdated (core.js:20149)
    at ɵɵattribute (core.js:20228)
    at DtOption_HostBindings (dynatrace-barista-components-core.js:2022)
    at setHostBindingsByExecutingExpandoInstructions (core.js:11678)
```

## Steps to Reproduce

[Stackblitz from the first combobox example in the docs](https://mklirgbzg.github.stackblitz.io)

**Comment by lukasholzer** [comment]
Hey thank you very much for reporting this issue 👍 

Would you like to contribute the fix to the component? 
Please keep in mind that this component is still experimental and should not be used in production (at least only behind a feature flag)!

**Comment by ffriedl89** [comment]
It might be related to an issue raised yesterday. Currently the example https://stackblitz.com/edit/github-nddgfv?file=src/combobox/combobox-simple-example/combobox-simple-example.ts is broken. If you filter for a value and try to click the option - the previous value is restored.

**Comment by ffriedl89** [comment]
Moved to internal issue tracking
