### ISSUE TITLE
[schematics] One schematic to run them all.

### ISSUE THREAD

**Issue by bardosmisi** [dynatrace-oss/barista#1726]
In the NX workspace, we have 4 schematics. 

dt-component
dt-component-dev
dt-component-e2e
dt-component-example

Running these schematics ideally could provide a clean component ready for the logic and other implementation inside it. It would be really cool if we did not have to run all four of these, bt only one command, and that internally would chain the 4 above. That would make contributing new compoenents more easy in the future.

I have tried to implement this in #889 , but there were problems with the chaining of the schematics, the file generation from templates did not work in imported schemtics.

**Comment by ffriedl89** [comment]
Moved
