### ISSUE TITLE
When expanding table rows programatically, other rows are not collapsing

### ISSUE THREAD

**Issue by anntr** [dynatrace-oss/barista#1734]
# Bug Report

When table `multiExpand` property is set to **false** and row is expanded through `expand` property, other rows are not collapsing. 

## Expected Behavior

Other rows should collapse (same as when user triggers expand action through click)

## Current Behavior

Other rows are not collapsing, multiple rows are expanded

## Steps to reproduce 
https://stackblitz.com/edit/github-h6nifb-brmne5

1. Expand first row by click on chevron button - other rows are collapsing 
2. Expand second row by click on 'Expand row # 2' button  - other rows are **not** collapsing

## Possible Solution

Seems that [`_expansionDispatcher.notify`](https://github.com/dynatrace-oss/barista/blob/c4445180f1803e1d4fe6300127500735fd14adcb/libs/barista-components/table/src/expandable/expandable-row.ts#L258) is only called when user expands the row. It should also be called in [`expand()`](https://github.com/dynatrace-oss/barista/blob/c4445180f1803e1d4fe6300127500735fd14adcb/libs/barista-components/table/src/expandable/expandable-row.ts#L231). 

I have fixed this locally, I can prepare a PR with the fix. 

### Used Versions:
- **@dynatrace/barista-components**: 8.1.0

**Comment by tomheller** [comment]
Hi @anntr!
This does not seem like a bug. Even with the multiexpand set to false, if you set multiple `expand` values on the datasource to true, the multiexpand will not _try to be smart_, and will expand all rows that you have set `expanded=true` on.

In the stackblitz you have provided, you are calling the expand row function when a button is clicked.

```ts
  expandRow(index) {
    const i = index - 1;
    const data = [...this.dataSource.value];
    data[i].expanded = true;
    this.dataSource.next(data);
  }
```
 
You are accessing `this.dataSource.value`, which is always the current state of the data. When you click all three buttons, the datasource value will look like this:

```json
[
  {
    "host": "host #1",
    "expanded": true
  },
  {
    "host": "host #2",
    "expanded": true
  },
  {
    "host": "host #3",
    "expanded": true
  }
]
```

As stated above, the multiExpand property will not try and override a users/consumers decision to expand a row. 
When changing the expandRow code to the following, it will work as you have expected.

```ts
  expandRow(index) {
    const i = index - 1;
    const data = [...this.dataSource.value];
    data
      .filter((d) => d.expanded)
      .forEach((d) => d.expanded = false);
    data[i].expanded = true;
    this.dataSource.next(data);
  }
```
