### ISSUE TITLE
Quickfilter "view more" shows empty options list

### ISSUE THREAD

**Issue by hubert-grininger** [dynatrace-oss/barista#1742]
# Bug Report

## Expected Behavior

The Quick Filter component should show the full list of options when a user click "view more". Unfortunately it doesn't seem to work for us. After clicking "View more" an empty area is shown instead of the full list.

## Steps to Reproduce

See this example: https://stackblitz.com/edit/github-rfmxpj-qobwna?file=src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts

### Used Versions:

8.1.2

**Comment by hubert-grininger** [comment]
Seems like the override of the datasource is the cause. We also tried to set the data field rather than creating a new datasource object. This doesn't work at all though.

**Comment by hubert-grininger** [comment]
As discussed with Rowa, the problems is fixed when the component initially doesn't set the datasource to an empty object and if the quick-filter component is only rendered when the dataSource is set:

```
<ng-container *ngIf="_dataSource">
  <dt-quick-filter...></dt-quick-filter>
</ng-container>
```

**Comment by rowa-audil** [comment]
Further investigation before closing this issue.
This might be an internal problem
