### ISSUE TITLE
[quick-filter] free-text input is not added in the filter bar

### ISSUE THREAD

**Issue by giordy** [dynatrace-oss/barista#1775]
# Bug Report

## Expected Behavior

When inserting a free-text filter and hitting "enter", I would expect the filter to be added in the list as it happens with other filters or with filter-field.

## Current Behavior

The input text filter disappears.
However when subscribing to `filterChanges`, I noticed that the data is submitted correctly.

## Steps to Reproduce

1. Open https://stackblitz.com/edit/github-cshctk
2. Select the "Text" filter and input free-text
3. Press enter

## Context (Environment)

We're currently planning to use Quick Filter to replace Filter Field to make filters more explicit in at least one place.

### Used Versions:

- **typescript**: 3.8.3
- **angular**: 10.2.0
- **@angular/cdk**: 10.2.6
- **@dynatrace/barista-components**: 8.2.0

## Attachments

Expected Behavior:

![filterfield](https://user-images.githubusercontent.com/6016950/97583152-e932c580-19f6-11eb-9c4e-2ed9a9a2e6e2.gif)

Actual Behavior:

![quick-filter](https://user-images.githubusercontent.com/6016950/97583035-c1436200-19f6-11eb-9337-542177bdff69.gif)

**Comment by ffriedl89** [comment]
Thx for the issue @giordy. We are on it.

**Comment by lukasholzer** [comment]
Moved to APM-266046
