### ISSUE TITLE
Filter Field not emitting expected event

### ISSUE THREAD

**Issue by SaraDavilaMendez** [dynatrace-oss/barista#1819]
# Bug Report

## Expected Behavior
Normally, in the filter field when you remove a filter and its option by clicking on the X, it emits the "filterChanges" event.
But when you remove the filter option by clicking on it (as if you would like to change it), but then instead of selecting a new option you press the "Backspace" keyboard, then the filter is removed (same result as when clicking on the X), but a "currentFilterChanges" event is emitted. What I expect to happen is that a "fiterChanges" event should be emitted if the user goes this path to remove a filter.

## Current Behavior

The filter field is just emitting "currentFilterChanges" event.

## Possible Solution

Add a cash that saves the previous filter and the removed filter and if they are the same then emit a "fiterChanges" event.

## Steps to Reproduce

1. Go to this [page ](https://stackblitz.com/edit/github-n8rpnq?file=src%2Ffilter-field%2Ffilter-field-distinct-example%2Ffilter-field-distinct-example.ts) 
2. Open the "Inspect" Tool
3. Go to the Console tab and clear it.
4. Click on the X to remove the hole filter:
![image](https://user-images.githubusercontent.com/16416038/99360143-70fe4800-28b0-11eb-8fee-63964ee67013.png)

5. See what event was emitted in the console and the state of the filter field
![image](https://user-images.githubusercontent.com/16416038/99360219-8d01e980-28b0-11eb-85ac-71cc68ee66bc.png)
![image](https://user-images.githubusercontent.com/16416038/99360296-a7d45e00-28b0-11eb-8f12-4282aa8c431e.png)

6. Reload the page and clear the console again.
![image](https://user-images.githubusercontent.com/16416038/99360790-67c1ab00-28b1-11eb-9fa0-cf22307ec517.png)

7. Click on "Vienna" and then press the "backspace" key in the keyboard and see the console out put
![image](https://user-images.githubusercontent.com/16416038/99360602-24ffd300-28b1-11eb-9d55-0bb7fad41156.png)
![image](https://user-images.githubusercontent.com/16416038/99360620-2d580e00-28b1-11eb-96a8-8efe810a7a59.png)
![image](https://user-images.githubusercontent.com/16416038/99360697-46f95580-28b1-11eb-99c5-386047797650.png)
![image](https://user-images.githubusercontent.com/16416038/99360975-afe0cd80-28b1-11eb-8678-31fb82cef8aa.png)

## Context (Environment)

This issue caused that request were not called because we were expecting it to emit this event to reload the table content.

### Used Versions:

- **node**: v12.15.0
- **npm**: 6.14.5
- **typescript**: 3.9.7
- **angular**: 10.0.5
- **@angular/cdk**: 10.2.6
- **@dynatrace/barista-components**: 8.2.0

**Comment by lukasholzer** [comment]
Moved to internal Jira APM-268757
