### ISSUE TITLE
Inner expandable in a nested expandable does not reflect expanded state

### ISSUE THREAD

**Issue by bugaandreea** [dynatrace-oss/barista#1870]
### **Bug Report**

**Expected Behavior**
The expandable section arrow should reflect the expanded state of the section.

**Current Behavior**
When using a nested expandable, the inner expandable arrow does not reflect the state of the section, but it rather always shows that it is in an expanded state.

**Steps to Reproduce**
Have a screen that includes nested expandable sections. Try to expand/collapse the inner expandable, its arrow will always indicate that this expandable section is open.

**Used Versions:**
"@dynatrace/barista-components": "^8.6.0",
"@angular/core": "^10.2.0",
"@angular/cdk": "^10.2.6",

**References**
StackBlitz link of the reproduced issue: https://rlmiblbom.github.stackblitz.io/

**Comment by tomheller** [comment]
Moved to APM-273280.

For future issue creations, please read #1786
