### ISSUE TITLE
Stacked series chart component should be able to make the whole stack selectable not just the node

### ISSUE THREAD

**Issue by dani7cl** [dynatrace-oss/barista#1889]
**Description**
This feature has been requested for Dynatrace User Session APM-252687 task. There should be an option to make the stacked series chart component selectable by the whole stack instead of just by node.

**Actual behaviour**
[https://gyazo.com/9bf2e43a013ac2a7dbece5f85f129238](https://gyazo.com/9bf2e43a013ac2a7dbece5f85f129238)

**Expected behaviour**
[https://gyazo.com/6d5d0ffc349ec64b47f2579cf2f109f0](https://gyazo.com/6d5d0ffc349ec64b47f2579cf2f109f0)

**Comment by tomheller** [comment]
Moved to internal issue tracking APM-276087
