### ISSUE TITLE
Fail tests if test coverage is below a threshold in component library

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#189]
#### - <strong>Summary</strong>

It would be nice if we could add a coverage threshold to our tests so that they are passing for certain folders. Even if the threshold would not be high we could ensure a higher quality.

#### - <strong>Feature Description</strong>

So components like a stepper without tests or with poor test coverage would fail on ci.

I know test coverage is not all but it is a good way to ensure further quality – where humans tend to forget or not think about to test the code.

- Solutions: 
Jest would provide a way to fail the tests for specific folders or files if they don't pass the threshold. 

https://jestjs.io/docs/en/configuration#coveragethreshold-object

```js
// jest.config.js
"coverageThreshold": {
      "global": {
        "branches": 50,
        "functions": 50,
        "lines": 50,
        "statements": 50
      },
      "./src/components/": {
        "branches": 40,
        "statements": 40
      },
      "./src/reducers/**/*.js": {
        "statements": 90
      },
      "./src/api/very-important-module.js": {
        "branches": 100,
        "functions": 100,
        "lines": 100,
        "statements": 100
      }
    }
```

**Comment by tomheller** [comment]
Can we definitely determine if the test coverage drops to a certain point, with the way that we build incrementally and only affected, @lukasholzer ?
