### ISSUE TITLE
Radial chart legend percentages

### ISSUE THREAD

**Issue by tonidalmases** [dynatrace-oss/barista#1959]
# Bug Report

## Expected Behavior

When using the radial chart with percentages, without _Max value_ (full chart), the sum of percentages in the legend should be equal to 100%.

## Current Behavior

In some occasions, the sum is not equal to 100, since the chart does not consider a precision, nor rounded percentages.

The current behavior (the sum is equal to 99.98)
![imagen](https://user-images.githubusercontent.com/27827642/107201905-dbc7a700-69f9-11eb-84d4-d922f97be927.png)

## Possible Solution

Adding `precision` to the chart would fix the number of decimals to display in the legend.
![imagen](https://user-images.githubusercontent.com/27827642/107202685-c010d080-69fa-11eb-9f56-404ef388217a.png)

However, note that the sum would be equal to 99.9, since those percentages are not rounded to 100. A possible implementation, described [Here](https://revs.runtime-revolution.com/getting-100-with-rounded-percentages-273ffa70252b), would also solve the issue by distributing the percentages in a way that the final result is equal to 100.
![imagen](https://user-images.githubusercontent.com/27827642/107202932-0b2ae380-69fb-11eb-84a0-078b730d15f1.png)

## Steps to Reproduce

https://stackblitz.com/edit/github-xzqveu?file=src/radial-chart/radial-chart-overlay-example/radial-chart-overlay-example.ts

Issue also described in APM-277510.

This issue is extensive to all kind of charts in barista whose percentages must sum up 100%.

### Used Versions:

- **typescript**: 3.8.3
- **angular**: 11
- **@angular/cdk**: 11.1.0
- **@dynatrace/barista-components**: 9.0.0-rc.3

**Comment by tomheller** [comment]
Hi @tonidalmases! We are no longer tracking issues here in github. please read #1786 and reopen the ticket in Jira.
