### ISSUE TITLE
Slider: Implement component in the library

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#204]
# Feature Request

## Summary

I want to have a slider component as part of the @dynatrace/barista-components

## Feature Description

You can find the ux specs on https://barista.dynatrace.com/components/slider/
Check whether the cdk as something we can reuse.

**Comment by bardosmisi** [comment]
# API Proposal DtSlider
The Slider essentially works as the html range element. It does consider accessibility and usability, while it does not use html range element itself. It also contains an input-field, which has its value in sync with the slider.
## basic structure
```
<dt-slider
  value="50"
  minValue="0"
  maxValue="100"
  label="Duration"
  inputLabel="sec"
  id="example-slider"
  ></dt-slider>
```
## inputs
***value:* number** the value with which the slider should be initialized

***minValue:* number** the minimum value that the slider can hold, the left end of the slider track

***maxValue:* number** the maximum value that he slider can hold, the right end of the slider track

***label:* string** the label for the slider

***inputLabel:* string** the label for the input field inside the component

***id:* string** the id of the input field element inside the component

***step:* number** essentially the difference between the possible values
## outputs
**_valueChanged_**: **`<EventEmitter>`**  emits an event with the new value of the slider

## additional requirements

- [ ] proper keyboard support (arrow: right left up down; home, end, page up, page down)
- [ ] WAI-ARIA
- [ ] consider the option to allow the component to be rendered without the input field
- [ ] consider compatibility with `dtInput`
- [ ] consider validation

## sources:
* https://www.w3.org/TR/wai-aria-practices/#slider
* https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-2.html
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by tomheller** [comment]
Hi @bardosmisi! Thank you for this proposal.
Here are a couple of thoughts we could discuss:

> inputLabel: string the label for the input field inside the component 

Could we create a directive that can be set to a component and is being rendered via `ng-content`, i.e. like we have it in the empty state.
https://github.com/dynatrace-oss/barista/blob/fa6d6952b27efa02b7fda72770a155ab45f12e45/components/empty-state/src/empty-state.ts#L93-L107 https://github.com/dynatrace-oss/barista/blob/fa6d6952b27efa02b7fda72770a155ab45f12e45/components/empty-state/src/empty-state-item.html#L13-L15
This way we do not constrain ourselves to only string inputs and open the api to potential styling modifications (bolds, colors, ...). 

---

> id: string the id of the input field element inside the component

I think we can lose the id here as a public member, we can keep track of it internally, as we do with the radios: 
https://github.com/dynatrace-oss/barista/blob/fa6d6952b27efa02b7fda72770a155ab45f12e45/components/radio/src/radio.ts#L46 https://github.com/dynatrace-oss/barista/blob/fa6d6952b27efa02b7fda72770a155ab45f12e45/components/radio/src/radio.ts#L71

---

> setDisabled: boolean set the component to be disabled based on the provided

I think we can omit this member function, as you can programmatically also access the disabled property on the instance. 

---

> getValue: () => value returns the current value of the slider component

I think we can omit this member function, as you can programmatically also access the value property on the instance.

## Additionals:

You might also think about the compatibility with ngForms module. This requires you the implement a couple of member functions, that come with the

**Comment by thomaspink** [comment]
aside from toms feedback i would suggest to name it `min` and `max` to be consistent with other components.

@tomheller for the id, i would also accept ids from the consumer, only if non is provided fall back to a generated one.

**Comment by tomheller** [comment]
> @tomheller for the id, i would also accept ids from the consumer, only if non is provided fall back to a generated one.

But for what reason would I need to set a specific ID on the input element other than defining it, to be able to access it in the DOM?

**Comment by bardosmisi** [comment]
@tomheller , @thomaspink 
After taking another look at content projection, should we consider using content projection for the input field as well?

**Comment by tomheller** [comment]
@bardosmisi I don't think that this would be a good idea. There is probably a tight coupling between the input field and the slider (in regards to state changes, values, ect ...). I'd rather opt for an internal input field that can be toggled via an input. That way we can keep the communication between the slider and the input internal and can be sure of certain things like input type.

**Comment by rarenal** [comment]
I would expect something easy and fast to create, like:
```
<dt-slider (change)="updateValue($event)"
    [value]="value"
    [max]="50">
    Duration
</dt-slider>
```
But also flexible, for more complex cases, like specifying the unit for the slider value (ms, degrees, minutes...)
```
<dt-slider (change)="updateValue($event)"
    [value]="value"
    [min]="20"
    [max]="50">
    <dt-label>Duration</dt-label> // slider label
    <dt-unit>ms</dt-unit> // slider value unit
</dt-slider>
```

**Comment by tomheller** [comment]
@rarenal it seems like your first example matches quite well with what @bardosmisi described. When including the changes that @thomaspink requested in
> aside from toms feedback i would suggest to name it `min` and `max` to be consistent with other components.

@bardosmisi could we modify your apiProposal post to match the requests? I would also opt to rename the `valueChange` output to `change` to be consistent with other parts of the library. 

@rarenal Can you share an example why you would need to pass a unit into this one?
I would also opt for using the default ng-content for the label, and not having two versions of how to set a label:

```html
<dt-slider (change)="updateValue($event)"
    [value]="value"
    [min]="20"
    [max]="50">
    <dt-slider-unit>ms</dt-slider-unit> // slider value unit
    Duration
</dt-slider>
```

**Comment by bardosmisi** [comment]
Updated based on comments above.
