### ISSUE TITLE
Opt-in / Opt-out component design

### ISSUE THREAD

**Issue by karolinawronska** [dynatrace-oss/barista#2073]
# **Feature Request**

## **Summary**
I created unified Opt-in & Opt-out component with an additional feedback option.

## **Feature Description**
We're seeing a big number of opt-in/out components, where every single one of them is different not only visually, but also functionally.

What situation we're dealing with here, are two case scenarios:
a) change in the whole page,
b) change in a standalone component.

What we need is to provide two versions for one solution. This component should have following attributes:
a) Clear information what the switch is used for,
b) Switch from current to new version,
c) possibility to hide the component,
d) optional, but recommended - feedback form button, preferably with 'what do you like?' & 'why did you switched back?'.

**Expectations** (how does it work, how interactions work, notifications if any, etc.)

a) Component always have a title that tells what has been changed/what new has happened (short explanation for the user).
b) Component doesn't have to have a short description - title should be self explanatory. Description is needed in special cases, as decided with the PM.
c) Toggle, depending on the intention, is on/off. Usually, when we want to introduce users a new version of something, it should be off. Whenever they switch on, feedback form (if included, but we strongly recommend having it) should appear on the left side of the toggle. 
c) Feedback form preferably should have two versions - one for giving feedback for a new change, and one for giving a reason why user switched back.
d) If user wants to hide the component, on the right top corner there is a close button. When user is clicking it, (depending on a use case) this component should either be gone for some time, forever, or be moved to the bottom of the page (like in example).

As mentioned before, there are two states for this component:
1. One element changed
Example in the attachment, as it was provided by other designer before, Arkadiusz Lipiarz. This solution was already tested so it doesn't require further testing for now. Please follow these expectations:
- "x" is unnecessary in this case
- the survey button has two states: tell us what you think about the redesign and the second one, why did you chose to switch back
- a toggle is indicating that you can go back and forth with new/old version

2. Whole page changed
Example is provided in the attachment with the same behaviour. The only difference is a placement on the page, where we are telling that the whole page is redesigned.

## **Attachments**
I don't know if svg files are also needed, there was already APM ticket for it: https://dev-jira.dynatrace.org/browse/APM-259874

![Screenshot 2020-10-05 at 13 46 58](https://user-images.githubusercontent.com/21307061/115254967-24a08800-a12e-11eb-8060-a2a40e546b26.png)
<img width="1666" alt="Screenshot 2021-02-16 at 09 38 18" src="https://user-images.githubusercontent.com/21307061/115254978-25d1b500-a12e-11eb-9b07-f34e1c963a45.png">
<img width="1666" alt="Screenshot 2021-02-16 at 09 38 46" src="https://user-images.githubusercontent.com/21307061/115254986-279b7880-a12e-11eb-8782-a8f1084a5261.png">

Thank you and all the best!

**Comment by tomheller** [comment]
@karolinawronska thank you for request.
Moved to internal issue tracking as per #1786

New ticket key: APM-297750
