### ISSUE TITLE
Providing a custom Template to the DtChartTooltip

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#224]
# Feature Request

## Summary

Currently, it is hard to extend from the `DtChartTooltip` in case that we are using a `@ContentChild(TemplateRef, { static: false })` for selecting the template. 

## Feature Description

It would be nice to open the API of the overlay to provide a way how the consumer can extend it without providing an own version of the overlay that is hard to maintain.
We could leverage the `ngTemplateOutlet` to provide a more generic way to integrate external content 

### Solution

The inputs and contentChildrens
```typescript
@Input() overlayTemplate: TemplateRef<OverlayContext>;
@ContentChild(TemplateRef, {static: false}) templateFromContent: TemplateRef<OverlayContext>;
```

In the component template
```html
<ng-template #fallbackTemplate let-values="values">...</ng-template>
<ng-template
  [ngTemplateOutlet]="overlayTemplate || templateFromContent || fallbackTemplate"
  [ngTemplateOutletContext]="context">
</ng-template>
```

**Comment by lukasholzer** [comment]
@thomaspink  @ffriedl89 @tomheller please provide your opinions :)

**Comment by thomaspink** [comment]
Can you give an example that shows what the benefit would be (e.g. what improvement the consumer would have)
