### ISSUE TITLE
Chart Data Export to CSV

### ISSUE THREAD

**Issue by dani7cl** [dynatrace-oss/barista#2447]
# Feature Request

## Summary

Internal ticket APM-354937 asks for Chart Data to be exported to CSV

## Feature Description
Provide a public function or some kind of mechanism where you can trigger a downloadCSV action which will return a CSV file with the data that you have in the chart.

We already did some implementation on top of it doing this and we considered it would be more accurate for that code to be on the barista dt-chart so it can be reused. What do you guys think?

Preconditions:
These Highcharts modules need to be loaded https://www.highcharts.com/docs/export-module/export-module-overview

## Attachments
![image](https://user-images.githubusercontent.com/15110589/158831438-e9913a32-3f11-46e1-b980-bc24088ef277.png)

If you agree on it we will proceed to create a PR

**Comment by LucasHocker** [comment]
Just an FYI:
DashboardPowerups (https://github.com/dynatrace-oss/DynatraceDashboardPowerups) has been loading the HighCharts export module for 1-2 years without issue. Should be pretty safe to load into Barista but might need some styling to meet Product standards.
![Screen Shot 2022-03-28 at 11 04 09 AM](https://user-images.githubusercontent.com/34926264/160440072-04b9e61d-cdc5-4f5c-82c2-6e40d95decc6.png)
![Screen Shot 2022-03-28 at 11 03 48 AM](https://user-images.githubusercontent.com/34926264/160440075-cd759da3-8bbd-4b39-a4bb-b627540ee5f2.png)
