### ISSUE TITLE
Create experimental package

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#254]
# Feature Request

Currently it can feel a bit slow to get new things into the library. To not block features until an api is stable enough we want to have an experimental package that is shipped in a separate npm package that does not follow semantic versioning

**Comment by ffriedl89** [comment]
We still need this to ship the quickfilter since this component won't be stable initially. The API surface is too big and we need to get feedback from product teams.

**Comment by tomheller** [comment]
To skip the complicated npm publishing and pipeline steps, I think it would be better to not publish it's own npm experimental package. We probably can ship an experimental part within the library and mark the component / api as unstable.
