### ISSUE TITLE
Legend: Fix incompatibility with Angular's ivy renderer

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#26]
Since we upgraded to angular version 8.2.12, I tried to build app with enabled Ivy to see how much needs to be done.

I found it tries to compile Angular Components modules and breaks on `dt-legend` with message:
```
ERROR in Cannot combine @Input decorators with query decorators
```
Googling it a bit and it looks we cannot use `@Input()` and `@ContentChild()` on one class field at once. I found in codebase following place where it should be fixed:
legend-item.ts#56-58

Fixing this issue would help us further investigation on Ivy upgrade.

**Comment by pieniazek** [comment]
Hi @ffriedl89 - any update on this issue? Still occurring with Angular@9.0.0-rc12. 
Removing 
`@Input()` from `_overlayTemplateRef` allows us to continue with Ivy compilation

**Comment by pieniazek** [comment]
We've been able to successfully compile Cluster UI by removing text selected on the screenshot below
![image](https://user-images.githubusercontent.com/17014590/73594183-20c61d00-450c-11ea-91ed-36c6249c0957.png)
from node_modules/@dynatrace/barista-components/fesm2015/dynatrace-barista-components-legend.js:116

**Comment by piotrl** [comment]
Thanks! It'll help us greatly with migration progress
