### ISSUE TITLE
Installation error with Angular version 15

### ISSUE THREAD

**Issue by technbuzz** [dynatrace-oss/barista#2635]
I am trying to install the components but it's clashing with Angular animation version as shown below

![image](https://user-images.githubusercontent.com/1523391/210353602-c548c51a-e1ea-4f09-b679-7ffe22723a7d.png)

Although `--legacy-peer-deps` works but I thought it's worth mention.

**Comment by tomheller** [comment]
We currently do not yet support Angular version 15. 
Also, please note that issue tracking has moved to our internal issue tracking, see #1786
