### ISSUE TITLE
Chart Range: Close the selection programatically

### ISSUE THREAD

**Issue by GustavAT** [dynatrace-oss/barista#276]
### Feature Request
The selection-area cannot be removed other than clicking on the close-button in the selection-overlay.
There should be a way to close the selection from the code.

#### Possible Solution
Remove the selection when assigning the default timeframe `[0, 0]`
```typescript
this.chartRange.value = [0, 0]
```

**Comment by ffriedl89** [comment]
I'd suggest a `close` method that can be called on the range and the timestamp respectively? @lukasholzer what do you think?

**Comment by lukasholzer** [comment]
the close method should call the reset method: 
https://github.com/dynatrace-oss/barista/blob/master/components/chart/src/range/range.ts#L324

**Comment by dovidio** [comment]
I will take this
