### ISSUE TITLE
Dt-Drawer has strange 20px padding

### ISSUE THREAD

**Issue by FireDragonGameStudio** [dynatrace-oss/barista#277]
# Bug Report

Hi, when working with the Dt-Drawer component, a strange 20px padding appears. (using the code from the documentation)

## Expected Behavior

Referring to the barista documentation [https://barista.dynatrace.com/components/menu#menu-in-use](https://barista.dynatrace.com/components/menu#menu-in-use) the drawer should look like this: 

![grafik](https://user-images.githubusercontent.com/23502690/70131811-3b525600-1683-11ea-861c-c666fca2d078.png)

## Current Behavior

But when I use the example from the documentation I usually get this:

![grafik](https://user-images.githubusercontent.com/23502690/70131867-545b0700-1683-11ea-897f-e2b67552cc38.png)

## Steps to Reproduce

Use the code from the documentation (e.g. menu in use) somewhere.

### Used Versions:

- **node**: v10.15.0
- **npm**: 6.10.3
- **typescript**: 3.1
- **angular**: 8.1.3
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 4.15.0
- **OS**: win32 x64

Best regards :)

**Comment by ffriedl89** [comment]
Thanks again for reaching out. I suspect you want to use the drawer with a menu as your navigation for the app. We built exactly that but it hasn't found its way into the design system yet. 
Please see https://github.com/dynatrace-oss/barista/tree/master/components/drawer#sidenav for documentation on the sidenav usage. If you need more help please reach out again, but i'll close the issue for now
