### ISSUE TITLE
Dt-Info-Group usage in cards doesn't show up as grid

### ISSUE THREAD

**Issue by FireDragonGameStudio** [dynatrace-oss/barista#278]
# Bug Report

Hi, using the Dt-Info-Group within a card, doesn't result in a info group grid. ([https://barista.dynatrace.com/components/info-group#info-groups-in-use](https://barista.dynatrace.com/components/info-group#info-groups-in-use))

## Expected Behavior

According to the documentation it should look like this (used code is placed after the screenshot):

![grafik](https://user-images.githubusercontent.com/23502690/70134295-13b1bc80-1688-11ea-8d69-cdff25d38f7a.png)

```
  <dt-card dtTheme="purple">
      <div class="dt-card-grid">
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="timemeasurement"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>5 min 30 s</dt-info-group-title>
          Session duration
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="user-uem"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>ben</dt-info-group-title>
          User identifier
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="application"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>easyTravel Protal</dt-info-group-title>
          Application name
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="finishflag"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>2</dt-info-group-title>
          Conversation goals
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="realuser-monitorwebsiteusers"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>Satisfied</dt-info-group-title>
          User experience score
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="incident"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>2</dt-info-group-title>
          Errors and annoyances
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="ios"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>OS X El Capitan 10.1</dt-info-group-title>
          Operating system
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="desktop"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>1280x768px</dt-info-group-title>
          Screen size
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="webpages"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>Chrome 70</dt-info-group-title>
          Browser
        </dt-info-group>
        <dt-info-group>
          <dt-info-group-icon><dt-icon name="pinpoint-location"></dt-icon></dt-info-group-icon>
          <dt-info-group-title>Rome, Italy</dt-info-group-title>
          Geo location
        </dt-info-group>
      </div>
    </dt-card>
```

## Current Behavior

But actually it looks like this:

![grafik](https://user-images.githubusercontent.com/23502690/70134555-a5212e80-1688-11ea-8776-610722d93c1d.png)

## Steps to Reproduce

Place the used code somewhere.

### Used Versions:

- **node**: v10.15.0
- **npm**: 6.10.3
- **typescript**: 3.1
- **angular**: 8.1.3
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 4.15.0
- **OS**: win32 x64

Best regards :)

**Comment by ffriedl89** [comment]
Thank you for reporting this issue. This happens due to the styles that are not yet shown in the barista demos. You can find the grid used in the example in https://github.com/dynatrace-oss/barista/blob/master/libs/examples/src/info-group/info-group-in-card-example/info-group-in-card-example.scss

Note that our components can be used in any layout, we differentiate between block and inline elements. Our components don't align themselves but can be used in a flexbox or grid layout for instance.
