### ISSUE TITLE
Dt-Tag is not colored in an optimal way, when using dark mode

### ISSUE THREAD

**Issue by FireDragonGameStudio** [dynatrace-oss/barista#279]
# Bug Report

Hi, when working with the Dt-Card and Dt-Tag components, the coloring of the Dt-Tag is not optimal when used with dark mode.

## Expected Behavior

Dt-Tags in dark mode should look something like this:

![grafik](https://user-images.githubusercontent.com/23502690/70137851-3a272600-168f-11ea-810e-498fe9546792.png)

## Current Behavior

But currently they are not really readable:

![grafik](https://user-images.githubusercontent.com/23502690/70137830-2a0f4680-168f-11ea-895f-97f4d58b2712.png)

## Steps to Reproduce

Here is the code block I used:

```
  <div dtTheme="dark">
    <dt-card>
      <dt-card-icon>
        <dt-icon name="host"></dt-icon>
      </dt-card-icon>
      <dt-card-title>Host</dt-card-title>
      <dt-tag-list aria-label="test">
        <dt-tag>window</dt-tag>
        <dt-tag>deploy</dt-tag>
        <dt-tag>.NetTest</dt-tag>
        <dt-tag>193.168.4.3:80</dt-tag>
        <dt-tag><dt-tag-key>Maxk</dt-tag-key>loadtest</dt-tag>
        <dt-tag>sdk-showroom</dt-tag>
        <dt-tag>dt</dt-tag>
        <dt-tag>requests</dt-tag>
        <dt-tag>cluster</dt-tag>
        <dt-tag>server</dt-tag>
        <dt-tag>node</dt-tag>
      </dt-tag-list>
    </dt-card>
  </div>
```

### Used Versions:

- **node**: v10.15.0
- **npm**: 6.10.3
- **typescript**: 3.1
- **angular**: 8.1.3
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 4.15.0
- **OS**: win32 x64

Best regards :)

**Comment by tomheller** [comment]
`dtTheme=':dark'` definition needs a `:` in front of it to be picked up. Tested with the following template code, which yielded the below expected result.

```html
<div class="dt-example-dark" dtTheme=":dark" style="color: #fff;">
  <dt-tag-list>
    <dt-tag
      [removable]="true"
      [value]="value1"
      title="My custom tooltip"
    >
      <dt-tag-key *ngIf="hasKey">[AWS]OSType:</dt-tag-key>
      Windows
    </dt-tag>
    <dt-tag
      [removable]="true"
      [value]="value2"
      title="Another tooltip"
    >
      <dt-tag-key *ngIf="hasKey">[AWS]Category:</dt-tag-key>
      Managed
    </dt-tag>
  </dt-tag-list>
</div>
```

![image](https://user-images.githubusercontent.com/6338434/73527440-5804d300-4413-11ea-8b0c-839d613de848.png)
