### ISSUE TITLE
Button moves outside overlay at specific scroll & mouse position

### ISSUE THREAD

**Issue by myieye** [dynatrace-oss/barista#289]
# Bug Report

## Expected Behavior

An overlay should stay the same size regardless of scroll or mouse position

## Current Behavior

In an example in Barista at a specific combination of scrolling and mouse positioning the overlay resizes and the button moves half outside the overlay

## Steps to Reproduce

The window has to be scrolled just the right amount (see the image below)
https://barista.dynatrace.com/components/overlay#overlay-content

## Context (Environment)

This doesn't affect me at all at the moment.

## Attachments

![overlay-bug](https://user-images.githubusercontent.com/12587509/70217526-a2cedb00-1741-11ea-894c-476bc96694d1.gif)

**Comment by tomheller** [comment]
barista.dynatrace.org is still running version 4.15 of barista-components. This problem has been solved by version 5.
