### ISSUE TITLE
Filter Field: Freetext node is instantly submitted with ENTER

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#294]
# Bug Report

## Expected Behavior

When a freentext node is highlighted in the autocomplete and the user presses `ENTER` the cursor is placed inside the input field but the freetext is not submitted 

## Current Behavior

When a freetext node is highlighted in the autocomplete and the user presses `ENTER` the freetext is instantly submitted with an empty value and therefore an error message is shown for the freetext to be required.

## Possible Solution

Handle ENTER the same way as the click on the freetext node in the autocomplete. It's probably a event bubbling issue

## Steps to Reproduce

1. select a freetext node with the keyboard and press enter when highlighted

**Comment by tomheller** [comment]
Sorry for referencing the wrong issue in the event chart commit, this has now been removed in https://github.com/dynatrace-oss/barista/pull/394/commits/bb77e96fdd1cfcf14d7cdb512329fb267cc87d1d
