### ISSUE TITLE
Chart tooltip doesn't appear if chart is hovered as it is scrolled into view

### ISSUE THREAD

**Issue by myieye** [dynatrace-oss/barista#295]
# Bug Report

## Expected Behavior

When I hover over a chart with a tooltip, I expect a tooltip to be visible (unless maybe the chart is mostly hidden).

## Current Behavior

If I hover over a chart that is only partially visible (specifically < 90% visible as defined [here](https://github.com/dynatrace-oss/barista/blob/39eda2796ed83e6e5b53bedd9273e5c7b5fe162b/components/chart/src/chart.ts#L111)), then (by design) the tooltip doesn't appear. However, if I then scroll the remainder of the chart into view while keeping the mouse over the chart, the tooltip never appears.

Note1: Once the chart has been 90% visible, the tooltip will always display regardless of how visible it is. So, the threshold is no longer considered.

Note2: This problem does not occur on the Barista [chart examples page](https://barista.dynatrace.com/components/chart). Note1 also doesn't apply.

## Possible Solution

While not a solution to the root problem, 90% seems like a very high threshold to me. Reducing this would lessen the occurances of this bug and quite possible be more user friendly. My suggestion would be 50%, but maybe there are good reasons for 90%?

## Steps to Reproduce

(See gif below)

On the chart example page of the Barista dev app, with one of the charts only partially visible:

1) Hover over the chart
2) Scroll down while continuing to hover

## Possible Implementation

The problem lies in the [switchMap](https://github.com/dynatrace-oss/barista/blob/39eda2796ed83e6e5b53bedd9273e5c7b5fe162b/components/chart/src/chart.ts#L558), which doesn't emit after the chart comes into view and `_isInViewport$` is triggered.

## Attachments

![chart-tooltip-bug](https://user-images.githubusercontent.com/12587509/70234758-a5412d00-1761-11ea-9393-a587ea9eca65.gif)

**Comment by tomheller** [comment]
#410 removes the inViewport check altogether, as it caused multiple problems when syncing with the highcharts lifecycle and anyways resulted in unexpected behaviour for the user.
