### ISSUE TITLE
Event Chart breaks application when rendered with universal

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#302]
# Bug Report

## Expected Behavior

Event chart should not throw an error if it was rendered with universal

## Current Behavior

Currently, when my app uses an event chart. And I am using universal rendering it crashes my application.

![Screenshot 2019-12-06 at 09 41 00](https://user-images.githubusercontent.com/11156362/70308937-a3807380-180c-11ea-91f1-e0b83c9194f3.png)

## Possible Solution

Wrap the platform browser parts in the event chart in a platform check.

**Comment by tomheller** [comment]
Fixed by #337
