### ISSUE TITLE
Add reports for e2e and a11y tests

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#32]
Add test-cafe reporter to have an overview about the a11y and e2e tests

**Comment by tomheller** [comment]
Already done here:
https://github.com/dynatrace-oss/barista/blob/aa7f6483f09647ac94bf36e19ce685bedd2a39a8/.circleci/config.yml#L256-L257
https://github.com/dynatrace-oss/barista/blob/aa7f6483f09647ac94bf36e19ce685bedd2a39a8/.circleci/config.yml#L274-L275

Results in output like this: 
https://app.circleci.com/jobs/github/dynatrace-oss/barista/13619/tests
https://app.circleci.com/jobs/github/dynatrace-oss/barista/13611/tests

or failing:
https://app.circleci.com/jobs/github/dynatrace-oss/barista/13570/tests
