### ISSUE TITLE
Context dialog improvements

### ISSUE THREAD

**Issue by moarliman** [dynatrace-oss/barista#322]
# Feature Request

## Summary

A scrollable content section for the context dialog.

## Feature Description

Problem: If there is too much content in a context dialog the buttons on the bottom are not visible.

Solution: The dialog should have a max-height of about 90vh. A sticky footer section ensures, that the buttons are always visible. The content of the dialog must then be scrollable.
- [ ]  Extend api with a footer that is sticky
- [ ]  Add closing button on the top right corner besides the title. 
- [ ] Make the content section scrollable
- [ ] Provide a mechanism for the consumer to set the OverlayConfig used by the context dialog, keep in mind that this config includes things like width, height, ...

## Attachments

![image](https://user-images.githubusercontent.com/57876279/70542521-22f1a800-1b69-11ea-98c4-e658775de9aa.png)

![context-dialog-scrollable](https://user-images.githubusercontent.com/57876279/70542858-c17e0900-1b69-11ea-9c06-c36930b0ac81.jpg)

**Comment by ffriedl89** [comment]
Positioning seems to cause confusion or at least raises some questions due to it being different than in previous versions. @moarliman can we revisit this with user tests regarding positioning defaults?
