### ISSUE TITLE
Option to display tables based on table tag instead of div

### ISSUE THREAD

**Issue by NagRock** [dynatrace-oss/barista#326]
# Feature Request
An option to display tables based on `table` tag instead of `div`

## Summary
Option to be able to use tables based on `table` tag too

## Feature Description
I think it is worth to consider using `table` tag for table component to support `copy` / `paste` functionality from table component to for example `excel` spreadsheet on desktop.

**Comment by lukasholzer** [comment]
Can you explain the use case of the feature description more in detail, please? I cannot follow your explanation about the copy-paste of excel spreadsheets. 

Maybe you can provide a use case where we need this in our product.

**Comment by tomheller** [comment]
As far as I understand it, if the browser represents tables with a semantically correct `table` tag, it is possible to user-select the table and copy and pasting the values into a spreadsheet.

@NagRock As we are leveraging the CDK tables here, I'm not entirely certain that a switch on a per table-instance option is something that can be achieved easily. With a very feature heavy table, supporting two different markups would be quite the endeavour.

A potentially different solution I have come across is an additional button somewhere next to the table, that will let you copy the data presented in the table in various forms of machine readable code, i.e. CSV/JSON/...

Would this also serve your purpose or do you have other concerns about not using `table` elements.
