### ISSUE TITLE
Filter field: Allow quicker filtering for selected filter category

### ISSUE THREAD

**Issue by OFouda** [dynatrace-oss/barista#336]
## Summary
Allow immediate typing to filter by a specific filter group faster
## Feature Description

For some cases its often desirable to allow users to filter by specific filter category by simply typing into the filter field. 

For example if I have a list of entities that have 5 different attributes, including name, I would want to be able to immediately start typing in the filter bar then hit enter to filter by entities by their name.

This would be opposed to the current approach of first choosing the "Name" filter category, then type something in and click enter.

For this to work, consumers of the filter field would need to mark one of the filter categories as the one to be considered for free text filtering

**Comment by tomheller** [comment]
@ffriedl89 is this one related to #453 ?
