### ISSUE TITLE
DtOverlay: is now shown on buttons with [disabled] attribute in some browsers

### ISSUE THREAD

**Issue by bartoszbobin** [dynatrace-oss/barista#355]
# Bug Report

```
<button class="arrow left"
        type="button"
        [attr.disabled]="isPrevButtonDisabled"
        (click)="prev()"
        [dtOverlay]="overlayPrev"
        [dtOverlayConfig]="overlayConfig">
  <dt-icon name="dropdownclosed"></dt-icon>
</button>
```
```
<ng-template #overlayPrev>...</ng-template>
```
```
  readonly overlayConfig = {
    originY: 'center',
  };
```

## Behavior

DtOverlay is shown correctly on:
- **Firefox**: 71.0 (64-bit) [Windows 10]
- **Chrome**: Version 79.0.3945.79 (Official Build) (64-bit) [Windows 10]

DtOverlay isn't shown on:
- **Edge**: Version 80.0.355.1 (Official build) dev (64-bit) [Windows 10]
- **Chrome**: Version 78.0.3904.108 [MacOS]

### Used Versions:
- **node**: 10.15
- **yarn**:  1.15
- **typescript**: 3.5.3
- **angular**: 8.2.12
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 4.15.1

**Comment by tomheller** [comment]
Hi @bartoszbobin 
Disabled buttons do not send browser events. The Overlay not showing up in this case is by design. 

If you have a specific usecase where you would need this, we'd be happy to talk about possible solutions.

**Comment by bartoszbobin** [comment]
> The Overlay not showing up in this case is by design.

At this moment DtOverlay sometimes is shown sometimes isn't - depends on browser and platform - would be nice to have consistent behavior.

> If you have a specific usecase where you would need this, we'd be happy to talk about possible solutions.

In my usecase state of the button depends on some conditions and I want to show information why it is disabled in DtOverlay.

DtOverlay is necessary here becasue:
1. I show another info in DtOverlay when button is enabled, I could use `title` attribute but then I have different UI when button is disabled,
2. have some DtIcon's and more lines of text with formatting - so `title` isn't enought for me ;)
