### ISSUE TITLE
Barista: use CDK ClipboardModule for all copy-to-clipboard actions

### ISSUE THREAD

**Issue by lara-aigmueller** [dynatrace-oss/barista#365]
Can be used after upgrading to Angular v9.

- Live example source code copy button
- Headline link component
- copy button on color pages (copy hex & copy cmyk)

**Comment by lara-aigmueller** [comment]
We have to wait for Angular 9 to do this issue.

**Comment by tomheller** [comment]
Duplicates #77 and #746
