### ISSUE TITLE
Linting rules: Rethink severity

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#367]
Since we are opensource our linting rules might not fit everybody - we should rethink the severity - is it a good idea to set all linting rules to warning - so we can educate devs but don't force them into a corner if they have a edge case

**Comment by ffriedl89** [comment]
@thomaspink @tomheller What's your take on it?

**Comment by tomheller** [comment]
I think setting the defaults of the rules to warning is fine. Would it be possible to ship an default setting with "best practices" that we would suggest, that are enabled (or set to error), that consumers can extend from?

**Comment by ffriedl89** [comment]
I think that's a good idea :)

**Comment by lara-aigmueller** [comment]
As our custom linting rules are not enabled by default (using `ng-add`), it's optional to activate/use them in a project. As discussed with @ffriedl89 we will close this issue for now. We can reopen it, once we have a use case to add more options to configure the linting rules.
