### ISSUE TITLE
DtSwitch: could be inline-flex

### ISSUE THREAD

**Issue by bartoszbobin** [dynatrace-oss/barista#383]
# Feature Request
`<dt-switch>` should have CSS `display: inline-flex` becasue now whole row is clickable

![image](https://user-images.githubusercontent.com/1777108/71713464-272c8080-2e0a-11ea-8d5a-d62b0ae56974.png)

**Comment by tomheller** [comment]
Hi @bartoszbobin!

I guess it could be, but it also looks like as this would break some layout in the applications. 
I think we need to plan this one for a next major version, what do you think @lukasholzer @thomaspink?

![switch-inline-flex](https://user-images.githubusercontent.com/6338434/71976970-fc7e6580-3217-11ea-9b5d-dd3b109d27e4.gif)
