### ISSUE TITLE
Filter field: Custom placeholder/tooltip to explain filter capabilities

### ISSUE THREAD

**Issue by moertenschlag** [dynatrace-oss/barista#393]
# Feature Request
Allow setting custom placeholders or/and tooltips for filter fields.

## Summary
Currently it is not possible to add placeholder or tooltip values.

## Feature Description
Add a property(ies) to allow setting placeholder or tooltip setup placeholder values for each filter to give a customer a hint what the user should or can enter in the placeholder.

We have scenarios where can add pattern, etc.

**Comment by moertenschlag** [comment]
Some feedback from the customers.
In prod environments this happens quite regularly that the name is not readable anymore. This is especially a problem because a lot of the name are quite similar and only have a different ending.

Here an test example to make it clear.

<img width="1134" alt="cutoff" src="https://user-images.githubusercontent.com/38486390/72532075-0127c700-3873-11ea-9e57-3d656bc9c61a.PNG">

**Comment by ffriedl89** [comment]
@moertenschlag The issue with truncation is different than the feature you are describing. The truncation issue #392 seems to be more critical - we will raise its priority
