### ISSUE TITLE
Filter Field: Input got lost on fast input

### ISSUE THREAD

**Issue by moertenschlag** [dynatrace-oss/barista#402]
# Bug Report

## Expected Behavior

The entered values are used as entered

## Current Behavior

If the values are entered fast and enter is pressed, the values are not used.

## Steps to Reproduce

See video.

1. Select address free-text in barista example
2. Enter values
3. Hit Enter very fast enter

## Context (Environment)

https://barista.dynatrace.com/components/filter-field

**Comment by ffriedl89** [comment]
Is duplicated by #294
