### ISSUE TITLE
Provide a toggle event handler for dt-tree-table-toggle-cell

### ISSUE THREAD

**Issue by sherifElhefnawyDynatrace** [dynatrace-oss/barista#415]
# Feature Request

## Summary

Add a toggle event for collapsing or expanding the toggle cell in the dt-tree-table component.

## Feature Description
As there is no other way to detect that the toggle cell in the tree table has expanded or collapsed, a click handler on the entire toggle cell was used. But this solution isn't great as a click handler on the toggle icon (toggle event) would be way more precise and avoid weird behavior for the user.

**Comment by tomheller** [comment]
@sherifElhefnawyDynatrace to clarify, do you want to have
1. an event on the `dt-tree-table-toggle-cell` that notifies you about a change in it's open and close state.
2. a public function on the `dt-tree-table-toggle-cell` that will let you programmatically toggle the expanded state?

**Comment by sherifElhefnawyDynatrace** [comment]
@tomheller , I would like the have the first option where I would get notified about the change of state :)

**Comment by gselltho** [comment]
Hi @sherifElhefnawyDynatrace, 
i'm on it and will do a pull request this week
