### ISSUE TITLE
Durationformatter: Feature proposal

### ISSUE THREAD

**Issue by rowa-audil** [dynatrace-oss/barista#444]
# Durationformatter Feature proposal

## Feature proposal

The DtDurationFormatter converts an input duration to an output duration. Both
the input and output units are configurable. Additionally, it has support for
precision/mode concerning how the output is displayed.

### Precisionmodes

- DEFAULT || undefined: Default mode
- PRECISE: Precise
- 1 - n: Amount of units to display

Pipesyntax:

```html
{{ <input /> || dtDuration: '<formattingMethod>':'<outputUnit>':'<inputUnit>' }}
```

The duration formatter pipe will cover the use cases below:

### **Default mode:**

It will only display two units from the biggest unit that has a value.
InputUnit is set to **milliseconds** by default

- _outputUnit not specified_ ('DEFAULT':undefined:undefined):
  - input (milliseconds): 61 001
  - output: 1 min 1 s 1 ms
  - precisionMode: "DEFAULT" OR undefined

- _outputUnit not specified_ ('DEFAULT':undefined:undefined):
  - input(milliseconds): 3 661 001
  - ouput: 1 h 1 min 1 s
  - precisionMode: "DEFAULT" OR undefined

- _outputUnit specified_ ('DEFAULT' **:'s':** undefined):
  - input (milliseconds): 1 500
  - output (seconds): 1 s
  - precisionMode: "DEFAULT" OR undefined

- _outputUnit specified_ ('DEFAULT' **:'s':** undefined):
  - input (milliseconds): 500
  - output (seconds): < 1 s
  - precisionMode: "DEFAULT" OR undefined

- _outputUnit specified AND inputUnit specified_ ('DEFAULT'**:'s':'h'**):
  - input (hour): 3
  - output (seconds): 10800 s
  - precisionMode: "DEFAULT" OR undefined

### **Precise mode:**

- outputUnit not specified:
  - input (milliseconds): 1500
  - output: 1500 ms
  - precisionMode: "PRECISE"

- outputUnit is seconds:
  - input (milliseconds): 1 500
  - output (seconds): 1.5 s
  - precisionMode: "PRECISE"

### **Custom amount of displayed units**

- Precision set to 2:
  - input(milliseconds): 90 061 001
  - output: 1 d 1 h
  - precisionMode: 2

- Precision set to 5:
  - input(milliseconds): 90 061 001
  - output: 1 d 1 h 1 min 1 s 1 ms
  - precisionMode: 5

**Comment by jsjsat** [comment]
Will this also work for rate units?
 E.g.: CPU time -> 10 s/min

**Comment by dlaubi-dt** [comment]
> Will this also work for rate units?
> E.g.: CPU time -> 10 s/min
Good point.
IMO it should be compatible with the dtRate formatter.

**Comment by rowa-audil** [comment]
@dlaubi-dt Good morning, first I want to apologize for the late response. I couldn't come to the office on Friday.
There are two outputs possible by giving the pipe another attribute which sets the formation mode:

**DEFAULT || undefined**
- Input: 1ms
- outputUnit: seconds
- Output: < 1s

**PRECISE**
- Output: 0.001s

@jsjsat && @dlaubi-dt  Good morning, can you elaborate on the rate s/min? I'm not quite sure what that means tbh ^^
But since Angular supports chaining pipes, I think that with a little string formatting magic it should work (Will test this out and keep you up to date if you want)
