### ISSUE TITLE
Releasing needs github authentication for stage-release

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#447]
# Feature Request

Our `npm run stage-release` needs the github credentials to create the pull request. Check if we can get the local one of the git user and add it to octokit.

**Comment by tomheller** [comment]
It does not seem as if you could grab the credentials from a local authentication. Possible solutions would be to build an authentication step into the stage release, or simply open a browser on the url that only requires the person running the stage release to click a single "Create Pull Request" button. 
Url would look something like this:
`https://github.com/dynatrace-oss/barista/compare/master...barista/stage-release-*.*.*`
