### ISSUE TITLE
Filter Field: Autocomplete appears above page header

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#451]
# Bug Report

With an open autocomplete or range, the opened overlay appears above the sticky page-header (z-index problem). 

## Expected Behavior

I'm not entirely sure what should happen. Either the autocomplete or range box should close when scrolling or the z-index should be fixed. 

## Current Behavior

Autocomplete or range box stay open and overlay other components.

### Used Versions:

- **angular**: 8.2.12
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 4.15.1

**Comment by ffriedl89** [comment]
Fixing the z-index is not as trivial unfortunately, but @lukasholzer created a `DtFlexibleConnectedPositionStrategy` that is part of the core package that respects the offset top for the sticky header. We are already using this in the selection area. We should be able to reuse this for the filter field.
