### ISSUE TITLE
Remove the RouterLink from the secondary-nav-section

### ISSUE THREAD

**Issue by NinaKammerlander** [dynatrace-oss/barista#465]
# Feature Request

The secondary-nav-section should work without a router.

Currently, the `dt-secondary-nav-section` contains a switch within its template where it defines whether the generated link should be either an external link (which uses the href attribute on the rendered html), or an internal link (which uses the `routerLink` directive). 

Template reference from https://github.com/dynatrace-oss/barista/blob/master/components/secondary-nav/src/section/secondary-nav-section.html#L13-L22: 
```html
<a [href]="href" class="dt-secondary-nav-section-header" *ngIf="external">
    <ng-container *ngTemplateOutlet="content"></ng-container>
  </a>
  <a
    *ngIf="!external"
    [routerLink]="href"
    class="dt-secondary-nav-section-header"
  >
    <ng-container *ngTemplateOutlet="content"></ng-container>
  </a>
```

In general we are trying to avoid a hard dependency to the Angular Router, which is why we should think about removing this switch and let the consumer handle what linking mechanism they would like to choose.

**Comment by NinaKammerlander** [comment]
@ffriedl89 can you please add more to the description? 😄

**Comment by tomheller** [comment]
I have updated the description to be a bit more telling about what is supposed to be the outcome here.

**Comment by thomaspink** [comment]
To resolve this we have to change the way the section works to something like:

````
<a dt-secondary-nav-section routerLink="/something">
    <dt-secondary-nav-section-title>
      Monitoring
    </dt-secondary-nav-section-title>
    <dt-secondary-nav-section-description>
      Setup and overview
    </dt-secondary-nav-section-description>
</a>
```

Internally the html of the section (expect for the template) has to move to the secondary nav itself (or an internal component).

**Comment by thomaspink** [comment]
We have to change the api and the way how the section work for that. Please hit me up if someone starts working on this issue.

**Comment by ffriedl89** [comment]
@areknow We talked about this a while ago, and we would like to get this going again :) Would you be able to help us out here? 
Any help is very much appreciated

**Comment by areknow** [comment]
@ffriedl89 sorry for the delay, I will get the PR ready this week

**Comment by tomheller** [comment]
Issue is still relevant and should not be closed. @areknow would you still be interested to provide the fix for this one?

**Comment by areknow** [comment]
Hey @tomheller, I started the work and should be able to complete it next sprint 👍
