### ISSUE TITLE
Chart: Selection overlay being re-opened on window resize

### ISSUE THREAD

**Issue by peter-affenzeller** [dynatrace-oss/barista#472]
# Bug Report

Regarding PR #432

## Expected Behavior

After selecting a timestamp or a range in a chart, closing the overlay and then re-sizing the window, the overlay should stay closed.

## Current Behavior

When re-sizing the window after closing a chart timestamp/range overlay, the overlay is re-opened.

## Possible Solution

Separate streams of range/timestamp changes and window resize and only call updateOrCreate on window resize if an overlay actually exists.

## Steps to Reproduce

1. Make a selection in a chart
2. Close the overlay
3. Re-size the window

### Used Versions:

- **node**: v12.13.1
- **npm**: 6.13.6
- **typescript**: 3.4.5
- **angular**: 8.2.14
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 5.0.0

## Attachments

[chart-overlay_window-resize.zip](https://github.com/dynatrace-oss/barista/files/4101478/chart-overlay_window-resize.zip)

**Comment by tomheller** [comment]
This issue is still valid and has already a PR assigned to it. It is already in the Review stage, so it should be done shortly.
