### ISSUE TITLE
Filter field: Make it easier to prefill filters based on the current data source

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#473]
# Feature Request

## Summary

Right now teams that use the filter field in a more simple way (just key-value pairs) have a hard way to persist the state they have in e.g the URL to the filter field. For every URL key/value pair they have to map/find the corresponding object in the data source, so they can set it as a filter on the filter field.

## Feature Description

Investigate if we can provide a better way to support these cases. 
## Attachments

For reference lookup the function `convertUrlParamsToNodes`.

**Comment by subarroca** [comment]
While keeping the current output and input it could be good to provide transforming functions that decompose and recompose field array.

Maybe this could be implemented in the data source object , that way if anyone has it's own DS implementation they could extend that too
