### ISSUE TITLE
feat: Add animations to chart tooltip/heatfield/selection-area overlay to improve user experience.

### ISSUE THREAD

**Issue by peter-affenzeller** [dynatrace-oss/barista#476]
# Feature Request

## Summary

Add some basic animations to improve the user experience when interacting with the chart. E.g. fade in and fade out for the selection area overlay to make it clearer that an overlay at a previously selected timestamp has been closed and a new overlay opened at the currently selected position.

## Feature Description

Previously, chart overlays popped up right after hovering, opening a heatfield or selecting a timestamp/range. When selecting a new timestamp, the overlay instantly changed position to the updated selection and the data updated. By adding some basic animations, the user experience can be enhanced and the animations can help guide the focus of the user.

There already is an open PR (#450), I will split this into separate PRs for each animated part of the chart as discussed with @lukasholzer after working on the PR comments.

**Comment by lukasholzer** [comment]
@peter-affenzeller Have you already aligned the animation speed and style with our UX department? If you have to could you be so kind and comment or write the UX feedback to this issue?

Since we are the open-source we try to communicate decisions transparent for everybody. So a quick clarification would be great for your PR #594

**Comment by peter-affenzeller** [comment]
@lukasholzer yes, I did, sry, forgot to add that as a comment to the PR itself.
UX wanted the animation of the heatfield backdrop to be a little bit faster than I originally implemented it and to remove the y-translation of the heatfield overlay and only keep the fade-in/-out.
