### ISSUE TITLE
Better detect failing examples.

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#488]
There is currently an issue where we can not check whether the examples of components are fine and work properly in the review process, unless the review is checking out the branch and runs the different apps (barista, demos, ...) - We all know that this is only done for the minority of PRs.

An example would be the change of the data structure of an option in the filter field when we released 5.0.0. We(I) forgot to update the data in the examples, which led to a broken state of the filter field examples in the demo and barista app. (See PR #487 which fixes this problem)

As discussed with @ffriedl89 we came up with 2 approaches that could/would help with that.

1. Run the barista and demo apps somewhere for every PR, to make it easier for reviewers to check whether the apps are fine. With a link to these running apps in the PR it should less of a hurdle.

2. Spin up the barista and/or demos app as a build step/check and check if the startup was fine, and then click through all pages/examples and look for errors.

Let's discuss which way we wanna go to prevent issues as described above. If you have a different idea please also share it here.

@tomheller @lara-aigmueller @lukasholzer

**Comment by thomaspink** [comment]
When looking at only the two solution above, i would suggest to first try out No. 1 and if that does not work for us (noboy clicks those links and checks the apps) we could add No. 2 as a second layer.

**Comment by lara-aigmueller** [comment]
Yes, I like the idea of having a preview somewhere, at least for all public readme files.

**Comment by tomheller** [comment]
It probably would make a lot of sense to build previews of barista application for every PR. I really like the idea. Maybe we can leverage netlify branch builds for this one? @lukasholzer what do you think?

**Comment by thomaspink** [comment]
food for thought: Fabian also mentioned Zeit for the previews.

**Comment by ffriedl89** [comment]
As discussed, I think that previews are a very good first step for us to improve code quality and also ease the review process. 
We can go from there if we need additional checks similar to the ones we had with the barista-examples build.

**Comment by tomheller** [comment]
I agree with @ffriedl89 here. Having previews of barista would be helpful. I don't have a strong preference on where or how they are being deployed. This will be up to you.

**Comment by thomaspink** [comment]
@ffriedl89 is investigating zeit right now. Pls keep us updated
