### ISSUE TITLE
[Timeline chart]: Overlapping metrics markers

### ISSUE THREAD

**Issue by allexcd** [dynatrace-oss/barista#496]
# Bug Report

## Expected Behavior

Markers should be visible and not overlapping

## Current Behavior

Metrics not displayed in the tooltip because they coincide with each other. Also, when overlapping over them instead of seeing all the appropriate details for all the overlapping markers, there's displayed only the information related to the marker that is on top of all the others

## Possible Solution

- Place one marker on top of the other
- Place one marker slightly to the left and the other one slightly to the right
- Display the details of all the overlapping markers in a single overlay. Example:

![image](https://user-images.githubusercontent.com/6011489/73262144-d112e900-41cd-11ea-9143-b536ab82575a.png)

Also, marking the hovered one helps the user

### Used Versions:

- **node**: 10.15.0
- **npm**: 6.4.1.
- **typescript**: 3.5.3
- **angular**: 8.2.12
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 5.0.0

## Attachments

![image](https://user-images.githubusercontent.com/6011489/73261648-cb68d380-41cc-11ea-969b-9b325ffb5a45.png)

![image](https://user-images.githubusercontent.com/6011489/73261823-239fd580-41cd-11ea-8fa5-a678b311463f.png)

**Comment by ffriedl89** [comment]
Hey @allexcd thank you for this issue. I think this is not really a bug, but more a feature request. We should discuss possible solutions here and we can guide you through the process of contributing this feature when we agree on a solution to try. 

We are more than happy to talk to you to ease you into the process :)

**Comment by ffriedl89** [comment]
I'd suggest a solution where we group the markers similar to how we group the points in the event chart. So if the distance between two markers falls under a certain threshold we merge the markers. 

This means that we need a character / icon / indicator for markers that have multiple values. 

I think it makes sense to display all markers that where hit inside the overlay, similar to the approach we took in the event chart. 
@ursula-wieshofer Please advice from a UX perspective. 

@tomheller implemented the merging for the dt-event-chart component so he can surely support you there as well.

**Comment by ursula-wieshofer** [comment]
Thanks very much for thinking about this. The only advice from a UX perspective is to definitely merge the markers and don't show them slightly left or right as this would change the message we want to tell the user. 
I think showing the details in the overlay is a very good solution and showing the markers on top of each other too.

**Comment by ursula-wieshofer** [comment]
Please have a look at this as well @Xavi-J

**Comment by ffriedl89** [comment]
Showing them slightly off is something where we would run into issues quite fast again. What do you do if you have as many markers in a very small space as shown in the screenshot above? 
So merging would definitely be preferable. You can just move so many markers slightly off somewhere. ;)

**Comment by Xavi-J** [comment]
@ffriedl89 @ursula-wieshofer in my opinion we should work on a holistic solution for charts with such range scale issues (confronting milliseconds with seconds, minutes, or even hours) such as the Range selector proposed for the Events chart (https://dev-wiki.dynatrace.org/display/BCN/Eventchart+requirements+for+Core). 

This would prevent us from facing this kind of issues and also from having to solve this issues in different ways in the product depending on the specificities of the page. It would be a consistent cross page solution. 

You can take a look at how it would behave in here. https://www.echartsjs.com/examples/en/editor.html?c=area-simple

**Comment by ffriedl89** [comment]
@Xavi-J I agree that a holistic solution is ideal in general, but solutions that arch over multiple components and try to solve a problem on a bigger scale need to be started by UX in my opinion. 

@ursula-wieshofer & @Xavi-J are you planning some research for a bigger solution? Otherwise, this issue seems to get stale.
