### ISSUE TITLE
Filter field: Default datasource types should be able to hold custom properties

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#507]
# Bug Report

The current types that describe the data structure that need to be passed into the `DtFilterFieldDefaultDataSource` make it hard (nearly impossible) to describe custom properties that are added additionally.

## Expected Behavior

Custom data structures/properies on options for the default data source should be possible and the types should support it.

## Current Behavior

Currently you can set custom data/properties but the defined types on the default data source makes it hard to do so. A typesafe solution is not possible right now. The consumers have to workaround with `any` or `unkown`.

## Possible Solution

Add a Generic to the option type so the consumer can set a custom data structure via this generic.

## Steps to Reproduce

Apply any custom property to the options in the data structure and try to read out these property when the filter has changed (via the filterChanges event or using the filters property on the filter field)

## Context (Environment)

Some teams need to apply custom properties/data to the options and the current types make it hard to do so.

**Comment by thomaspink** [comment]
[Basic example](https://www.typescriptlang.org/play/index.html?strictNullChecks=false#code/JYOwLgpgTgZghgYwgAgCJzHAygewK5RIA8AKgHzIDeAUMncgCYZwBcyJA3NQL7V-UB6AcgDEY8RMlTxg4QGEAqlhIB5ALJ9QkWIhRy8AZzA4AtukxVa9EHBMQ2RqKADmXXtTABPAA57Dxs2YARlJkAF4qbgoI-SNTczhkADJ2LmoEABs4AwNkWICE3AIkIORgE28MiDtwXML8QggifPjgshp6RmY2FsDMILc+TOzc3vriiAAmUIgAD0gQBlH-VswKcsrqiFq0ZiLG0narOiZMNk4efllRaVvb67l1AAUVADkAUVeSTXBoeCRkGpPO8AG7bMCHSydU6sVKXdJZHKAzxyUzeHAgcGQjr0BAYxx4BDGKAACgAlFRkLxoXsGkg2OMDuRjsgIGDwAAxYBQCAMQ4khAAIzYJLZ4LYQNBWPIFLCFBBOGADDJbAVSsi8Oud21kmuAEFXgBxBQAGT1ACV0viwMg8RVwshMQB3ZGoioY8HktJanW+h5vLAKNTvS1WkBGZCQIwJUoRHF0Gx2NgAcjgSxgyYANCylSmlcn4Xjwzao2AEpMeis+ok4yzE-ZkKn01mcww8wwC+4ixHSwkAMyVuLVkKUMpt5COFxU6JQ6y2BtNgwZ7OdXON-OF62MAyxx0QF1jWkTIJesMRpaTB3OvJVxlISanq0VAB0MP2AIiSwGfC-r+YDt7YIuF-GEAIgaNmEmYCdz-CwIkAzA+w4ZAhjRWDsDpFBPx3aDJnQsCIP6XD8Pg8Cy0g4jQNIwi4CQ1CXzFTluV5UV2RtOVZzobscCqZ8MhwZxWPBdDn3rMkuE6bjeP4wTGLAESlXEnglKfbxnzkrkeQYEkhPACVgTY5pb2CIhKDXScQGcKIyFlCh41tfEeIgPiBN0+SYVE+clMkxzpNcuSFOVNxxKAA)

**Comment by thomaspink** [comment]
Should be released with version 7.0.0 as some breaking changes are required.

**Comment by tomheller** [comment]
@thomaspink will you be able to prepare this one for the release of 7.0.0?
