### ISSUE TITLE
Label in "Add Tag" button in dt-tag-list is always wrapped and looks broken

### ISSUE THREAD

**Issue by heartdisease** [dynatrace-oss/barista#509]
# Bug Report

## Expected Behavior

The button label fits into one line and is not wrapped.

## Current Behavior

The button label is wrapped after the word "Add" and looks broken.

## Possible Solution

Removing fixed width from element `span.dt-tag-add-button-text`

## Steps to Reproduce

Use the default example from the Barista documentation page.

### Used Versions:

- **@dynatrace/barista-components**: 5.0.1

**Comment by tomheller** [comment]
Thank you for reporting this. 
Problem is reproducible.

![image](https://user-images.githubusercontent.com/6338434/73458906-4b7e6d00-4376-11ea-8c77-22d2be749845.png)

**Comment by ffriedl89** [comment]
@heartdisease It would be awesome if you could contribute this bug fix :)
