### ISSUE TITLE
Ivy: Add library to ngcc validation repo

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#519]
To better validate whether our library is fully compatible with ngcc, we should add it to the [ngcc validation repo](https://github.com/angular/ngcc-validation)

**Comment by lukasholzer** [comment]
The pull request in the ngcc validation repo https://github.com/angular/ngcc-validation/pull/832  

To get a comprehensive check for our library we have to add all our barista examples to the repository.

**Comment by lukasholzer** [comment]
The repository build break build fails on other dependencies. So I will stop investing time on that. @thomaspink created his own repo for that.
