### ISSUE TITLE
Being able to release even when the last commit is not the changelog and version bump.

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#531]
# Feature Request

## Feature Description

Currently, it is only possible to release when the last commit is the changelog with the version bump. But with the auto cherrypicker, it could be possible that somebody merges a fix or feature in the meanwhile to the master and cherrypicks it automatically on this branch then the last commit would not be the changelog.

I suggest going n commits back to look for the changelog commit. In case we only need this commit to get the commit sha to download the tar from circle.

**Comment by tomheller** [comment]
Why do we need this?

**Comment by ffriedl89** [comment]
I'd table this issue for now - improve communication before providing a technical solution imo

**Comment by lukasholzer** [comment]
Communication can fail and this happened then you have to drop commits from a branch and destroy the history with that. It would be an easy fix because you only need to adapt one check with some lines of code. Easy win.

**Comment by tomheller** [comment]
But this would possibly publish a release that contains changes that are not within the changelog changeset, or am I getting this wrong?

**Comment by lukasholzer** [comment]
@tomheller no this would not happen because we release from a commit with a certain commit SHA and this SHA we get according to the commit message. In this case, we would release exactly the commit `chore: Bump version to 5.2.0 w/ changelog`. Currently, we check if the last commit matches the Regex but we have to go back in the history with the regex not only on the last commit. because we need only a hash to release from.

Because with this hash a build artefact on circle is connected with.
