### ISSUE TITLE
Favorite column modifies data source but should not interfere

### ISSUE THREAD

**Issue by tscherfler** [dynatrace-oss/barista#540]
# Bug Report

## Expected Behavior

Favorite column should not modify my data source.

## Current Behavior

Modifies data by reference.
https://github.com/dynatrace-oss/barista/blob/5ffbd2c02f6fca42630ed02f5caf3cb0c701b996/components/table/src/simple-columns/favorite-column.ts#L64

## Possible Solution

Hold favorite state in component itself.

## Steps to Reproduce

When data in datasource is immutable this breaks.

### Used Versions:

- **@dynatrace/barista-components**: 5.0.1

**Comment by tomheller** [comment]
Additionally the example binding is wrongfully called `change` here:
https://github.com/dynatrace-oss/barista/blob/master/libs/examples/src/table/table-favorite-column-example/table-favorite-column-example.html#L5
https://github.com/dynatrace-oss/barista/blob/master/libs/examples/src/table/table-favorite-column-no-header-example/table-favorite-column-no-header-example.html#L5
when the actual output is called `favoriteToggled`:
https://github.com/dynatrace-oss/barista/blob/master/components/table/src/simple-columns/favorite-column.ts#L43

**Comment by tomheller** [comment]
After a short investigation, this is what I have found: 
If the data in the datasource is immutable (the object has been frozen somewhere in the process) we cannot mutate the data on the original object. We as the component providers should not modify the data within that source.

Here is what I would propose as a solution:
In the favorite-colum.ts file
https://github.com/dynatrace-oss/barista/blob/53241e14c6eb04ed21dfd89540f682dd566751ad/components/table/src/simple-columns/favorite-column.ts#L64
I would remove the modification of the original data. 

The modification of the original data is best handled by the consumer of the component library, as we cannot know if the data is mutable or not. They can react to the event and handle the modifications of their data accordingly. 

@yngrdyn I would really appreciate your input on this one.

**Comment by yngrdyn** [comment]
Hello @tomheller, I'll take a look in this

**Comment by tomheller** [comment]
Thank you @yngrdyn, you are brilliant 🎉 🤘 .
