### ISSUE TITLE
Investigate storybook for web-components

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#544]
# Investigate storybook

Nrwl has added the support of storybook for nx workspaces. So with storybook we could reduce the maintenance of the examples. And provide visual regression testing.

Investigate the integration with stackblitz and our barista.

This would solve issue #15

**Comment by tomheller** [comment]
Do we not have that with #529 and with our Barista app deployment? What are the benefits that we would get from using storybook?

**Comment by lukasholzer** [comment]
@tomheller we would need storybook to have a visual regression testing tool for our components. Furthermore, it would help us to maintain all the examples in a more streamlined way.

## The key benefits of storybook where:
1. Examples with dynamic inputs. Designers can play around with input values they don't have to be hardcoded anymore.
2. Automated visual testing.  Instead of asserting specific CSS rules, selectors, and HTML markup, you assert that something visually appears as expected. If you refactor style, markup, or state logic, but visually nothing changes, you wouldn’t need to modify any tests or update visual baselines! 
3. Better built in a11y checks with visual output why and what fails with our a11y tests getting rid of the custom a11y setup.
3. Creating examples with a declarative approach (no need for deep Angular knowledge)

```typescript
import { DtButton } from '@dynatrace/barista-components/button';

export default { title: 'My Button' }

export const withText = () => ({
  component: DtButton,
  props: {
    text: 'Hello Button',
  },
});

export const withEmoji = () => ({
  component: DtButton,
  props: {
    text: '😀 😎 👍 💯',
  },
});
```

4. It is possible to generate a design system https://github.com/storybookjs/storybook/tree/master/addons/docs that can handle framework independent components. with documentation via markdown and examples. 

We should create a first MVP if everything works with testcafe – nx has already support for storybook and then check if we can generate the stackblitz examples out of it.

**Comment by tomheller** [comment]
This seems like a good idea as an addition for the barista outlet for testing and visual regressions. 

It will be interesting to see how storybook would deal with content-projections that we heavily use (i.e. in the card) or how this would deal with more complex examples (like a table).

**Comment by lukasholzer** [comment]
# First Research Results

![image](https://user-images.githubusercontent.com/11156362/76055645-832f9480-5f74-11ea-9317-95a97718bada.png)

I've created an isolated test repository to play a bit around and my first impressions are really good!

https://github.com/lukasholzer/storybook-angular-demo


## Knobs

One core feature of storybook is the **knobs feature** where you can set properties that are dynamic:
![image](https://user-images.githubusercontent.com/11156362/76055469-0dc3c400-5f74-11ea-9523-b14c325e8678.png)

> knobs make components easily accessible to the non-programmer members of your team.


## Stories

The stories files are looking pretty straight forward to me. A big bonus is that you can actually share code between the stories file and the component itself.

**button.stories.ts**
```typescript
export default {
  title: 'DtButton'
};

// when you have content projection you have to use the template
const template = `<dt-button [color]="color">{{ buttonText }}</dt-button>`;

export const primary = () => ({
  moduleMetadata: {
    imports: [DtButtonModule]
  },
  component: DtButton,
  template,
  props: {
    disabled: boolean('Disabled', false),
    // the DtColors is an enum from the component
    color: select('color', DtColors, DtColors.Red),
    buttonText: text('Button Text', 'My Button')
  }
});

```

Because you have to specify which dependencies are needed for the component through the `moduleMetadata` it would be possible to generate an example component with a schematic for our stackblitz examples. But this has to be investigated a little bit more if storybook is providing a way to export the generated examples.

**Comment by tomheller** [comment]
@lukasholzer would you consider the investigation done? Can we close this issue?

**Comment by lukasholzer** [comment]
The investigation is done but we should create a discussion about how we want to proceed with that issue.

**Comment by tomheller** [comment]
Could you please do that or rephrase the issue so that the status of it is clear.

**Comment by ffriedl89** [comment]
I've continued some research to have storybook working for our web components based on the open-wc storybook prebuilt setup. 
I want to leverage storybook for our web components - this would eliminate the need to create our own dev app again, but instead rely on tooling to do this for us. 

I'll try to get a working prototype running

**Comment by lukasholzer** [comment]
@ffriedl89 do you mind doing it with bazel? As we don't have to migrate it then – and all prerequisite are done for it.

**Comment by tomheller** [comment]
Preliminary investigations of storybook and bazelification here:
https://github.com/dynatrace-oss/barista/compare/storybook-tests

**Comment by lukasholzer** [comment]
We will close this issue as web components are not the way we want to create components in the future this is related to a shift of priorities in the team.
