### ISSUE TITLE
Barista: Show full component decorator code in example TS-code

### ISSUE THREAD

**Issue by lara-aigmueller** [dynatrace-oss/barista#545]
In some cases it makes sense to show the full metadata within the component's decorator in the  Barista examples TS code; e.g. when additional providers are used in an example. Currently they are replaced with `...`.

![image](https://user-images.githubusercontent.com/22007416/73830311-c3301a00-4804-11ea-9a82-955edafb6c8e.png)

FYI @myieye

**Comment by myieye** [comment]
In this case, the Component with the ugly red circles is not included in the displayed code at all. Only the first component in the file is shown. So, showing multiple classes/components may be another consideration altogether.
