### ISSUE TITLE
Table: update expand functionality

### ISSUE THREAD

**Issue by ursula-wieshofer** [dynatrace-oss/barista#560]
# Feature Request

## Summary
Update position of the expand functionality in tables and add validation hints.

## Feature Description

Problems with the current expand functionality:
- On big screens the nested arrow button is often (too) far away from the content
- On screens with special tables like the USQL (horizontal scrolling) the button to expand the table row wouldn't even be visible
- Validation errors of components in the expanded section are not visible if the user collapses the table row

Solution:
1. After research and testing we agreed that the arrow to expand the table row should be on the left side of the table. 
<img width="872" alt="Screenshot 2020-02-06 at 13 06 03" src="https://user-images.githubusercontent.com/36620967/73935702-72422380-48e1-11ea-9388-44bd4e196d4a.png">

2. If there are components changed within the expanded section, which also occur in a table column, we should highlight this value as long as it is not saved yet.
![Screenshot 2020-02-06 at 13 08 11](https://user-images.githubusercontent.com/36620967/73935860-d2d16080-48e1-11ea-92d9-43f661ac0197.png)

3. If there is a validation error within the expanded section we should use the dtIndicator
![Screenshot 2020-02-06 at 13 10 31](https://user-images.githubusercontent.com/36620967/73935975-13c97500-48e2-11ea-9ad0-70e07e1bcc28.png)

## Attachments
We asked the UX enablement guild for their feedback to this component. You can see the video with a prototype for this survey here:
https://web.microsoftstream.com/video/c4482ef5-825b-4967-8600-c60dbd3a4bb6

**Comment by tomheller** [comment]
Hi @ursula-wieshofer!
Thank you for reaching out about this. As far as I can tell, the order of columns is up to the libraries consumer to define. This means that the expand column can be used in any position. 

Marking dirty properties within the expand and have it displayed in the row itself, is also something that should already be possible on an individual level. I feel that a general solution could be rather cumbersome to achieve, as this is tightly coupled to the data displayed.

**Comment by ursula-wieshofer** [comment]
Thanks very much @tomheller. 
In this case I will publish the information of the suggested changes and will then ask for help to get this into the product. 
Could we change this issue then to update the example on Barista, so that we can describe the recommended pattern? Meaning the example here: https://barista.dynatrace.com/components/table/#expandable-table-rows

**Comment by tomheller** [comment]
@ursula-wieshofer With pattern you mean the expandable being on the left hand side, or the whole shabang with bold/red cell entries?

**Comment by ursula-wieshofer** [comment]
@tomheller I mean the expandable being on the left hand side. I think we can describe the suggested pattern of the validation in the section where we already have an example.

**Comment by tomheller** [comment]
@ursula-wieshofer Did you think about what happens when handling responsive tables? 
The current behavior slices off columns from the right end of the table and adds an expand to the right end of the columns. Should this behavior stay and also move the `details-action` cell to the left?

**Comment by tomheller** [comment]
There is a preview available here: https://barista-6libuy9ad.now.sh/
Sadly, deep linking is not enabled in previews yet so you will have to navigate to the table page. We will look into add deep linking soon.

**Comment by ursula-wieshofer** [comment]
The arrow color shouldn't change, the concept is just done in a black and white wireframe to concentrate better on the functionality and not on styling. 
And about the responsive behavior: the behavior should stay that columns move into the "details" section and the details would then always be on the left. This could be a bit strange, but let's try as it would be more consistent to have it at the same position.

**Comment by tomheller** [comment]
@ursula-wieshofer Example is ready and could be opened for code review / your review. Will you be able to provide a pattern page for this behavior?

**Comment by ursula-wieshofer** [comment]
@tomheller I will describe the functionality directly in the components page ;) Thanks so much.
