### ISSUE TITLE
Table: reorder functionality

### ISSUE THREAD

**Issue by ursula-wieshofer** [dynatrace-oss/barista#561]
# Feature Request

## Summary
Add the functionality to reorder table rows (for rule sets, etc.) to our table component.

## Feature Description
There are 2 use cases to reorder table entries in Dynatrace:
1. rule sets in our settings
2. reorder recorded actions of a synthetic browser monitor

Currently reordering table rows in our platform is done via clicking the <move up> or the <move down> arrow buttons in a table row. It is not yet implemented in Angular. Problems with this functionality are:
- this is very annoying and exhausting when it comes to bigger rule sets
- every time a row is clicked the user has to follow the row with the mouse
- if there is pagination, the rules often jump to a different page when reordering them

Solution:
The reordering of table rows should be done with drag and drop.
- Users should be immediately able to see the drop position with a gray broken line
- As soon as the table row is dropped, the numbers get updated and the confirmation dialog appears to provide the save functionality

Additionally we need the possibility to validate the drop position. This is because e.g. in a synthetic action recording, the first action must always be a navigation action. So we need to prevent users from creating a script that won't work.
- Show the user immediately restricted positions (with a red broken line, light red background and a validation hint in the row, which explains why the user can't drop the row in this position)
- If the user drops the row anyhow, we revert this action. The row will move back to the initial position.
![drag-and-drop](https://user-images.githubusercontent.com/36620967/73937831-38275080-48e6-11ea-913e-bff42f9cc4d2.gif)

For accessibility reasons and especially for bigger rule sets we need a second possibility to change the order in a table.
- Hovering the order numbers will show an input field.
- Clicking the number will provide the possibility to type in a number
- Clicking the return key would confirm the number, the numbers get updated and the confirmation dialog appear to save these changes.

![typing-number](https://user-images.githubusercontent.com/36620967/73937958-83416380-48e6-11ea-9653-91e3a886b28a.gif)

Some notes to the reorder functionality to consider:

- If this functionality is used by a table, the sorting via table header must be restricted
- If the user has 10 rules and types in a higher number (e.g.502), the rule will be reordered to the very end of the table
- If the user types in an incorrect value into the number field (e.g. xyz) then we need our input field validation showing that this value is not allowed. On focus loss, we need to reset the wrong value to the initial value.
- The reorder functionality can also be used in expandable tables. As soon as the user starts dragging a table row, all expanded rows need to be collapsed in order to give the user an overview of where to drop the row
- If a table is filtered, the reorder functionality should be disabled to prevent users from making mistakes

## Attachments
We asked our UX enablement guild for feedback. The videos recorded with a prototype describing the whole functionality can be seen here:
https://web.microsoftstream.com/video/5e0eaf66-4e72-40c1-9f62-7ebeee735230

**Comment by ffriedl89** [comment]
Some notes here: 

> If this functionality is used by a table, the sorting via table header must be restricted
This information should be added to Barista as a pattern - we cannot easily restrict this in code 

> If the user types in an incorrect value into the number field (e.g. xyz) then we need our input field validation showing that this value is not allowed. On focus loss, we need to reset the wrong value to the initial value.

We could use a number input since no other values are allowed anyway. This would make it impossible to enter anything else than a number

> The reorder functionality can also be used in expandable tables. As soon as the user starts dragging a table row, all expanded rows need to be collapsed in order to give the user an overview of where to drop the row

I think collapsing is not a good idea, since it changes position of elements that might be dragged currently or the target location is different after the rows are collapsed.

> If a table is filtered, the reorder functionality should be disabled to prevent users from making mistakes

This is also something to add to a pattern in Barista. We might not be able to build this into the components. But a note for the developer that might have a search for the table in place can help us avoid this issue.

**Comment by ursula-wieshofer** [comment]
Awesome thanks @ffriedl89. Once the feature is available in Barista we will add these restrictions and guidelines ;)

**Comment by peter-affenzeller** [comment]
I started working on this, will keep you posted!
