### ISSUE TITLE
Create Nx Linting rules to enforce module boundaries and correct imports

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#570]
# Feature Request

Add the module boundaries linting rule and check for correct submodule imports:
I've seen a lot of imports like that `import { } from 'components/core/src/testing';` or `import { } from 'tools/shared/src/utils';`

So every import that imports not from the barrel via the path alias in the tsconfig or violates the module boundaries should be banned!

This is really a high prio task!

**Comment by ffriedl89** [comment]
We need to adhere to the conventions of nx having everything inside apps or libs folders. 

See 

```
function isAbsoluteImportIntoAnotherProject(imp) {
    return (imp.startsWith('libs/') ||
        imp.startsWith('/libs/') ||
        imp.startsWith('apps/') ||
        imp.startsWith('/apps/'));
}
```

The check above only works if you follow this structure. Therefore will move components and tools inside libs folder
