### ISSUE TITLE
Confirmation dialog – avoid unsaved edits

### ISSUE THREAD

**Issue by moarliman** [dynatrace-oss/barista#577]
# Feature Request

## Summary

Increase the visibility of the Confirmation dialog by sticking it to the bottom of the respective card

## Feature Description

- Problem: The currently implemented Confirmation dialog sticks to the bottom of the browser window, which makes it hardly visible, especially on large screens and when a user is focusing on an area at the top of a page. That's why many users navigated to another page without saving their edits. 

- Solutions: The dialog is placed on the bottom of the respective card. The dialog should float on the bottom if the content of the page exceeds the height of the browser window. In addition the dialog is animated to increase visibility. To avoid navigating to another page without saving or cancel the edits, an overlay locks the screen and the Confirmation dialog is animated to show that an action by the user is needed. 

### Entrance animation
```
/*
The CSS export should solely be used as a reference.
For a more detailed animation export the JSON file should be used.
*/
#confirmation-dialog {
    transform: translateX(-50%) translateY(-50%);
    animation: confirmation-dialog__width__1 200ms 0ms linear forwards, confirmation-dialog__width__2 200ms 200ms linear forwards, confirmation-dialog__height__1 200ms 0ms linear forwards, confirmation-dialog__height__2 200ms 200ms linear forwards, confirmation-dialog__opacity__1 400ms 0ms linear forwards;
}

@keyframes confirmation-dialog__width__1 {
    from {
        width: 2000px;
    }

    to {
        width: 2008px;
    }
}
@keyframes confirmation-dialog__width__2 {
    from {
        width: 2008px;
    }

    to {
        width: 2000px;
    }
}
@keyframes confirmation-dialog__height__1 {
    from {
        height: 90px;
    }

    to {
        height: 94px;
    }
}
@keyframes confirmation-dialog__height__2 {
    from {
        height: 94px;
    }

    to {
        height: 90px;
    }
}
@keyframes confirmation-dialog__opacity__1 {
    from {
        opacity: 0;
    }

    to {
        opacity: 1;
    }
}
```

### Lock animation
```
/*
The CSS export should solely be used as a reference.
For a more detailed animation export the JSON file should be used.
*/
#Rectangle_11 {
    transform: translateX(-50%) translateY(-50%);
    animation: Rectangle_11__opacity__1 125ms 0ms linear forwards;
}

@keyframes Rectangle_11__opacity__1 {
    from {
        opacity: 0;
    }

    to {
        opacity: 1;
    }
}

#confirmation-dialog {
    transform: translateX(-50%) translateY(-50%);
    animation: confirmation-dialog__x__1 100ms 0ms linear forwards, confirmation-dialog__x__2 66ms 100ms linear forwards, confirmation-dialog__x__3 66ms 166ms linear forwards, confirmation-dialog__x__4 68ms 232ms linear forwards;
}

@keyframes confirmation-dialog__x__1 {
    from {
        left: 1526px;
    }

    to {
        left: 1526px;
    }
}
@keyframes confirmation-dialog__x__2 {
    from {
        left: 1526px;
    }

    to {
        left: 1530px;
    }
}
@keyframes confirmation-dialog__x__3 {
    from {
        left: 1530px;
    }

    to {
        left: 1522px;
    }
}
@keyframes confirmation-dialog__x__4 {
    from {
        left: 1522px;
    }

    to {
        left: 1526px;
    }
}
```

## Attachments

https://www.figma.com/file/B9KBwNgrN8lX7I9grgYkkc/confirmation-dialog-styling?node-id=0%3A1

![floating](https://user-images.githubusercontent.com/57876279/74161293-ffa5b080-4c1e-11ea-8074-7a50834fb55e.gif)

![floating-lock](https://user-images.githubusercontent.com/57876279/74161302-02a0a100-4c1f-11ea-953c-2d74b6f22f71.gif)

![settings-2540-floating](https://user-images.githubusercontent.com/57876279/74322824-d4d56c80-4d84-11ea-8255-07e7d9869d49.png)

![settings-2540-floating-multiple-cards](https://user-images.githubusercontent.com/57876279/74322840-da32b700-4d84-11ea-92ac-1f9c8be7e230.png)

**Comment by tomheller** [comment]
Some points to consider here:

> The dialog is placed on the bottom of the respective card. The dialog should float on the bottom if the card is bigger than the height of the browser window.

How would we handle multiple unsaved, card locked confirmation dialogs? Would they stack together? 

> To avoid navigating to another page without saving or cancel the edits, an overlay locks the screen and the Confirmation dialog is animated to show that an action by the user is needed.

There can also be multiple changes made at once, that would be saved together with one confirmation dialog. When locking the screen after the first edit, how would the user be able to still make the other changes?

**Comment by moarliman** [comment]
> How would we handle multiple unsaved, card locked confirmation dialogs? Would they stack together?
I just added a few more screenshots and edited the description. So we just show one confirmation dialog per page. If the card or the content of the page exceeds the window height, the dialog floats on the bottom.
> There can also be multiple changes made at once, that would be saved together with one confirmation dialog. When locking the screen after the first edit, how would the user be able to still make the other changes?

![image](https://user-images.githubusercontent.com/57876279/74323145-5b8a4980-4d85-11ea-95f4-6ab3e40b40fe.png)

![image](https://user-images.githubusercontent.com/57876279/74323171-693fcf00-4d85-11ea-9ec1-e14f875cec96.png)

The user is only allowed to navigate between pages inside a settings category or between pages on an entity setting. Then the screen is not locked, the dialog stays open and the pages with changes are shown in the dialog description.

**Comment by tomheller** [comment]
@moarliman Don't you think it could be confusing that you can navigate to certain pages but not others.

Also, this still does not answer the question of there being multiple cards on a page and multiple confirmation dialogues overlapping.

**Comment by moarliman** [comment]
No we think that's the best option for now. Sorry I forgot to tell you that I've updated the images in the first comment to explain the multiple cards issue.

**Comment by moarliman** [comment]
Just attached the figma mockup to the first comment

**Comment by ffriedl89** [comment]
Notes: 
We had a lengthy discussion regarding changing the alignment and behavior as described in the issue. 

> The dialog is placed on the bottom of the respective card.

This should not be changed in the first version. I'd rather consider exposing the overlay configuration to the consumer to enable different position strategies. This might also have implications regarding the styling and animations used, so we need to be careful there. 
You can checkout a way of implementing the config as part of the public API in https://github.com/dynatrace-oss/barista/pull/459/files#diff-629888c811b4c5590a0534856bfbc25fR303

>  To avoid navigating to another page without saving or cancel the edits, an overlay locks the screen and the Confirmation dialog is animated to show that an action by the user is needed.

Two points here: 
1. The confirmation dialog does not handle the "screen lock". If the consumer wants to prevent navigation in certain cases the consumer should use `onbeforeunload` since we don't know what might set the screen in this state. 
2. We need a trigger to animate an already shown confirmation dialog to attract attention in this case. 

@

Work items: 
- [ ] Check whether the new animations apply to a globally positioned confirmation dialog as well
- [ ] Check whether the exposing the overlay config works
- [ ] Add a trigger for the lock animation
- [ ] Describe the pattern to prevent navigation in the CMS (@lara-aigmueller has more information)

**Comment by ffriedl89** [comment]
I've heard @SirTroyer is willing to contribute. 
I am still not certain if the investment is worth the benefit now.
