### ISSUE TITLE
[dt-chart-tooltip] Chart tooltip is shown although the chart is removed from Dom. 

### ISSUE THREAD

**Issue by mohamediab** [dynatrace-oss/barista#579]
# Bug Report

## Expected Behavior
Tooltip should be destroyed when the chart is removed from DOM.

## Current Behavior

Tooltip is stuck on the screen and can no be removed.

## Possible Solution

Tooltip should be destroyed when its parent chart is removed.

## Steps to Reproduce

- hover over a chart so the tooltip is visible
- apply an action which removes the chart from dom while mouse is still hovering over the chart
- the tooltip will stay and can not be removed although chart is removed.

## Attachments
![screenshot1](https://user-images.githubusercontent.com/60917703/74222442-ccadfc00-4cb4-11ea-8e22-f5e9cc227219.PNG)
![screenshot2](https://user-images.githubusercontent.com/60917703/74222444-cd469280-4cb4-11ea-8aa5-330de6b2513d.PNG)

**Comment by tomheller** [comment]
Hi @mohamediab! Thank you for reporting this one to us. 
We were able to reproduce this issue in our dev app and it seems that your proposed solution of destroying the overlay when the chart is destroyed.

**Comment by tomheller** [comment]
We have reached out to @mohamediab if he would be able to contribute this bug fix to the library, but due to time constraints, he sadly will not be able to do this at this time. I will take over that issue and see that we can sort this out as soon as possible.
