### ISSUE TITLE
Autocherrypicker does not cherrypick pull request from forks

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#586]
# Bug Report

## Expected Behavior

The autocherrypicker should cherrypick every PR 

## Current Behavior

The autocherrypicker does not cherrypick PRs that are being merged opened from forks.

I had to cherrypick this one by hand: https://github.com/dynatrace-oss/barista/pull/379

## Steps to Reproduce

1. Fork the repository
2. Create PR
3. Assign merge ready label
4. Wait for target labels
5. Merge
6. Autocherrypicker is not running

**Comment by tomheller** [comment]
Github actions do not have access to [forks deliberately](https://github.community/t5/GitHub-Actions/Actions-not-working-correctly-for-forks/td-p/35545) due to security implications. 
This seems not like something we can control, we will have to make sure to cherry pick forks manually.
