### ISSUE TITLE
DrawerTable component

### ISSUE THREAD

**Issue by madina705** [dynatrace-oss/barista#587]
# Feature Request

## Summary
Drawer table is a component that adds collapsible side content to table rows.

## Feature Description

This component uses table and drawer components. Table is the main content of the drawer and row click of the table opens the drawer content of the row. I think that this component should be a separate component since I could not find the way to include the drawer component inside table.  Columns which stay open when row is clicked can be defined like in example: 
 ``` 
<dt-drawer-table [openColumns]="['col1']">
          <ng-template let-row>
              <div class="row_col1">{{ row.col1 }}</div>
          </ng-template>
          <dt-table [dataSource]="dataSource" dtSort #sortable>
              <dt-simple-number-column
                      name="col1"
                      label="Column1"
              ></dt-simple-number-column>
              <dt-simple-number-column
                      name="col2"
                      label="Column2"
              ></dt-simple-number-column>
              <dt-simple-number-column
                      name="col3"
                      label="Column3"
              ></dt-simple-number-column>
              <dt-header-row
                      *dtHeaderRowDef="['col1', 'col2', 'col3']"
              ></dt-header-row>
              <dt-row [dtDrawerRowDef]="row"
                      *dtRowDef=" let row; columns: ['col1', 'col2', 'col3']"
              ></dt-row>
          </dt-table>
      </dt-drawer-table>
```

Here is the demo of the component: 

![drawer-table](https://user-images.githubusercontent.com/38882598/74327413-73190080-4d8c-11ea-976c-e1533a6603b1.gif)

**Comment by tomheller** [comment]
Hi @madina705!
This seems like something that could be incorporated into the barista-components repository. @ffriedl89 tells me that you would be willing to contribute this to the library. 

Could you maybe quickly outline what the api on the `dt-drawer-table` component would look like. What are it's inputs and outputs? Are there any public members / functions that can be used to open / close the drawer programmatically?

**Comment by madina705** [comment]
Hey @tomheller 

These are the inputs and the methods of the component: 

### **Inputs**

| Name  | Type | Default | Description| 
| ------------- | ------------- |  :---:  | ------------- |
| openColumns  | string[] | - | Defines the columns that stay visible when row is clicked by receiving a columnName[]. |

I have a question regarding the openColumns input here. Is it better to make the 1st column as default or make this input required? 

### **Methods**

| Name  | Description| Return value| 
| ------------- | ------------- | ------------- | 
| open | Opens the drawer | void |
| close | Closes the drawer | void |
| toggle | Toggles the drawer | void |

Regarding the outputs, would you recommend adding the outputs of the Drawer component?

**Comment by tomheller** [comment]
The inputs and methods seem great.

I would suggest to add the output to the `DtDrawerTable` and not directly to the drawer.
That should be good enough for consumers, who will need to react to an opened column, I guess.

**Comment by ffriedl89** [comment]
Depends on the experimental package being there #550, we will take care of finalizing the PR after 550 is merged.
