### ISSUE TITLE
Automatically hide DtPagination if not necessary

### ISSUE THREAD

**Issue by myieye** [dynatrace-oss/barista#590]
# Feature Request

Automatically hide DtPagination if not necessary.

## Summary

Almost every usage of DtPagination in DT's code base (12/16) explicitly hides it if there's only 1 page. I think this should be handled by the pagination component itself.

## Feature Description

Based on our usages of DtPagination, I propose that the **default** behaviour of the component be that it hides itself if there's only a single page. There should be a boolean option called `alwaysShow` that can be used to **force** the component to remain visible even if there's only 1 page.

**Comment by tomheller** [comment]
Hi @myieye!
Thank you for this feature request. This seems like an interesting feature request. 
Would you be willing to contribute this to the library yourself? 

The changes involved should be fairly easy to achieve. The difference to the current way of dealing with this is, that the DtPagination would not be instantiated when hidden with an `*ngIf` (if there is only one page available), whereas in your proposed solution, the component would always exist, even if it does not show anything.

**Comment by myieye** [comment]
When I say that we often explicitly "hide" it, I'm refering to cases where it's actually **hidden** as well as where it's not instantiated. Both methods are used in the cluster.

`*ngIf` has a performance advantage, but I prefer the idea of only hiding it. This reduces complexity, because developers don't have to worry about the component getting destroyed and then recreated (in which case they have to re-assign it to the DataSource etc.).

If a developer includes a paginator it means they're banking on the possibility of needing it even if they don't need it for the current data set.

**Comment by tomheller** [comment]
Hey @myieye !

> This reduces complexity, because developers don't have to worry about the component getting destroyed and then recreated (in which case they have to re-assign it to the DataSource etc.).
> If a developer includes a paginator it means they're banking on the possibility of needing it even if they don't need it for the current data set.

I agree, I just wanted to point it out as food for thought. 

Let's go with the `alwaysShow` override and try to incorporate the visibility switch into the Pagination.
Would you be willing to  contribute the changes?

**Comment by myieye** [comment]
@tomheller I'll add it to my backlog :D

**Comment by tomheller** [comment]
After discussing this within the team, it would make more sense to build this functionality into the table datasource (or other datasources that connect to the pagination), rather than to the pagination itself. 
Reasoning behind this would be that the pagination can be used in other situations and use cases where this might be handled differently. 

Would this make sense and help your use cases, @myieye ?

**Comment by myieye** [comment]
Making the DataSource responsible for UI layout seems a bit odd to me. You should then probably also move the `alwaysShow` option to the DataSource, which also feels very weird.

Do you guys have a specific use case in mind where having the Paginator hide itself automatically would be very unintuitive?

**Comment by tomheller** [comment]
We usually do not have patterns that the a component does not show itself at all, if certain criteria is matched. I would opt for a higher-order component in your codebase that can be shared if this is a pattern that is often used within your application. 

We feel that making the component responsible for its own visibility is not a pattern that we want to follow. We would essentially rebuild an `*ngIf` directive, which is already possible.

**Comment by ffriedl89** [comment]
I totally agree with @tomheller. The components provided by the library should be displayed if added to the template. It is very confusing if the consumer adds the component to the template but the pagination is not shown. This would also most likely create edge cases where we would need exceptions to those rules. If you would need this i'd recommend creating a higher order component or extend the data source and handle visibility there.

**Comment by ffriedl89** [comment]
Our recommendation is to create a higher-order component to deal with this logic since a pagination component should not handle visibility internally.
