### ISSUE TITLE
Chart selection: timeframe in the overlay is not updated

### ISSUE THREAD

**Issue by GustavAT** [dynatrace-oss/barista#608]
# Bug Report

## Expected Behavior

After setting the chart selection programatically, the timeframe in the selection overlay should be updated accordingly.

## Current Behavior

If having an existing selection and setting the selection programatically through the `value` property, the timeframe in the selection overlay still has the old value.

The value gets updated after hovering the chart.

## Steps to Reproduce

1. Select any range in the chart (i.e. by hand)
2. Set the selection programatically to some other value

You can paste the following snippets to the `chart-demo.component`.

```html
<button (click)="setTimeframe()">set timeframe</button>
```
```typescript
setTimeframe(): void {
  this.lastTimeframe = [
    this.lastTimeframe[0] - 100_000,
    this.lastTimeframe[1] + 100_000,
   ];
   this.dtChartRange.value = this.lastTimeframe;
}
```

## Context (Environment)

We have to add the selection based on some filters after loading data. This should override a selection done by previously by the user.

### Used Versions:

- **node**: 12.4.0
- **npm**: 6.13.7
- **typescript**: 3.4.3
- **angular**: 8.0.0
- **@angular/cdk**: 8.0.0
- **@dynatrace/barista-components**: 5.2.0

## Attachments

![selection-overlay-not-updated](https://user-images.githubusercontent.com/6452952/74665442-05ac0c00-51a0-11ea-9805-3c7e48004c1c.gif)

**Comment by tomheller** [comment]
Bug is reproducable in our dev application and demos application. 
After an initial investigation, it seems that the change detection does not trigger on the overlay. ChangeDetection seems to be disconnected from the ranges.
