### ISSUE TITLE
Event chart x-axis formatting

### ISSUE THREAD

**Issue by subarroca** [dynatrace-oss/barista#614]
# Bug Report

## Expected Behavior

X-axis formatting should not contain too many decimals

## Current Behavior

Currently x-axis may contain up to 9 or 10 decimals and overlaps with the next tick

## Possible Solution

Round the result to a given amount of decimals

### Used Versions:

- **node**: 12.0.0
- **npm**: 6.9.0
- **typescript**: 3.5.3
- **angular**: 8.2.14
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 5.1.1

## Attachments
![image](https://user-images.githubusercontent.com/1245057/74716292-86194e00-522e-11ea-91b9-5947f36f1a1e.png)

**Comment by tomheller** [comment]
Hi @subarroca! Thank you for reporting this. As @ffriedl89 told me, you are willing to take over this fix. Thank you very much for this one. 

If you need any help during the process, please feel free to reach out.
