### ISSUE TITLE
Card title "note"

### ISSUE THREAD

**Issue by myieye** [dynatrace-oss/barista#618]
# Feature Request

## Summary

Add an optional card title "note" to cards (see screenshot)

## Feature Description

In our code base we commonly include some small text beside a card title. It's often to display the current timeframe, but not always.

Newer screens have continued to use this pattern, but are simply implementing it manually, so I think it would make sense to make this a standard feature.

## Attachments

![image](https://user-images.githubusercontent.com/12587509/74745976-f8a52080-5264-11ea-911b-882838d906dd.png)

**Comment by tomheller** [comment]
Hi @myieye!

Thank you for that request. This seems pretty doable. A couple of things the contributor of this feature will have to look out for / think about: 

* Does it make sense to create a separate directive, so the card can select the `dt-card-title-note`?
* Layouting / Nesting: Should the element be nested into the `dt-card-title` or live next to it. What would the layout look like if the input would look like [1] and the output like [2], but positioning should be like shown in the attachment in the original post. How would we prevent the headline to not fill the whole space without a decent wrapper (when also keeping the subheadline in mind).
* Would it be enough to provide a style class, so the _note_ would not need to be styled manually?

[1]:
```html
<dt-card>
  <h2 dtCardTitle>My title</h2>
  <span dtCardTitleNote>Jan 10 2020, 15:39 - Today, 15:39</span>
</dt-card>
```

[2]: 
```html
<dt-card class="dt-card dt-card-has-header">
  <div class="dt-card-header">
    <div class-"dt-card-heading">
      <h2 class="dt-card-titlte">My title</h2>
      <span class="dt-card-title-note">Jan 10 2020, 15:39 - Today, 15:39</span>
    </div>
  </div>
</dt-card>
```

**Comment by ffriedl89** [comment]
@rrcaptain Can add your thoughts here please from UX perspective? Is this something we want to have?

**Comment by myieye** [comment]
@tomheller Thanks for your thoughts!

Based on your example, it would definitely be simpler to make the note a child of the title. That's how I've implemented it currently.

So what I've got is:
`
<dt-card-title>
    My title
    <dt-card-title-note>Jan 10 2020, 15:39 - Today, 15:39</dt-card-title-note>
</dt-card-title>
`

A css class would suffice, but a directive just adds that little bit of extra ease-of-use :D, but all we need are a specified margin and font settings.

**Comment by tomheller** [comment]
When looking at the current card setup, I question the lack of accessibility and role declarations. There are no roles defined on the `dt-card-title` [1] as well as on the `dt-card-subtitle` [2]. This seems a like an oversight on our end. This should not be part of this issue discussion here, but I'm inclined to at least consider aria-attributes on the title and subtitle, especially if we start nesting things into the title (which should semantically not be considered part of the header). 

[1]:
https://github.com/dynatrace-oss/barista/blob/04bed13cbfbca35307b83bcd9bc91ca867f46361/components/card/src/card.ts#L29-31
[2]:
https://github.com/dynatrace-oss/barista/blob/04bed13cbfbca35307b83bcd9bc91ca867f46361/components/card/src/card.ts#L49-L51

> As a directive, I guess the title would then have to select it.
The card-title is already a directive, which is being selected by the card itself. If we would want to achieve what you have proposed, we would need to change the `dt-card-title` to a component with a template like this:

```html
<ng-content></ng-content>
<span class="dt-card-title-note">
  <ng-content select="dt-card-title-note, [dt-card-title-note], [dtCardTitleNote]"></ng-content>
</span>
```

Imho, a css class that styles your custom span (or even a mixin to apply the style to the note would be a sufficient solution).

**Comment by myieye** [comment]
> Imho, a css class that styles your custom span (or even a mixin to apply the style to the note would be a sufficient solution).

Yes, I agree now. I'd prefer a class to a mixin. I'm not a pro at this stuff, can we put the styling inside dt-card without using ng-deep?

**Comment by tomheller** [comment]
> can we put the styling inside dt-card without using ng-deep?

I guess even if the card would provide that styling, we would still need to apply a selector like `dt-card ::ng-deep .dt-card-title-note` because we never know if there is a component with viewEncapsulation turned on is being nested into the `dt-card-title`. But this should be fine within the card component scope. 

We are still waiting for confirmation from @rrcaptain to confirm the UX perspective.

**Comment by myieye** [comment]
That would be a nice solution for me!

**Comment by rrcaptain** [comment]
We're trying to avoid the notes beside the title, it's an old solution for a complicated problem and a lot of users actually missed the notes as they're small and gray. Apart from that they don't work well if we keep responsiveness/accessibility in mind.

If a specified time frame is really needed, we'd rather have it written in normal body text beneath the title. This is only a workaround, we'll try to conquer the issue of "several time frames on one view" in our future designs, but there will not be a solution any time soon.
