### ISSUE TITLE
Table: changing dtSortActive is not updating boldness of new column

### ISSUE THREAD

**Issue by areknow** [dynatrace-oss/barista#619]
# Bug Report

## Expected Behavior

I expect a column to be bold when a matching value has been passed to `dtSortActive`.

## Current Behavior

The column does not become bold. The previous column remains bold. The new column shows the updated directional arrows. 

## Steps to Reproduce

https://stackblitz.com/edit/github-iwfjnb

### Used Versions:

All latest versions in stackblitz example.

**Comment by tomheller** [comment]
Hi @areknow! Thank you for reporting this. We were able to reproduce the problem and introduce a fix in #620.
