### ISSUE TITLE
Horizontally center empty states

### ISSUE THREAD

**Issue by myieye** [dynatrace-oss/barista#634]
# Feature Request

## Summary

Horizontally center empty states

## Feature Description

Horizontally center empty states in their container. It just looks way better (at least in tables?) especially in wider containers.

This can be implemented by simply adding:
```
.dt-empty-state-item-content-area {
  justify-content: center;
}
```

## Attachments

![image](https://user-images.githubusercontent.com/12587509/75147022-a8aed980-56fc-11ea-9a9b-57853f2a950c.png)
### vs.
![image](https://user-images.githubusercontent.com/12587509/75147053-ba907c80-56fc-11ea-8418-caba5a54145e.png)

**Comment by tomheller** [comment]
Hi @myieye! This seems a like a good idea, but we had that issue already. Did you test it with multiple empty state steps as well? Because this one was a bit of a problem when we tried this last. 

For UX input, @Marike-Sorgdrager do you want to weigh in here?

**Comment by myieye** [comment]
@tomheller Is the problem with multiple steps, that they wouldn't be perfeclty align with each other? After playing around with an empty state with multiple steps, I can't find any strange behaviour.

**Comment by tomheller** [comment]
I believe the problem was the responsive behavior of the multi stepped empty states. But if this issue has been fixed by some side effect, I guess this would be a good addition. Still waiting for the UX input on this one.

**Comment by MarikeAnne** [comment]
Hi guys. My only concern with centering it is that it's not set as a rule when it comes to empty states - > which would result in it being centered of a few pages and then left aligned on others. As this does not hinder the usability of the page and is purely based on styling I would recommend staying consistent and wait for it to be clarified at a later stage. Even though it does look better on your screens, we need to stay consistent.

**Comment by myieye** [comment]
> My only concern with centering it is that it's not set as a rule when it comes to empty states

@MarikeAnne I don't quite understand. I'm basically proposing that it **is** set as a rule :)

**Comment by myieye** [comment]
OK, I'll let UX open this topic again when they're ready.
