### ISSUE TITLE
Add sort direction Input to simple-number-column

### ISSUE THREAD

**Issue by myieye** [dynatrace-oss/barista#637]
# Feature Request

## Summary

`dt-simple-number-column` has a sort direction of `desc`. I think that's a good default, but that it should be settable.

## Feature Description

Sorting numbers in descending order often makes sense, but there are certainly cases when sorting them in ascending order is more desirable. For example, we sort browser monitor availability in ascending order so that the more problematic monitors are at the top.

Or course I could make my own column, but I just want to set one parameter and I think that `asc` is a valid initial sort order for numbers. So, I think that the sort order of `dt-simple-number-column` should be configurable.

Currently I can use `dtSortActive="availability" dtSortDirection="asc"` so that the column is initially ordered with `asc`, but then if I change the sorted column and switch it back to availability again, then it is initially sorted with `desc`.

**Comment by tomheller** [comment]
This was initially requested by UX and POs, that there is a consistent sorting behavior on number columns. The decision to not make this configurable on simple-columns was a conscious one.

My opinion would be, to not make this configurable. @ffriedl89 @Marike-Sorgdrager, what would be your take on this one?

**Comment by ffriedl89** [comment]
@myieye Thanks for the feature request. I have to agree with @tomheller here. This was a lengthy discussion in the past and it was a conscious decision to have this set internally. If you have an edge case to sort numbers differently you can always create your own simple-column. But as part of the library it makes sense to keep it as is.
