### ISSUE TITLE
Make Add Tag button styles more specific

### ISSUE THREAD

**Issue by myieye** [dynatrace-oss/barista#640]
# Feature Request

## Summary

Make the Add Tag button more independent from user agent styles.

## Feature Description

The Add Tag button currently relies on button padding that is set by the user agent style sheet. Our normalize.css overrides this padding and makes the button look yucky (see screenshot). Because "Add Tag" is not a standard button, I think it would make sense for it to style itself more excplicity instead of relying on user agent styles.

All it needs is an explicit padding of `2px 6px 1px 6px`.

## Attachments

![image](https://user-images.githubusercontent.com/12587509/75255286-f7826f00-57e1-11ea-92d6-4affd4d01c1d.png)

**Comment by tomheller** [comment]
Hi @myieye Thank you for reporting this. This is a good point and we will see that this is being taken care of. 
Are you willing to make that contribution?

**Comment by tomheller** [comment]
@myieye I quickly started an investigation into this one, and I don't seem to be able to reproduce the problem in our demo app.
Firefox:
![image](https://user-images.githubusercontent.com/6338434/75315300-b1212480-5862-11ea-84d2-5b650c2dbba8.png)

Edge 18
![image](https://user-images.githubusercontent.com/6338434/75315322-c1390400-5862-11ea-8571-874c403b3c6e.png)

Chrome
![image](https://user-images.githubusercontent.com/6338434/75315330-c5fdb800-5862-11ea-948c-0a29c7049f0d.png)

Granted, edge18  looks a little bit off, but not what you are showing here. 
I guess that not the padding is the problem, but the missing border box sizing, that should be set on the tag-add instead. I will see if this is the case.
