### ISSUE TITLE
Create THE stackblitz example template

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#656]
# Feature Request

## Summary

I want to easily start prototyping with the components on stackblitz

## Feature Description

Provide one stackblitz template that has all the modules configured where you can start prototyping right away without handling importing certain modules.

**Comment by tomheller** [comment]
Provided prototyping example in the [barista-examples repository](https://github.com/dynatrace-oss/barista-examples/tree/master/prototype), creating template link is:
https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/prototype/?file=src%2Fapp%2Fapp.component.html
