### ISSUE TITLE
[collection] broken stackblitz-examples

### ISSUE THREAD

**Issue by petrabrunner** [dynatrace-oss/barista#657]
## Expected Behavior
I expected the stackblitz examples to be (visually) exactly the same as they were in the barista-ui. (interal version). 

## Current Behavior
the following components were somehow broken (see screenshots) when opened in stackblitz:

- DtExampleTopBarNavigationDefault - errors in console, mybutton and burger-icon not visible 
![image](https://user-images.githubusercontent.com/45869415/75450546-54f7f680-596f-11ea-81b8-d8fcaba21a19.png)
- DtExampleTopBarNavigationDrawer - errors in console, mybutton and burger-icon not visible 
![image](https://user-images.githubusercontent.com/45869415/75450321-e024bc80-596e-11ea-8d62-e21e60aa260a.png)

- DtExampleCtaCardDefault ![image](https://user-images.githubusercontent.com/45869415/75448983-7e635300-596c-11ea-90c3-a362d0aa3c78.png)

- DtExampleCtaCardClosable was seemingly empty -edit- same console-error as TopBarNav-examples ![image](https://user-images.githubusercontent.com/45869415/75449511-64764000-596d-11ea-97f8-415b9cc3cbd1.png)
_note: I just saw that the DTCard is depricated... maybe thats why it doesn't work..._

- DtExampleBreadcrumbsDefault - was not really broken - but required installing some packages before it was view-able (was done via button-click and stackblitz-background workers) so thats just an fyi! 
![image](https://user-images.githubusercontent.com/45869415/75450498-3b56af00-596f-11ea-8dce-69349b6ea015.png)

I will continue to extend the list of broken examples as I find them (if I find others). 

## Steps to Reproduce
I opened the provided "Open in StackBlitz" link for each of the listed components.

**Comment by ffriedl89** [comment]
Thank you Petra for reporting this, we will have a look 👍

**Comment by tomheller** [comment]
Progresstracker for broken examples:

* [ ] DtExampleTopBarNavigationDefault
* [ ] DtExampleTopBarNavigationDrawer
* [ ] DtExampleCtaCardDefault
* [ ] DtExampleCtaCardClosable
* [ ] DtExampleBreadcrumbsDefault

**Comment by ffriedl89** [comment]
- [ ] https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleTreeTableProblemIndicator/
- [ ] https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleChartDefault/
- [ ] https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleIconDefault/
- [ ] https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleEmptyStateInCard/
