### ISSUE TITLE
Overlay: Add additional strategies for capturing clicks outside pinned overlays

### ISSUE THREAD

**Issue by deeleman** [dynatrace-oss/barista#670]
# Feature Request
The current implementation for overlays allows for pinnable overlay elements. When setting overlays as pinnable, a backdrop element spreading across the viewport is added in the background to capture clicks outside the overlay element in order to dispatch a close action of the aforementioned overlay.

Unfortunately, this backdrop element overlaps over the rest of the UI so mouse interactions such as mouseover might not work as expected and clicking on any interaction element will require the user to click twice in order to get the pinned overlay removed on the first click. 

## Summary

We need to extend the overlay configuration options to enable additional strategies for capturing clicks for disposing the pinned overlay that does not entail a blocking background layer overlapping the rest of the UI. 

## Feature Description

A proposed workaround would be to add an additional CaptureClickOutsideOverlay directive that component consumers can add to their own implementations in order to capture click events propagated thru event delegation to parent elements. Placing that directive in an outer element would turn it into a click-capture device that would destroy pinned overlays by inspecting whether the target element fo the event source is the overlay or not, if any. This should come in combination with a config option that disables the default backdrop element triggered by default on pinned elements to capture click events.

**Comment by thomaspink** [comment]
Agree that clicking on transparent backdrops is not ideal. Would propose a solution to change overlays that have these transparent backdrops, to change to a `clickOutside` solution as done in the autocomplete.
