### ISSUE TITLE
Rethink our current PositionStrategy for our Overlays

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#671]
As [part of reworking our overlays](https://github.com/dynatrace-oss/barista/issues/86), we also need to rethink the position strategy:

First, let's evaluate if we even need a custom PositionStrategy? Whats the benefit for the user if the overlay follows the mouse?

If we do need a custom strategy, let's define and write down a clear ruleset how the overlay should behave in each situation. This ruleset should be defined first to avoid misunderstandings (everyone is on the same page) and have clear path (checklist) for developing it later.

**Comment by ffriedl89** [comment]
I think this is a relevant discussion to have. I don't see a use case where a user benefits from our current position strategy that the overlay needs to follow the mouse while hovering an element. 
We had a lot of edge cases, especially with SVG elements where this was really problematic. To avoid all these cases we could opt for a position-strategy that is connected to an element. 
Current issues that would be solved by using a connected position strategy: 
#401 
#220

For cases like the session replay timeline, we could still use a connected position strategy with the point given on the timeline. The CDK's FlexibleConnectedPositionStrategy can also take x & y coordinates for positioning.

**Comment by ffriedl89** [comment]
Looping in UX @kathrin_aigner

**Comment by ffriedl89** [comment]
@deeleman & @allexcd I guess your use case for session replay would be the most affected one by a change like this. 

The current plan would be to have the normal FlexibleConnectedPositionStrategy from the CDK used for all our overlays with the following positions used: 
```
[{
  originX: 'start',
  originY: 'bottom',
  overlayX: 'start',
  overlayY: 'top',
},
{
  originX: 'start',
  originY: 'top',
  overlayX: 'start',
  overlayY: 'bottom',
},
{
  originX: 'start',
  originY: 'bottom',
  overlayX: 'end',
  overlayY: 'top',
},
{
  originX: 'start',
  originY: 'top',
  overlayX: 'end',
  overlayY: 'bottom',
}]
```
For the timeline in session replay this would mean to call updatePosition with the mouseposition and use a Point as a reference - see https://material.angular.io/cdk/overlay/api#FlexibleConnectedPositionStrategyOrigin

**Comment by kathrin-aigner** [comment]
From a UX perspective we recommend tooltips that are dependent on objects rather than mouse. With mouse dependent tooltips readability can suffer in some cases and this behaviour causes bugs. Exceptions would be charts, where the tooltips should follow the mouse. Additional exceptions can emerge as soon as we further investigate the behaviour of tooltips.
