### ISSUE TITLE
Create a "Prototype" page in Barista

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#677]
I want to promote our prototype capabilities prominently in Barista. Let's create a "prototype" page with the new full blown stackblitz example @tomheller created with #656 

I think the homepage should have a prominent link to this page. 

@dynatrace-oss/barista What do you think?

**Comment by ffriedl89** [comment]
My suggestion would be to add a page teaser that links to a prototyping page within barista.
@lara-aigmueller Do you have some tips for structuring the content :) ?

**Comment by lara-aigmueller** [comment]
Hm, I'm not sure what the content should be? Basically it will be a short introduction text and after that the example, right?

Where should the page live in Barista?

@ffriedl89

**Comment by ffriedl89** [comment]
I think the best place is located under resources, I'll create a page and align with @ursula-wieshofer about the content :)

**Comment by ffriedl89** [comment]
After further discussion - the page is a bit off when placed inside resources. The most obvious place for me was inside the getting started section.
