### ISSUE TITLE
Investigate Algolia for public barista search

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#679]
Start investigating Algolia for the public search of Barista. Try to limit the API surface of Algolia to a rest endpoint so we can easily switch to a internal search tool for the internal version of Barista.

**Comment by tomheller** [comment]
This one relies on #626 and #504 for serverside rendering and also a public version of barista, so we will hold off on that one.

**Comment by tomheller** [comment]
We will need to add the algolia logo next to the search, once we have integrated it.
https://www.algolia.com/press/?section=brand-guidelines
