### ISSUE TITLE
Create internal search

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#680]
# Feature Request

For the internal search we need a node app running and crawling the content internally. Goal is to have an API close or similar to the rest endpoint used by algolia to trigger a search. 

#679 is tightly coupled to this issue

**Comment by tomheller** [comment]
Internal search has been built. I will need to wait for some support to get this deployed...

**Comment by tomheller** [comment]
The internal search will require a server side rendered version of barista, to be able to crawl it successfully. 
This issue relies on #626 and its fix.
