### ISSUE TITLE
Switch: contrast of disabled switch label is not enough

### ISSUE THREAD

**Issue by ursula-wieshofer** [dynatrace-oss/barista#684]
# Bug Report

## Expected Behavior

When a switch is disabled, the switch itself should change the color, but not the text/ label next to the switch, as users should still be able to read this. With the current text color we don't meet our accessibility standards ;) 

## Possible Solution

Best solution would be to disable the switch but not the text / label. The label should be visible in our standard font color.

![Screenshot 2020-03-02 at 13 55 54](https://user-images.githubusercontent.com/36620967/75678278-92b98f80-5c8d-11ea-9886-9d11c2de1833.png)

**Comment by tomheller** [comment]
Thank you for reporting this, @ursula-wieshofer. This seems like a valid request.

**Comment by tomheller** [comment]
@ursula-wieshofer Did you check the other input types here as well? At first glance there seem  to be a couple that suffer that issue:

Radio button:
![Radio button - disabled label not showing enough contrast](https://user-images.githubusercontent.com/6338434/75867860-848f7e80-5e07-11ea-85f8-8a5b23aef05a.png)

Form field placeholders and hints:
![Form field with placeholder text and hints showing not enough contrast](https://user-images.githubusercontent.com/6338434/75867929-9cff9900-5e07-11ea-8825-61dab7f984cd.png)

Checkbox:
![Checkbox disabled label not showing enough contrast](https://user-images.githubusercontent.com/6338434/75868044-ca4c4700-5e07-11ea-891d-1039aab78f02.png)

There would be automatic contrast checks in our a11y tests, but we have disabled most of them right now, as they would crash the builds of our design system. If this is something we want to tackle soon, we can go over the violations offline.

**Comment by ursula-wieshofer** [comment]
@tomheller imho I think we should change the fonts for all these components.

**Comment by tomheller** [comment]
I'm fixing the radio, checkbox and switch labels within the #702. 
@ursula-wieshofer I think we should discuss placeholder texts in general, as they are a highly controversial topic.
If we make the change to the placeholder texts within the input and form fields, they will be visually the same as if the user would have entered a value. This tends to get confusing and does not help the user to determine which fields should be filled out and which ones already have values in them.
