### ISSUE TITLE
Top bar items don't show an outline when selected with keyboard

### ISSUE THREAD

**Issue by SkaillZ** [dynatrace-oss/barista#692]
# Bug Report

## Expected Behavior

There should be an indicator for a `dt-top-bar-navigation-item` that is currently keyboard-focused.

## Current Behavior

Items can be selected via the keyboard but there is no indicator for the selected item.

## Steps to Reproduce

1. Open any documentation page that contains top bar items
2. Focus any item

**Comment by tomheller** [comment]
This is correct and currently missing from the top-bar-navigation. We are happy to accept contributions on this one.
