### ISSUE TITLE
DtTagList shows "0 more ..."

### ISSUE THREAD

**Issue by ermin-muratovic** [dynatrace-oss/barista#695]
# Bug Report

## Expected Behavior

If all tags are shown the expand link "0 More ..." should not be displayed.

## Current Behavior

All tags are shown and the link "0 More ...".

![image](https://user-images.githubusercontent.com/6098219/75980902-a65e3380-5ee3-11ea-9105-ee85fbe15ef9.png)

## Steps to Reproduce

The issue can be reproduce on https://bridge2.keptn.gke.demo.keptn.sh/

On first load it works correct. When clicking on a project and afterwards going back to the overview by clicking on the keptn icon the data is already loaded and the view shows immediately with the "0 More ..." in the tag list.

### Used Versions:

- **node**: 12.13.1
- **npm**: 6.12.1
- **angular**: 8.3.25
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 5.1.1

**Comment by ffriedl89** [comment]
@ermin-muratovic Can we close this issue since it's already fixed in 5.3.1?

**Comment by tomheller** [comment]
It was fixed as part of the 5.2.0 release. @ermin-muratovic if it is possible, please upgrade to the version 5.3.1 or 6 of barista-components. If the bug still exists, please let us know and reopen this issue.

**Comment by ermin-muratovic** [comment]
Updating to 5.3.1 fixed the issue. Thanks.
