### ISSUE TITLE
filter-field: Filter value is ignored if entered too fast.

### ISSUE THREAD

**Issue by uygaruyaniksoy** [dynatrace-oss/barista#726]
# Bug Report
## Expected Behavior

When I type a text to unique filter field too fast (around under 200ms) and hit enter, the filter value is expected to be shown in the current filter.

## Current Behavior

Typed value is ignored and an empty filter value is displayed.

## Steps to Reproduce

1. Select a filter key
2. Type a short text very fast (e.g. under 100ms).
3. Hit enter
4. Observe filter value is ignored by the filter component.

![broken](https://user-images.githubusercontent.com/20678081/76508015-01e17180-644e-11ea-9f61-db890a08e8b5.gif)

## Context
It's broken in the internal barista page: https://barista.lab.dynatrace.org/components/filter-field#unique-free-text-or-range-options

### Used Versions:
I was also able to reproduce it locally.
- **node**: 12.14.1
- **npm**: 6.13.4
- **typescript**: 3.7.5
- **angular**: 9
- **@angular/cdk**: 9.1.0
- **@dynatrace/barista-components**: 6.0.1

**Comment by tomheller** [comment]
Hi @uygaruyaniksoy !
Thank you for reporting this. We have run into this issue in the past and it is kind of a tricky one. 
Basically you are in a race against the angular change detection cycles at this point. 
We have tried to tweak it to a point where this is less frequent. We'll see if we can fix this once and for all.

**Comment by tomheller** [comment]
If you have any idea on how to fix this consistently within the filter field, we would happily accept a contribution.

**Comment by OFouda** [comment]
hi guys, would just like to add that I've also run into this a few times. its now more evident with UI tests since my test always fails because it tries to select the filter option too fast

**Comment by tomheller** [comment]
We have run into the same issue with the UI tests. But with the current architecture of the filter-field and how it relies on the angular change detection, this is really hard to fix. We had to resort to slow down our filter-field tests that check the behavior here.

https://github.com/dynatrace-oss/barista/blob/9f3c0478d0ba12f28f8eb20fc10bcdeb768012f3/apps/components-e2e/src/components/filter-field/filter-field.e2e.ts#L168-L194

We will continue to investigate how we can fix this issue, but it seems more and more to point to a complete rewrite of the filter-field. The requirements for the filter field have increased during it's development, which required us to bend a lot.

**Comment by OFouda** [comment]
I understand, I have also added a delay to my UI test but thought to bring it up here since I have also manually run into the issue a couple of times.
Thanks for looking into it

**Comment by tomheller** [comment]
@OFouda You are right to bring that up, and to be quite honest, we have also manually ran into this issue manually. 
My current approach would be to eliminate the internal representation of the inputValue and rely on the value of the nativeElement. This could lead to some synchronizing problems between ChangeDetection update cycles and native inputs value updates. I have a draft of the changes ready and already shared it with the code owners of the filter field to discuss if and how we would deal with sideEffects.
