### ISSUE TITLE
SelectionArea: Overlay should be closed if ESC keyboard button is pressed

### ISSUE THREAD

**Issue by Sherif-Elhefnawy** [dynatrace-oss/barista#745]
# Feature Request

After discussion on #725 , it was decided in according with the UX team that the overlays for the ~chart heatfield~ (Done in #816) and selection area should be closed if the user presses the "ESC" button on their keyboard to align to the same behavior as the context dialog.

**Comment by tomheller** [comment]
@ffriedl89 @Sherif-Elhefnawy I guess this has been solved by #816 as well?
Can we close this issue?

**Comment by Sherif-Elhefnawy** [comment]
@tomheller , the selectionArea doesn't have that ESC behavior yet unfortunately

**Comment by tomheller** [comment]
Thank you for clarifying, I'll adjust the issue accordingly to not be misleading.
