### ISSUE TITLE
Table Loading State might be displayed out of current viewport

### ISSUE THREAD

**Issue by christian-fischer** [dynatrace-oss/barista#747]
# Bug Report

## Expected Behavior

I would expect to see the table loading distractor regardless of viewport position

## Current Behavior

The table loading distractor is displayed exactly in the middle of the table. 
When there is a bit more data in the table (more than two screen heights), the loading distractor is not visible, when we are scrolled to the top of the page.

## Possible Solution

Fixed position for table loading distractor.

## Steps to Reproduce

1. see reproducer https://stackblitz.com/edit/github-zfhpq7

## Context (Environment)

More than two screen heights of table data

### Used Versions:

- **@dynatrace/barista-components**: "6.0.1",

**Comment by tomheller** [comment]
Hi @christian-fischer!
Thank you for bringing this up, I will loop in our @dynatrace-oss/ux-core team, as they may have an opinion on this one as well. 

I'm also changing the issue to a feature request, because as of right now, the table in combination with the loading state work as designed. This does however not mean that this is not subject to change.

**Comment by ursula-wieshofer** [comment]
I would rather invest development time in building something like a sceleton loading than waisting time with our annoying loading distractor. But I'm not sure if this is even feasible or realistic :smile:
I get the problem of Christian, but how often does it occur? We could show the loading distractor horizontally centered but vertically always underneath the table header!?

The UX component owner Marike Sorgdrager also raised awarness of an open issue which might  assist with this issue already:
https://github.com/dynatrace-oss/barista/issues/287

**Comment by Marike-Sorgdrager** [comment]
For now, I'd suggest keeping things simple and just making the proposed changes for the empty and loading state discussed in the issue @ursula-wieshofer just mentioned. It is not the perfect solution, but it at least already solves some part of the problem.
