### ISSUE TITLE
Filter Field: Support of multiple Range Operators and extend Range Operations (>, <)

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#75]
Extend operator list for range selections in filter field with greater and lesser operators. 

This is how it is currently implemented in the product: 
![image](https://user-images.githubusercontent.com/6338434/72409658-b3259d00-3766-11ea-81d8-8f60ba040d3c.png)

I think we should talk about the design of it with the UX team.

**Comment by moertenschlag** [comment]
Any plans, when this will hit production?

**Comment by tomheller** [comment]
Hi @moertenschlag! Unfortunately we did not have time to start with this one. There are also some UX questions still open, that we are trying to sort out. 
If you would be open to contributing this feature to the library, we will of course support you every step of the way.
