### ISSUE TITLE
Fix tslint and prettier combination / Migrate to Eslint

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#755]
As of now, tslint (in version ~6.0.0) does not work with rules that are defined in the `.prettierrc` file. Violations like `trailingCommas: always` are not validated by the linting tasks. They should be covered by the precommit hook, but somethimes it seems these slip through the crack. We have upgraded the version of `tslint-plugin-prettier` to version 2.2.0, since this is the first version that supports tslint 6 and above in #754. Maybe this has fixed the problem of the precommit hook.

As tslint is deprecated since version 6.0.0 to encourage people and maintainers to move over to eslint ([Changelog notice of tslint](https://github.com/palantir/tslint/releases/tag/6.0.0)) we should also think about moving over to eslint. 

Communication from the angular team is, that angular will support the switch over to eslint with version 10 of angular ([Comment within a thread discussing the switch](https://github.com/angular/angular-cli/issues/13732#issuecomment-573149865)).

What needs to be done for the switch: 

* [ ] Migrate all tslint.json files over to the eslint format
* [ ] Make sure that eslint and prettier are still working together
* [ ] Create duplicates of our custom linting rules that work for eslint
* [ ] Make sure we deprecate the tslint support and encourage users of the library to move over to eslint as well. We should ship the tslint versions of our custom rules until version 8.0.0 of the library to give people time to migrate. 
* [ ] Remove all dependencies to tslint and tslint-plugins.

**Comment by ffriedl89** [comment]
Interesting resource to migrate our rules to eslint
https://timdeschryver.dev/blog/migrating-a-tslint-rule-to-eslint-with-typescript-eslint

**Comment by lukasholzer** [comment]
We can do a partial transition of eslint and tslint our nx workspace would support that so having two different interest. for all angular related stuff still tslint and for the node libraries etc. migrate to eslint.
