### ISSUE TITLE
[Chart] Add support for observable input in options

### ISSUE THREAD

**Issue by rarenal** [dynatrace-oss/barista#756]
# Feature Request
Add support for a stream (`Observable`) as input for DtChart **options** field.

## Summary
Following **DtChart** component doc, there are two main `@Input()` in order to build a chart, being those:

`options: DtChartOptions | undefined;`
`series | Observable<Highcharts.IndividualSeriesOptions[]> | Highcharts.IndividualSeriesOptions[] | undefined;`

In order to keep cohesion between those input and to support both dynamic and static inputs, this requests aims to support streams as an input for `options` field.

## Feature Description
Accept a stream as input for `options` field in `DtChart`:
`options; Observable<DtChartOptions> | DtChartOptions | undefined`
And handle that stream in the `DtChart` component to fully support it.

**Comment by tomheller** [comment]
Hi @rarenal !

This seems like a good idea to keep things consistent within the chart component. After a first investigation, this seems like a simple fix.
The input here should be easily extendible to also accept an observable and next an internal options BehaviourSubject.

https://github.com/dynatrace-oss/barista/blob/2709b1640bc06501f5e5ed853887f08e88a97fab/libs/barista-components/chart/src/chart.ts#L237-L244

Keep in mind that we join the input options with ones that are provided by default, when the option changes:
https://github.com/dynatrace-oss/barista/blob/2709b1640bc06501f5e5ed853887f08e88a97fab/libs/barista-components/chart/src/chart.ts#L442-L446

We call the update function, which would also need to be called if the internal BehaviourSubject is nexted: 
https://github.com/dynatrace-oss/barista/blob/2709b1640bc06501f5e5ed853887f08e88a97fab/libs/barista-components/chart/src/chart.ts#L516-L535

Would you be willing to contribute this to the library?
