### ISSUE TITLE
Chart HeatField: Incorrect behavior with overlapping heatfields

### ISSUE THREAD

**Issue by Sherif-Elhefnawy** [dynatrace-oss/barista#765]
# Bug Report

## Detailed Description

When using multiple heatfields in the chart with overlapping times, incorrect behavior tends to happen when the heatfield order is changed.

For example with this code:

`<dt-chart [options]="options" [series]="series">
  <dt-chart-heatfield [start]="20000" [end]="60000">
    Problem 1:
    <br />
    <a class="dt-link">View problem details</a>
  </dt-chart-heatfield>
  <dt-chart-heatfield [start]="40000" [end]="60000" color="main">
    Overload prevention:
    <br />
    <a class="dt-link">View overload prevention</a>
  </dt-chart-heatfield>
</dt-chart>
`

This is produced, which is correct behavior:
![image](https://user-images.githubusercontent.com/59170440/77064414-beec4480-69df-11ea-9e15-89ac0bd64fe5.png)

However, if the times are switched around like so:
`
<dt-chart [options]="options" [series]="series">
  <dt-chart-heatfield [start]="40000" [end]="60000">
    Problem 1:
    <br />
    <a class="dt-link">View problem details</a>
  </dt-chart-heatfield>
  <dt-chart-heatfield [start]="20000" [end]="60000" color="main">
    Overload prevention:
    <br />
    <a class="dt-link">View overload prevention</a>
  </dt-chart-heatfield>
</dt-chart>
`

The second heatfield overlaps the first one completely which is incorrect:
![image](https://user-images.githubusercontent.com/59170440/77064510-e5aa7b00-69df-11ea-841d-8cac07f8d97d.png)

## Stackblitz Link
https://stackblitz.com/edit/github-palqu9?file=src/chart/chart-heatfield-multiple-example/chart-heatfield-multiple-example.html

**Comment by Sherif-Elhefnawy** [comment]
After discussing with @ffriedl89 , we thought about adding a two-lane approach, top and bottom, and specify it per heat-field.
By default, the heat-field would be in the bottom lane. 
Something alone lines of this:
![image](https://user-images.githubusercontent.com/59170440/77075648-f2849a00-69f2-11ea-97f3-9e471f123bae.png)

**Comment by tomheller** [comment]
@Sherif-Elhefnawy This sounds and looks a very valid approach. As the heatfield at this point can only take the `main` and `error` states, this should be feasible to build. 
I'm guessing we should consider input from @dynatrace-oss/ux-core or @kathrin-aigner before starting implementation on this one.

**Comment by kathrin-aigner** [comment]
@Sherif-Elhefnawy @tomheller looks good to me, I think the screenshot is already from the mock that I did some months ago so the approach is already discussed and we can give it a go!

**Comment by SkaillZ** [comment]
@Sherif-Elhefnawy Would you like to contribute this to our library? A small API proposal with the changes you want to introduce would be helpful (please double-check that no breaking changes are introduced). We'd help you if you have any questions, so feel free to reach out to us.

**Comment by Sherif-Elhefnawy** [comment]
@SkaillZ , thanks for offering the help. I will do so when I come around to this again :)
