### ISSUE TITLE
Filter Field: dropdown closes after clicking the filter-field

### ISSUE THREAD

**Issue by GustavAT** [dynatrace-oss/barista#768]
# Bug Report

## Expected Behavior

The dropdown stays open after clicking the filter-field.

## Current Behavior

The dropdown opens and immediately closes after clicking in the filter-field.

## Steps to Reproduce

Note: this is a very special edge case I discovered :). See attached gif.

1. Add some filters to fill up the first line of the field (does not matter which filters). Note: the `clear all` button has to be in the same line as the filters. The filter-field will add one additional line and places the underlaying input-element there.
2. Click the input-element
3. The dropdown does not stay open

## Context (Environment)

An automated acceptance test uses the underlaying input-element to select filters. It fails however, because the dropdown closes immediately after clicking.

### Used Versions:

- **node**: 12.4.0
- **npm**: 6.14.2
- **typescript**: 3.7.5
- **angular**: 9.0.6
- **@angular/cdk**: 9.1.0
- **@dynatrace/barista-components**: 6.0.0

## Attachments

![filter_field_dropdown_bug](https://user-images.githubusercontent.com/6452952/77070953-7f2b5a00-69eb-11ea-85e1-182685f7cded.gif)

**Comment by tomheller** [comment]
Hi @GustavAT! 
Nice catch on this one. As you have mentioned this is a very edge case and probably also very tricky to solve. 
As per UX requirement, the clear all button needs to appear when blurring the filter field. At which point it requires it's width. The input field itself is always there and always takes the ~300px space given to it. This might result in creating a second line in the filter field. 

I'm not sure if we can tackle this one any time soon and given it's edge-case situation, I believe it too not be as critical.
I will add a priority-4 and a help-wanted label onto it. If you have any thoughts on fixing this one, help is as always appreciated.
