### ISSUE TITLE
Overlay is misplaced for trigger element consisting of mutiple elements

### ISSUE THREAD

**Issue by hubert-grininger** [dynatrace-oss/barista#772]
As discussed with Lukas:

See example:
https://github-slwyzc.stackblitz.io

When you hover over the first element everything is fine, hovering over "=" or the last word you see that the overlay is misplaced.

**Comment by hubert-grininger** [comment]
![screenshot-1](https://user-images.githubusercontent.com/62534476/77285912-7af48a80-6cd2-11ea-91ef-d1681ef736d5.png)

**Comment by tomheller** [comment]
@hubert-grininger Could you please check the provided link to the stackblitz example? When I open it, it points to our default example. Which seems to work fine.
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/6338434/77289297-f9a0f600-6cd9-11ea-9a2a-28b8dad8ac06.png">

**Comment by hubert-grininger** [comment]
Sorry, was too stupid to fork correctly:

Hopefully this works now:
https://stackblitz.com/edit/github-slwyzc-neytpd?embed=1&file=src/overlay/overlay-complex-content-example/overlay-complex-content-example.html

**Comment by tomheller** [comment]
@hubert-grininger No worries, forking in stackblitz is really weird. The example now works and in chrome it also shows the faulty behavior. It seems to work in firefox, which does not make me happy 😭.
(Probably relates to #671)

**Comment by ffriedl89** [comment]
Thanks @hubert-grininger for reaching out, I already have an idea on how to fix this - it is connected to our faulty MouseFollowPositionStrategy. I'll take a look and try to fix this once and for all.
I've already synced with @dynatrace-oss/ux-core and we agreed to not use the follow strategy anymore and switch to a static overlay. This should also fix this issue.
