### ISSUE TITLE
Filter Field: Add support for validators for the range inputs

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#78]
Add support for validators for the inputs in the range of the filter field.
Check out the validators for the free text nodes, find a similar solution

**Comment by moertenschlag** [comment]
@ffriedl89 
Is there any update on this.
We currently have the requirement to disallow floating point operations for certain inputs.

**Comment by bmrozinski** [comment]
I would like to use range / less than / greater than filters for version numbers (eg. 1.190.1). Therefore it would be great to allow not only numeric input. 

Solutions: 
1. Allow any string as an input for range filter with some kind of regex validation. 
2. Allow autocomplete option in range filter with provided predefined values to choose from.

**Comment by tomheller** [comment]
Hi @bmrozinski! In general the range is not intended to be used for arbitrary ranges, like versions but rather for numerical ranges. We would be able to open up its intended use with the introduction of validators. 
Would you be willing to contribute this feature to the library. We would of course support you in this quest and guide you through the process.
