### ISSUE TITLE
Barista: Page is blocked from indexing

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#800]
# Bug Report

According to Google Lighthouse audit the page is blocked from indexing:

https://web.dev/is-crawable?utm_source=lighthouse&utm_medium=cli

![image](https://user-images.githubusercontent.com/11156362/77657423-93380400-6f75-11ea-8d4b-a32f859ee5bb.png)

**Comment by ffriedl89** [comment]
Which site are you referring to?

**Comment by tomheller** [comment]
The `x-robots: noindex` is only set for staging builds on zeit, to not index staging environments (which seems to be a good thing). 
The header tag is not present on the `production` system.
