### ISSUE TITLE
Align sizing of dt-icons with pattern guideline.

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#827]
Currently the size of a `dt-icon` is handled by the consumer by either setting the size of the container element in which the icon is rendered (the dt-icon takes the space it gets) or via css. 

This leads to a non-uniform way of different icon sizes (every consumer can define it's own size depending on its use-case) and contradicts the pattern that icons can only have one of a specified [set of sizes](https://barista.dynatrace.com/patterns/common-ui-styles#icon-sizes).

It also shifts some wort to the consumer where everyone has to specify their own sizes (in multiple instances) even if they are the same.

A suggested and possible solution would be to introduce a `size` input property where only the mentions [sizes](https://barista.dynatrace.com/patterns/common-ui-styles#icon-sizes) are allowed.

UX should also be involved if it is possible to limit the sizes of icons to only these.

**Comment by tomheller** [comment]
@dynatrace-oss/ux-core Do you have any opinions on that one. Do we want to limit the sizes of icons to the ones listed on guidelines @thomaspink shared?

**Comment by ursula-wieshofer** [comment]
Hi @thomaspink and @tomheller sorry for letting you wait so long.
I think it would be very helpful to have the icon sizes as tokens we can change once. If that is not too much effort I'd suggest we do this as it would help to create our UI more consistent.

**Comment by tomheller** [comment]
@ursula-wieshofer This works for me, the only question would now be: What token do we default to, when no size is given?
For a grace period I guess we should keep the behavior as is, so the icon sizes itself based on the container and give a warning if it is not set, so people have time to adapt their screens.

**Comment by ursula-wieshofer** [comment]
@tomheller in our guideline here https://barista.lab.dynatrace.org/patterns/common-ui-styles#icon-sizes it says that S (20px) is the default, so I'd go with this. But I agree, having this as a warning would be great ;)
