### ISSUE TITLE
Open active section in secondary-nav on init

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#828]
Right now, every consumer has implement a way to open the section of an item that has been set to active by their own. This should be handled by the component, because as it looks like this is a default behaviour most (every) consumers implement.

Proposal:
A section should automatically expand if it contains an active item (link) on init.

Code-wise adding this feature can be tricky because first we need to find a way how to determine which link is active before rendering so the correct expand value can be set.

**Comment by thomaspink** [comment]
cc @areknow

**Comment by areknow** [comment]
@thomaspink this behavior is included in the PR with the breaking change to the component 👍

**Comment by thomaspink** [comment]
Great to hear. Thanks a lot

**Comment by tomheller** [comment]
Closed by #734
