### ISSUE TITLE
Filter field: autocomplete stays open when clicking into another filter field

### ISSUE THREAD

**Issue by evan-bradley** [dynatrace-oss/barista#840]
# Bug Report

## Expected Behavior

The autocomplete in a filter field should close when clicking into another filter field, just like it would for anywhere else in the page.

## Current Behavior

When clicking directly into two filter fields, the autocomplete menus for both will be open.

## Possible Solution

This likely sources from the filter field swallowing the click event in the [_handleHostClick](https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/filter-field/src/filter-field.ts#L572) method.

## Steps to Reproduce

StackBlitz: https://stackblitz.com/edit/github-dixtrt

1. Click into top filter field (the autocomplete will open)
2. Without clicking anywhere else on the page, click into the bottom filter field
3. Both filter fields will have their autocomplete menus open now.

## Context (Environment)

We are currently presenting the user with an option to manage two sets of filters on a single set of tag data. The filter fields are close to each other, so can be activated at the same time.

### Used Versions:

- **node**: v12.13.0
- **npm**: 6.14.1
- **typescript**: 3.8.3
- **angular**: 9.0.6
- **@angular/cdk**: 9.1.0
- **@dynatrace/barista-components**: 6.1.1

## Detailed Description

The autocomplete for a tag filter should close when clicking into another tag filter.

## Possible Implementation

Either the [_getFreeTextOutsideClickStream](https://github.com/dynatrace-oss/barista/blob/5a7a5687dd274075552489fb969d4a530f1ab930/libs/barista-components/filter-field/src/filter-field.ts#L1006) method or the [_handleHostClick](https://github.com/dynatrace-oss/barista/blob/master/libs/barista-components/filter-field/src/filter-field.ts#L572) method should probably handle this.

## Attachments

![DeepinScreenshot_select-area_20200407101854](https://user-images.githubusercontent.com/11745660/78680432-7b3b7b00-78b9-11ea-9eaf-302a479d7b40.png)

**Comment by tomheller** [comment]
Hey @evan-bradley !
Thank you for reporting this, I was also able to reproduce this in our development environment, and you are right that it is probably the outsideClick handling that is preventing it from closing.

We have had some focus management issues with the filter field in the past and sadly it's not as trivial, but we will look into this problem.
