### ISSUE TITLE
Design token interface

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#847]
With the introduction of design tokens to our library, we should also make the tokens and their values more apparent and easily testable without needing to change the yaml file definitions to see the results. 

I am proposing to create an additional application within the repository, that targets the visualisation and customisation of the design tokens (with a primary focus on the colors and palettes). 

### Create a way to visualize the current design token palette

This could be either visualized as a grid, or already in examples like buttons and other components to create a relatable scenario.

### Visualize each color and show their contrast ratio

Show the contrast ratio to various other colors, i.e. the base color as well as to the text color.
This will help us to see where there might be problems with contrasts at a single glance without. 

### Add additional interactivity
The user should be able to tweak the base and key colors as well as the contrast ratio inputs and see the results within the application without needing to rebuild or retrigger the generation of design tokens. 

I would very much appreciate input from @dynatrace-oss/barista and @dynatrace-oss/ux-core what additional information or features for this one would be helpful.

**Comment by lukasholzer** [comment]
That's is a great idea in my opinion! So the application is running the functionality of the "builder" in a kind of serve mode to adapt the output on the fly and you can update the values with some kind of input fields?

We should then think about implementing the WCAG standards so that if you update a value it shows wich WCAG standards would be fulfilled.

**Comment by tomheller** [comment]
>  So the application is running the functionality of the "builder" in a kind of serve mode to adapt the output on the fly...

The conversion should be pure functions that get inputs and deliver outputs that the builder and the application can leverage. There is no need to run the builder in a `server` mode, imho.

**Comment by ffriedl89** [comment]
@SkaillZ & @tomheller I'd suggest closing this with the current state after #910 is merged
