### ISSUE TITLE
Filter field: allow programmatically adding disabled tags

### ISSUE THREAD

**Issue by evan-bradley** [dynatrace-oss/barista#848]
# Feature Request

## Summary

It would be helpful to allow for disabling tags when being programmatically adding them to a filter field.

### Problem
Currently tags can be programmatically added to the filter field, and can be disabled using instances given by the `currentTags` observable. However, in our usage, this causes issues with change detection (which we worked around by calling the `_handleInputChange` method), and requires us to manage the state of the tags in two separate places (once on insertion, once in the observable subscription).

Our use case is that we have two filter fields that use the same set of tags. The second filter field displays all the tags selected in the first filter field in a disabled state. Any tags selected exclusively in the second filter field are not disabled.

Example with selected tags for each:
filter field 1: `['one', 'two', 'three']`
filter field 2: `['one', 'two', 'three', 'four']`

In this case, 'one', 'two', and 'three' in filter field 2 would be disabled, 'four' would be enabled.

### Solution 
It would be helpful for the `editable` and `deletable` fields to exist on the tag objects passed into the filter field when programmatically adding them. This should allow change detection to pick up the change in state, and would allow us to manage tags in one place.

## Attachments

See the following StackBlitz for a basic example of our use case:
https://stackblitz.com/edit/github-ww73cs

**Comment by ffriedl89** [comment]
Hey @evan-bradley, thanks for reaching out. 
We have an example here https://barista.dynatrace.com/components/filter-field#readonly-non-deletable-non-editable-tags that sets the tag initially to non-editable and non-deleteable.
```
linzTag.editable = false;
linzTag.deletable = false;
this._changeDetectorRef.markForCheck();
```
You are correct that change detection needs another run to pick up the changes, by marking the component as dirty with a call to markForCheck this should work fine :) 

Let me know if this solves your usecase

**Comment by thomaspink** [comment]
you can also use the `disabled` property which automatically sets both, `editable` and `deletable` to false.

**Comment by tomheller** [comment]
@evan-bradley Did you have a chance to check if this solves the issue that you were having?

**Comment by evan-bradley** [comment]
Hi @ffriedl89, @thomaspink, and @tomheller, thanks for the replies. We are currently the following approach: we mark the tag as disabled call `_handleInput` on the component's instance, as calling `markForCheck` unfortunately has no effect for us.

```
linzTag.disabled = true;
this.dtFilterFieldComponentRef._handleInputChange();
```

We're seeing the following issues with this:
* We have to handle the state for each tag in two locations (once on adding, and once within the Observable subscription)
* There is a very brief flicker between when the tags are added and when they are marked as disabled, where you can visibly see the tag go from being enabled to disabled
* Hovering over a disabled tag will change the color of the text once, seemingly due to additional change detection being fired within the tag

For us, being able to set the `disabled` property would be both more ergonomic and offer a possible resolution to the two graphical issues we see since the tags would be in a disabled state the first time they are rendered.

**Comment by tomheller** [comment]
Hi @evan-bradley !

Right of the bat, I wanted to mention that all methods and members on the componentInstance, that are prefixed with an `_` are considered part of the private API. You should not rely or call them directly, as they are not meant to be used by the consumer (but need to be public for various reasons, i.e. usage in the components template itself). 
Internal members can change or vanish within minor versions, as they are not part of the API contract to the consumer.

The flicker you are seeing is probably based on you calling the `_handleInput` in a state where the filterField does not expect inputs. 

Due to the difference between the inputFilters and what the filterField eventually uses as filtered tags, I guess the way provided is currently the only way to set a filter disabled from the get go. 

I guess something like this, would probably be more convenient for you, right?

```typescript
@Component({ ... })
export class DtExampleFilterFieldReadOnlyTags<T> implements AfterViewInit {
  @ViewChild(DtFilterField, { static: true }) filterField: DtFilterField<T>;
  private DATA = {
    autocomplete: [
      {
        name: 'AUT',
        autocomplete: [{ name: 'Linz' }, { name: 'Vienna' }, { name: 'Graz' }],
      },
      {
        name: 'USA',
        autocomplete: [
          { name: 'San Francisco' },
          { name: 'Los Angeles' },
          { name: 'New York' },
          { name: 'Custom', suggestions: [], validators: [] },
        ],
      },
    ],
  };

  private _linzFilter = [
    this.DATA.autocomplete[0],
    this.DATA.autocomplete[0].autocomplete![0],
  ];
  _filters = [this._linzFilter];

  _dataSource = new DtFilterFieldDefaultDataSource<
    DtFilterFieldDefaultDataSourceType
  >(this.DATA);

  constructor(private _changeDetectorRef: ChangeDetectorRef) {}

  ngAfterViewInit(): void {
    // ### CONVENIENT CHANGE HERE ### 
    this.filterField.disableTags([this._linzFilter]);
  }
}
```

**Comment by evan-bradley** [comment]
That would definitely be more convenient, since we could set the disabled property using our existing data structure. What would be ideal for us is to have a property on the `DtFilterFieldDefaultDataSourceType` type providing the ability mark them as disabled (or enabled) in a declarative fashion. It would probably look something like this.

```
@Component({
  template: '<dt-filter-field [filters]="filters"></dt-filter-fileld>',
  ...
})
export class DtExampleFilterFieldReadOnlyTags<T> {
  private DATA = {
    autocomplete: [
      {
        name: 'AUT',
        autocomplete: [{ name: 'Linz' }, { name: 'Vienna' }, { name: 'Graz' }],
      },
      {
        name: 'USA',
        autocomplete: [
          { name: 'San Francisco' },
          { name: 'Los Angeles' },
          { name: 'New York' },
          { name: 'Custom', suggestions: [], validators: [] },
        ],
      },
    ],
  };

  private _linzFilter = [
    this.DATA.autocomplete[0],
    // ### PROPERTY ADDED HERE ###
    { ...this.DATA.autocomplete[0].autocomplete![0], disabled: true }
  ];
  private _viennaFilter = [
    this.DATA.autocomplete[0],
    // ### PROPERTY ADDED HERE ###
    { ...this.DATA.autocomplete[0].autocomplete![1], disabled: false }
  ];
  filters = [this._linzFilter, this._viennaFilter];

  _dataSource = new DtFilterFieldDefaultDataSource<
    DtFilterFieldDefaultDataSourceType
  >(this.DATA);

  constructor() {}
}
```

Let me know if this approach would make any sense.

**Comment by tomheller** [comment]
I'm afraid your suggestion will not work, because internally we are checking for instance equality on the filters. 
When doing this, 
```typescript
private _linzFilter = [
    this.DATA.autocomplete[0],
    // ### PROPERTY ADDED HERE ###
    { ...this.DATA.autocomplete[0].autocomplete![0], disabled: true }
  ];
```
you are creating a new instance of the linzFilter[1] element, which will no longer match. 
@thomaspink please correct me if I'm wrong here, but I don't think that this will work.

**Comment by evan-bradley** [comment]
@ffriedl89 and I discussed this, and were able to get the `changeDetectorRef.markForCheck()` call working, so thankfully that rids us of the internal method call.

Yeah, I see how it would be challenging to add a disabled property to the `DtFilterFieldDefaultDataSourceType` type, so I would be good with the solution you proposed. Declaratively setting the disabled property in some fashion would ideal, but a method for setting disabled tags would still allow us to consolidate our logic into a single update cycle within our component while letting us use the data structure we already have.

**Comment by ffriedl89** [comment]
We can currently support this feature. We will take the comments under consideration for a potential v2 - #951
