### ISSUE TITLE
Formatters: Check for spacing between values and units + rates

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#85]
Check for all formatters whether we have correct spacings between values and units.
Also check for rates

UX can provide input

Issue solved in this PR: https://github.com/dynatrace-oss/barista/pull/460

**Comment by gselltho** [comment]
### Research
After some research i found out that numbers and units have to be separated by space. For abreviations, like 1k for 1000, there should be no space.
### References
- https://physics.nist.gov/cuu/Units/checklist.html
15 Unit spacing
`There is a space between the numerical value and unit symbol, even when the value is used in an adjectival sense, except in the case of superscript units for plane angle.`
- https://en.wikipedia.org/wiki/Space_%28punctuation%29#Unit_symbols_and_numbers
Unit symbols and numbers
`The International System of Units (SI) prescribes inserting a space between a number and a unit of measurement (being regarded as a multiplication sign) but never between a prefix and a base unit; a space (or a centered dot) should also be used between units in compound units`
### Outcome
- `1k` and not `1 k`
- `99 %` and not `99%`
- `100 kB` and not `100kB`
- `100k %` and not `100k%`
- `100 kB/s` and not `100 kB /s` or `100kB/s`

**Comment by ffriedl89** [comment]
@rowa-audil FYI
