### ISSUE TITLE
Cleanup deprecations for 7.0 

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#853]
We missed some deprecations for 6.0 and there are some to be removed for 7.0.

Cleanup those deprecations.

**Comment by lukasholzer** [comment]
when do we plan the 7.0.0 milestone?

**Comment by ffriedl89** [comment]
Today we will announce the planned breaking version and i'd say sometime end of April or first week of May if no major blockers come up

**Comment by lukasholzer** [comment]
@rowa-audil can you please create a list with all the deprecations or do you already have a list that you can post into so that the work can be shared across?

**Comment by rowa-audil** [comment]
@lukasholzer I don't think we need a list.
@bardosmisi and I are currently working on finishing the last deprecations (breadcrumbs and filter-field).
