### ISSUE TITLE
Overlay: Rethink overlay

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#86]
currently we are solving the issue that the cdk overlay does not have a solution for overlays that need to follow the mouse
Rethink API and what we want to do with this service/directives

**Comment by ffriedl89** [comment]
After discussing several approaches that would cover all usecases we have internally and for our consumers we decided it would be best to wrap the cdk and provide the needed styles / css classes on the panel. 

Additionally the DtOverlay as is should be deprecated once we have the alternative in place. 

Current working name for the new implementation would be `DtTooltip`. We think this will remove some of the confusion between UX and development since a tooltip and the overlay as we called it in code looked the same but where completely different components.

We also want to use the new version in all components internally to battle test the new approach.

We still need to keep functionality for our edge cases like pinning and the `DtMouseFollowPositionStrategy`. 

Usecases that we see:
Adding a tooltip to any element
```html
<button dtTooltipOrigin #origin="dtTooltipOrigin"></button>
<ng-template dtTooltip [dtTooltipOrigin]="origin"></ng-template>
```
Service usage
```typescript
DtTooltip.create(config?): DtTooltipRef
```
Reusing the same template for multiple tooltips
This  is currently not planned to be possible inside the template, but using the service in typescript this is possible

Special wrapper for common chart tooltip usecases `dt-chart-tooltip` has a default template if none is provided or can accept a ng-template as a content child
```html
<dt-chart>
	<dt-chart-tooltip></dt-chart-tooltip>
</dt-chart>

<dt-chart>
	<dt-chart-tooltip>
		<ng-template>
			my awesome template
		</ng-template>
	</dt-chart-tooltip>
</dt-chart>
```

**Comment by ffriedl89** [comment]
As a more general discussion, is it worth the effort to wrap the directive/components provided by the CDK just so they are prefixed with `dt`.
What do we gain by doing that? 
For the overlay the API is quite straightforward and not that big, but thinking about #561 and drag & drop this needs way more effort.

I am seriously considering not wrapping the cdk related stuff, there is no real reason for me to do it. 

What's your take on it @dynatrace-oss/barista?

**Comment by tomheller** [comment]
I would be totally fine to communicate to users of our library that overlays should be handled via the cdk and provide styling for the base of the overlay within our library. 
The possibilities of what cdk already provides with their overlay api would just be limited if we wrap only selected parts of it.

**Comment by lukasholzer** [comment]
I agree there is no need to wrap the CDK with the `dt`

**Comment by thomaspink** [comment]
Would propose that we rework our position strategy and change all our internal dt-overlay usages to cdk. After all our internal overlays have been rebuilt with cdk, let's sit together and look and evaluate what had to be changed, which apis did (didn't) we use, and what are the learning of just using the cdk. Based on this we should decide if the dev can easily use the cdk or if we need to maybe shim away some apis.

**Comment by lukasholzer** [comment]
@ffriedl89 should we tackle this for version 8? Because then we should start deprecating our dt-overlay now for version 7.

**Comment by ffriedl89** [comment]
We can't deprecate it before we have an alternative in my opinion

**Comment by lukasholzer** [comment]
Not on our roadmap
