### ISSUE TITLE
Find as you type feature in icon search steals focus of text input control

### ISSUE THREAD

**Issue by knorp** [dynatrace-oss/barista#878]
Search works but input into field is interrupted by background reload. 

Steps to reproduce:
Use chrome Version 80.0.3987.163 (Official Build) (64-bit) on Windows 10
Go to /resources/icons on the internal barista version
Type search term, allow to reload while typing
-> focus from input box is lost

**Comment by rowa-audil** [comment]
Hi @knorp 
It seems to me that reloading while typing shouldn't happen in the first place. Do you know why your chrome reloads a currently visited page?
