### ISSUE TITLE
Improve visiblity of disabled inputs

### ISSUE THREAD

**Issue by beeme1mr** [dynatrace-oss/barista#880]
# Feature Request

## Summary

Disabled input fields are very difficult to read. 

## Feature Description

Improve the visibility of disabled inputs by updating the CSS. I've provided a Stackblitz example that contains a possible solution.

## Attachments

[Stackblitz example](https://stackblitz.com/edit/github-5n4bq1)

**Comment by tomheller** [comment]
Hi @beeme1mr! This seems like a good input, thank you for reporting this. 
I guess that this will/should affect all of our form fields and placeholders/values. I would love to have an opinion from @dynatrace-oss/ux-core on this one.

@beeme1mr would you be willing to contribute these changes to the library, once we have finished the discussion with UX which way we want to go?

**Comment by beeme1mr** [comment]
Sure, I'm happy to help. Please let me know what direction the team would like to go and I'll get started.

**Comment by ursula-wieshofer** [comment]
Hi @beeme1mr and @tomheller I totally agree that our disabled input field is very hard to read. I think the contrast might also not follow our accessibility guidelines.
I would love to change this, but we have to take into consideration that this should be consistent throughout our components. E.g. a disabled select has the same styling.

I really appreciate changing this, it's on our plate for a long time now.
Please make sure to have a contrast ratio of 4.5:1 as described in our [accessibility guidelines](https://barista.lab.dynatrace.org/guidelines/accessibility#readable) and please make sure all components which use this disabled styling are being updated.
I quickly checked: our Gray600 would have enough contrast ratio to the background. That would be a good option ;)

**Comment by SkaillZ** [comment]
@beeme1mr Would you like to contribute Ursula's suggestion to the library? We'd really appreciate it and we could guide you through the process.

**Comment by beeme1mr** [comment]
Sure, I can do that.

**Comment by tomheller** [comment]
Hi @beeme1mr! I quickly wanted to reach out if you will need any guidance or help on your end? Are you blocked by anything here or is it _just_ time that you need?
If you want, you can reach out and we can go through the contributing process together. 

If you think you will not have the time to contribute on this specific issue, please let us know so we can open it up for others to contribute again.

**Comment by beeme1mr** [comment]
Hi @tomheller, I plan on working on this but haven't found the time yet. I might be able to work on it later today. It appears to be a straightforward change but I'll reach out to you directly if I run into issues.
