### ISSUE TITLE
New charts section

### ISSUE THREAD

**Issue by subarroca** [dynatrace-oss/barista#885]
# Feature Request

With a growing number of charts it would be good to croup them all in a new section on barista called 'charts'. That way we could use components only for UI components, like buttons, sliders, cards, etc. And for a clearer view of the charts section we could have images of what you'd find inside, that way you would find a pie chart easier than by its name

**Comment by tomheller** [comment]
@ffriedl89 Maybe you can take this with you into your discussions next week?

**Comment by ffriedl89** [comment]
I think grouping charts somewhere in barista definitely makes sense, maybe a subsection of the components makes more sense. We would need some adjustment in the barista app to make this possible. But i totally agree with this and see the benefit of it :)
