### ISSUE TITLE
[Schematics] Create dt-barista-component schematic

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#889]
It should create a new folder inside the libs/barista-components using the '@nrwl/angular', 'library' schematic. This takes care of adding the references in the nx.json and angular.json file for the new library. 
All additional files or changes should follow the nrwl library schematic to conform to our structure. 
 
This schematic should also use the dt-example, dt-dev-page and dt-e2e schematic internally. 

The schematic should be part of the libs/workspace package.

**Comment by lukasholzer** [comment]
Moved to APM-266074
