### ISSUE TITLE
Barista: Add Slack notification status for barista build.

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#901]
## Feature Request

Add slack notifications for barista builds on our Jenkins.
When the build fails we want to get notified in our slack channel and if a public build is done the same to be promoted on Zeit. Maybe post the URL for the promotion to production in the channel.

```groovy

post {
  failure {
    cleanWs deleteDirs: true
    slackSend(
      botUser: true,
      channel: 'dodos',
      color: 'danger',
      message: 'Barista build failed: ${env.BUILD_NUMBER}',
      teamDomain: 'dynatrace',
      username: 'Barista Build',
      iconEmoji: '☕️',
      tokenCredentialId: 'slack-notification-token'
    )
  }
  success {
    slackSend(
      botUser: true,
      channel: 'dodos',
      color: 'good',
      message: 'Successfully published a new public version of barista',
      teamDomain: 'dynatrace',
      username: 'Barista Build',
      iconEmoji: '☕️',
      tokenCredentialId: 'slack-notification-token'
    )
  }
}
```

**Comment by lukasholzer** [comment]
@ffriedl89 should we tackle this?

**Comment by ffriedl89** [comment]
@lukasholzer Yeah let's try to tackle this :)

**Comment by tomheller** [comment]
Please consider not sending a notification for passing builds. This could get spammy real quick, and will be quickly glanced over

**Comment by ffriedl89** [comment]
Use slack-notification-token on ci env
