### ISSUE TITLE
Barista: Server Side rendering of index page fails.

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#905]
# Bug Report

Currently, all barista pages are static pages that are rendered on the server. Due to a race condition, the index.html file gets replaced with its original file in the builder. That is the reason why the index page is not server side rendered.

All other pages are fine.

## Possible solution.

Rename the output file to `index.original.html` and launch it for the generation. (This is already done)
* Fix the bug with the renaming.

**Comment by tomheller** [comment]
Progress is blocked here. @lukasholzer please reach out to @rowa-audil if you have time to tackle this one
