### ISSUE TITLE
Restyle confirmation dialog

### ISSUE THREAD

**Issue by SirTroyer** [dynatrace-oss/barista#922]
# Feature Request

Since our confirmation dialog currently is too subtle for our users to see it on larger screens we would like to make it more prominent.

Following changes should be done:
* make it darker
* move buttons to the left (more consistent with our button positioning guidelines + on larger screens the button can be too far away from the content)
* do not dock the confirmation dialog directly to the edge of the screen but give a little margin
* add shadow to make it pop from the content above
* text should be placed above the buttons making the confirmation dialog higher and therefore also improve visibility
* provide option to make the confirmation dialog wiggle (future behaviour for the screens will be the following: when the user tries to navigate away from the screen with unsaved changes we'd like to stay on the page and wait for the user to do either save or discard and therefore draw the users attention to the confirmation dialog with a wiggle animation also indicating that what the user anticipated to do is invalid)

see following mockup:
![confirmation_dialog_mock](https://user-images.githubusercontent.com/61140594/80456472-ee229980-892d-11ea-97d0-4704b6c1ae0d.jpg)

**Comment by tomheller** [comment]
I guess this is related to the #577 
There was a discussion ongoing and based on the comment from @ffriedl89, seems that you are willing to contribute. Is this still accurate? 

Can you outline the API changes that will be required for your improvements?

**Comment by SirTroyer** [comment]
oh right #577 is a duplicate issue
yes I'm still willing to contribute we planed to implement it in this sprint
hmm not sure wat API changes are required but it should not change a lot but just a new capability for the wiggle animation the rest are just styling changes I guess

**Comment by tomheller** [comment]
> but just a new capability for the wiggle animation

This is what I was referring to. Maybe just quickly outline what the default option is, and how you can (opt in / opt out) of the wiggle.

**Comment by SirTroyer** [comment]
hmm I thought actually about providing a stream as a parameter like `wiggle` to trigger the animation because I guess the confirmation dialog component does not know / probably should not know about navigation
or am I wrong?

**Comment by tomheller** [comment]
You are right, the confirmation-dialog should not know about the navigation. 
That's why I was asking about details on this one. 
An input subject that you subscribe on within the confirmation dialog or a public method would be fine.

**Comment by SirTroyer** [comment]
perfect :)

**Comment by SirTroyer** [comment]
I'm currently struggling with the indent from the menu bar as the confirmation dialog is a template that will be set into a CDK overlay. How can I make it aware of the navigation bar or at least how can the component provide an opportunity to make the wrapper aware of this and adjust the indent from the left?
Does anyone have a good idea how to make it possible without an a hack or a bad API?
