### ISSUE TITLE
Sunburst Chart: Add E2E test to ensure code quality.

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#925]
# Tests

As a follow-up issue for the pull request #883 the newly added Sunburst Chart needs some E2E tests to ensure proper code quality. Connected to the issue #786

The scope of this issue should be to create E2E tests that are testing the interaction with the chart. Common test cases would be interacting with the chart overlay through hovering sections of the chart. Furthermore, it can be switching (filtering) the chart series by clicking a button that applies a new series.

It is not part of the scope to test some internal functions **only user-facing behaviour should be tested**.

**Comment by lukasholzer** [comment]
@subarroca @pedromosquera As you are the code owners of this component would you contribute the tests to ensure our code quality?

**Comment by lukasholzer** [comment]
@subarroca can you give a status on the progress?

**Comment by subarroca** [comment]
Pending. I'll start this week with that
