### ISSUE TITLE
Add custom public linting to components package

### ISSUE THREAD

**Issue by thomaspink** [dynatrace-oss/barista#93]
- [ ] Move rules to a different location (out of tools; because it is code that ships to the consumer it should not be in the tools folder)
- [ ] Build rules and add it to shipped artifact
- [ ] Reapply these rules to the barista-examples app
- [ ] Add command to development.md

**Comment by ffriedl89** [comment]
old commands from development.md
```
## Custom TSLint rules

Run the following command to build the custom TSLint rules

```
npm run tslint:build
```

To test the rules run

```
npm run tslint:test
```
```

**Comment by ffriedl89** [comment]
I think we can close this issue for now. We are already bundling our linting rules into the package
