### ISSUE TITLE
Breadcrumbs: Make them responsive

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#94]
Breadcrumbs should adapt to smaller screen / container sizes. 

Breadcrumb items should be moved into an overlay if they don't fit the screen starting at the very first item. 
Keep in mind that the entries inside the breadcrumbs get very long. Also the overlay should truncate (ellipsis) the entries and have a max-width set. Set a title attribute with the complete value. The newly released DomPortal that moves dom nodes into the portal and moves them back after the portal is destroyed might be something that can help us here.
See: https://github.com/angular/components/pull/16101

The desired behaviour should look like
![image](https://user-images.githubusercontent.com/2905693/68758739-a83b7880-060e-11ea-821c-deb65772989a.png)

the shark menu as inspiration might be useful https://github.com/jayfreestone/priority-plus

- [ ] Implement responsiveness
- [ ] Add tests that check correct placement of breadcrumb items
- [ ] Check whether the domportal can help us with the dt-taglist as well

**Comment by ffriedl89** [comment]
The newly released DomPortal that moves dom nodes into the portal and moves them back after the portal is destroyed might be something that can help us here. 

https://github.com/angular/components/pull/16101

**Comment by ffriedl89** [comment]
I've tinkered around quite a bit with this - unfortunately this is currently on hold due to other tickets having a higher priority.

**Comment by lukasholzer** [comment]
Moved to APM-266072
