### ISSUE TITLE
Use durationPipe in event chart x-axis

### ISSUE THREAD

**Issue by subarroca** [dynatrace-oss/barista#940]
# Feature Request

## Summary

X axis can get a better formatting

## Feature Description

- Problem: Currently the duration format is similar to the duration pipe but built autonomously
- Solution:  Use duration pipe to make it consistent along the platform

- Problem: If chart is small ticks overlap
- Solution:  Create as many ticks as allowed in a view

**Comment by tomheller** [comment]
Thanks for raising this. We wanted to do this for quite some time now, but the duration formatter finally made it to a stable release. 
Thank you for taking care of this.
