### ISSUE TITLE
Chart Selection Area: Snap to closest timestamp

### ISSUE THREAD

**Issue by Sherif-Elhefnawy** [dynatrace-oss/barista#945]
# Feature Request

## Summary

Presently, when the user wants to select a timeframe on a chart that contains specific timestamps, he can start dragging from one point to the end point. The issue is that the user must start his timeframe selection EXACTLY at the timestamp or slightly after which seems a bit strict.

An example is shown below:
![Annotation 2020-05-05 092537](https://user-images.githubusercontent.com/59170440/81043430-87aff500-8eb2-11ea-8027-5e3fea14b8cd.png)
Here we see that the selection area started right before 13:55 and thanks to the bar at that timestamp, the user would think that he is selecting exactly at 13:55, however the timeframe starts at 13:54 since the user didn't start his dragging at or after 13:55. 

It would make sense to actually snap to the closest timestamp when beginning to drag the timeframe.

## Feature Description

When beginning to drag for selection, the closest timestamp should be considered as the starting point. However, this really depends on the distance from the beginning of the mouse down event to the timestamp. Calculating the distance between timestamps relative to the mouse down location is important here as well as how forgiving the snapping would be. 

A question would be whether the snapping be limited to the beginning or also extended to the end  point as well.
 
In order to support snapping to the closest timestamp, the component "dt-chart-range" needs to be adapted.

**Comment by tomheller** [comment]
Hi @Sherif-Elhefnawy!

This seems like a good extension to the selection area, a couple of things to note here:

* The snapping behavior should be opt-in on the selection area
* How would we deal with missing data points on a series?
* Do we want to set the snapping to a series, or to the a collection of all data points over all series? 

Would you be willing to contribute this feature to the library. As the code owner of the selection area, @lukasholzer would definitely assist you if we ironed out the details of the snapping behavior.

**Comment by Sherif-Elhefnawy** [comment]
Hi @tomheller ,

About the points you mentioned:
-  For missing data points, how is that dealt with now for the selection area?
- I would assume that we snap it to a series that is shown rather than all data points

I can't promise unfortunately about contributing soon but it is on our backlog.

**Comment by tomheller** [comment]
> For missing data points, how is that dealt with now for the selection area?

It's not, currently there is no snapping for the selection area and therefor no direct connection between the selection area and the date in the chart. 

> I would assume that we snap it to a series that is shown rather than all data points

Yes, if we do that, we don't need to deal with the problem of missing data. It will just not be possible to snap to a specific time, if there is no datapoint there. Considering your example, if we would snap to the columnSeries, it would not be possible to snap to 13:57, because there is no datapoint there. 
Edge cases of single datapoints in a series need to be considered, though. 

@Sherif-Elhefnawy It does not need to be you who contributes the feature. I just wanted to know if you would be willing to do it. 
I have added the help-wanted label. Maybe somebody else will grab this one in the meantime.

**Comment by christian-fischer** [comment]
We have a similar use case as @Sherif-Elhefnawy but with two series.
No selection/snapping for no datapoints is fine for our use case, but that means no points in all series.

**Comment by lukasholzer** [comment]
Will be handled by @Sherif-Elhefnawy and @christian-fischer

**Comment by christian-fischer** [comment]
notes on intro by @lukasholzer :
- snapping would be very similar to already existing clamping functionality
- snap only after dragging finished
- ensure that it works for mouse/touch/keyboard

**Comment by lukasholzer** [comment]
Moved to APM-266093
