### ISSUE TITLE
Refactor Schematics that we don't rely on the CDK

### ISSUE THREAD

**Issue by lukasholzer** [dynatrace-oss/barista#948]
## Description

With the CDK update from **9.2.1** to **9.2.2** the CDK broke our library as they do not follow semantic versioning and they consider the schematics library not as public - even though they do not state this and export it like the other stuff. https://github.com/angular/components/issues/19258#issuecomment-624160584

Due to the fact that our consumers can use the new patch version in their projects we have to get rid of the CDK in the schematics – otherwise our `ng update @dynatrace/barista-components` will fail on the clients' side if they use the newer CDK version.

This is very important for #944 otherwise we can forget our upgrade schematic.

**Comment by lukasholzer** [comment]
Fair enough they state it in the [README](https://github.com/angular/components/blob/master/src/cdk/schematics/README.md)

**Comment by devversion** [comment]
Sorry if that was not clear enough. We plan on making this more clear in the future by not exporting anything from `cdk/schematics`, but exporting from `cdk/schematics/private`.
