### ISSUE TITLE
Table datasource documentation

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#975]
The DtTableDataSource has a lot of undocumented features that can be quite beneficial for advanced usage, i.e. the functions
* `addSortAccessorFunction`
* `removeSortAccessorFunction`
* `addComparatorFunction`
* `removeComparatorFunction`

As the table documentation in itself is already quite long, it might be feasible to create a sub page for the datasource documentation where all use cases are outlined and described. From easy, out of the box setup with simple columns until the more complicated sorting and filtering with custom-accessor and comparator functions. 

There are a few options for as an outlet here.
1. Markdown file within the table source, which will probably require us to make some adjustments in the page generation for barista. 
2. Strapi page, but then it will be hard to get it into the components subtree. 
3. Figure out how to create blogs and write this as some sort of blog article, _Mastering the DtTableDatasource_.

**Comment by SkaillZ** [comment]
Regarding option 1 suggested by @tomheller: It seems like the easiest way is creating a subfolder in `libs/barista-components/table` (e.g. `docs/table-data-source`). The builder will just pick it up and show it in the components tree, no code adjustments required.

**Comment by lukasholzer** [comment]
Moved to APM-266086
