### ISSUE TITLE
Chart Range: Range scaling issue

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#99]
Range does not get upscaled correctly if the window is resized to a very small size and then resized very fast to a bigger size. 

Check whether the viewport resizer uses the correct operators - we always need the last emission after the debounce time passed

**Comment by dovidio** [comment]
It seems to be related to the clamping done here: https://github.com/dynatrace-oss/barista/blob/b89786da642171a16a11322236e7f9530b2f2afe/components/chart/src/range/range.ts#L534

When resizing fastly, left is clamped to maxWidth, and width is clamped to maxWidth - left, which is effectively 0. Removing the clamping seems to solve the issue, however this might reintroduce the issue where it's possible to grow the selection outside the chart area

**Comment by lukasholzer** [comment]
I think this is an operator issue that skips an emission due to debouncing. @dovidio thanks for your investigation but as you pointed out we need the clamping that nobody can resize the range larger than the highcharts container.
